Zoinkwiz/quest-helper

src/main/java/com/questhelper/QuestHelperOverlay.java

Allows resizing and using the Runelite's colorOverlayBackground config option to recolor the background of the quest helper overlay.

overlay: use OverlayPanel instead of Overlay

---

src/main/java/com/questhelper/quests/atailoftwocats/ATailOfTwoCats.java

fixes #7.
Goes from Varrock Museum to Varrock Castle's library.

Correct Reldo's location in A Tail of Two Cats

---

src/main/java/com/questhelper/QuestHelperPlugin.java

This resolves issues with an EventBus that subscribes automatically rather than using a register() function.
(it was possible to receive events before the plugin was ready for them, causing havoc.)

plugin: inject members immediately after decleration

---

src/main/java/com/questhelper/steps/ConditionalStep.java

Since QuestStep already subscribes to the "onWidgetLoaded" event we want to override and re-use that subscription instead of creating another one. Hence ConditionalStep should override not subscribe.

Fixed issue where widgets would fire 2 times in ConditionalStep

---

src/main/java/com/questhelper/quests/thehandinthesand/TheHandInTheSand.java

* Sandy's desk wasn't being highlighted
* The doorway indicator was one tile too far to the west

Fix coordinates in The Hand in the Sand

---

src/main/java/com/questhelper/quests/thegolem/TheGolem.java

- Fix step initially not pointing at Broken Golem due to wrong NPC ID being used

Fix golem NPC to Broken version of the NPC for first clay addition

---

src/main/java/com/questhelper/quests/curseoftheemptylord/CurseOfTheEmptyLord.java

2 steps on the Curse of the Empty Lord miniquest were not updating on the panel for path 2.
Before
After

Fixed 2 steps in Curse of the Empty Lord miniquest

---

src/main/java/com/questhelper/quests/atailoftwocats/ATailOfTwoCats.java

The Catspeak amulet needs to be equipped as both steps that use this required it equipped as you talk to your cat and the NPC at the same time.

Small fix in A Tail of Two Cats

---

src/main/java/com/questhelper/quests/dragonslayerii/DragonSlayerII.java

Minor Dragon Slayer 2 changes:
- Ghostspeak amulet required equipped (talking to ghosts).
- Add additional dialog step when talking to the Oneiromancer.
- Add additional step of talking to Dallas after the mural to the panel.

Small DS2 Changes

---

.run/Run QuestHelper.run.xml

This will work for IntelliJ versions 2020.1+.
Multiple run configurations can be added to the .run/ directory. (i.e. build configurations, etc.)
The configuration name can be changed of course. As for the JDK; I personally use OpenJDK 13 but used the Bundled option so it should work with any installation of IntelliJ.
This should make it extremely easy for people to start doing some dev work for this project. If they don't have much experience with Java or IntelliJ it can be a bit of a pain to figure out how to run Runelite via this project. This allows them to not have to worry about it and just start the actual coding.
Picture of Run Configuration: https://i.imgur.com/h59n63u.png

Create a shareable run configuration for IntelliJ 2020.1+

---

src/main/java/com/questhelper/requirements/CombatLevelRequirement.java
src/main/java/com/questhelper/requirements/FavourRequirement.java
src/main/java/com/questhelper/requirements/FollowerRequirement.java
src/main/java/com/questhelper/requirements/FreeInventorySlotRequirement.java
src/main/java/com/questhelper/requirements/ItemRequirements.java
src/main/java/com/questhelper/requirements/NoItemRequirement.java
src/main/java/com/questhelper/requirements/PrayerRequirement.java
src/main/java/com/questhelper/requirements/QuestPointRequirement.java
src/main/java/com/questhelper/requirements/QuestRequirement.java
src/main/java/com/questhelper/requirements/Requirement.java
src/main/java/com/questhelper/requirements/Requirements.java
src/main/java/com/questhelper/requirements/SkillRequirement.java
src/main/java/com/questhelper/requirements/SpellbookRequirement.java
src/main/java/com/questhelper/requirements/WeightRequirement.java
src/main/java/com/questhelper/steps/conditional/Operation.java
src/main/java/com/questhelper/steps/conditional/SkillCondition.java
src/main/java/com/questhelper/steps/conditional/VarbitCondition.java
src/main/java/com/questhelper/steps/conditional/VarplayerCondition.java
src/main/java/com/questhelper/steps/conditional/WeightCondition.java

Lots of changes in this one. This PR adds missing `Requirement`s as well as removing some duplicate code.
I'm marking this as a draft because it's 3AM and I wanted
Quest Requirements are found at: https://oldschool.runescape.wiki/w/Quests/Requirements
I was able to run QuestHelper without any errors with these changes but I did not test quests that specifically used some of these requirements.
I would appreciate it if someone could review this and see if I missed anything or changed some logic somewhere.
****1. Duplicate code****
Duplicate code was found in several classes, mainly `getDisplayTextWithChecks` where all it did was use the same `LineComponent` builder to combine the display text and `getColor`. This bit of code was moved back into the abstract `Requirement`.
`getColor` was …

Add missing Requirements

---

src/main/java/com/questhelper/quests/coldwar/ColdWar.java

- Added World Points to a lot of steps, this actually fixed one step that continuously crashed (enterAvalanche).
- Move talkToLarryAfterEmotes into the conditional step for returning to Relleka otherwise this would not progress.
- Moved "Yes" dialog step from talkToLarryOnIcebergWithSuit to tuxedoTime as the varbit progreses to this step before the dialog step.
- Removed readMissionReport and kgpBeforePingPong from the Panel as these steps are skipped and are not required for any progression within the quest.
As always, reach out if there are any questions/concerns/anything :)
Edit: Formatting on comments.

Cold War Fixes

---

src/main/java/com/questhelper/QuestHelperPlugin.java

This is a simple change but it allows us to start talking about what tools we want to add for when users are working on QuestHelper.
Either when they are making a quest or just doing dev work in general.
I did a short test and confirmed this worked by adding to the overlay in the `QuestHelperOverlay` class.
I believe with this we can now start working on some useful tools for when quests need to be added/edited.
You could also a way for devs to 'step' through their existing steps without having to progress through a quest so they can make sure their zones/objects/npcs work as intended. Obviously these won't work for instances or places that only appear during the quest, but for most things this should remove the doubt that a particular step works.

Add the ability to start creating developer tools

---

src/main/java/com/questhelper/QuestHelperConfig.java

Also added a config section to better define the different parts of the config.
The filters should now read like a sentence.
(e.g. Show all grandmaster quests in alphabetical order is equivalent to what's in the picture)
I was originally going to include completed quests right below the main filter drop down box but it ruins the way that section looks.
Picture: https://i.imgur.com/mbh2ZRn.png

Change how config filters are ordered.

---

src/main/java/com/questhelper/BankItems.java
src/main/java/com/questhelper/QuestHelperPlugin.java
src/main/java/com/questhelper/banktab/BankTabItem.java
src/main/java/com/questhelper/banktab/BankTabItems.java
src/main/java/com/questhelper/banktab/QuestBankTab.java
src/main/java/com/questhelper/banktab/QuestBankTabInterface.java
src/main/java/com/questhelper/banktab/QuestHelperBankTagService.java
src/main/java/com/questhelper/requirements/ItemRequirement.java
src/main/java/com/questhelper/requirements/ItemRequirements.java

This adds a button to the bank which brings up an interface with the items you'll need for the currently active quest, with the items sorted into sections, and the number of items indicated.
Few things in terms of player-facing bits I'm unsure on:
1. The position of the button is far from ideal. I've put it at the top right to avoid it conflicting with any existing Runelite functionality, but it feels a bit rubbish. Any ideas on good placement + how it should interact are appreciated
2. Quantity overlay is okay, but can be bad for larger quantities, and over brighter items.
3.

Add basic Quest Bank Tab solution

---

src/main/java/com/questhelper/QuestHelperConfig.java
src/main/java/com/questhelper/QuestHelperDebugOverlay.java
src/main/java/com/questhelper/QuestHelperPlugin.java
src/main/java/com/questhelper/questhelpers/QuestDebugRenderer.java
src/main/java/com/questhelper/questhelpers/QuestHelper.java

This will allow devs to have more information on screen while they are working on quests.
This PR implements the basic framework that will allow devs to add debug information on screen while working in dev-mode.
At the moment, all it does is display the current Var of the active quest, but devs can override that behavior in each quest using the correct methods.
See `QuestHelperRenderer` for which method to use.
`renderDebugOverlay` is for rendering overlay similar to how quest step overlays are rendered.
`renderDebugWorldOverlayHint` is for rendering overlays similar to how fishing spots/agility spots are rendered
`renderDebugWidgetOverlayHint` is for rendering overlay hints on widgets

Add the basic framework for adding debug information

---

src/main/java/com/questhelper/requirements/QuestRequirement.java

For example, "Fairy ring access" looks better than "Fairytaile II - Cure a Queen In Progress"

QuestRequirement now displays custom display text.

---

src/main/java/com/questhelper/IconUtil.java
src/main/java/com/questhelper/QuestHelperPlugin.java
src/main/java/com/questhelper/QuestHelperWorldMapPoint.java
src/main/java/com/questhelper/panel/QuestHelperPanel.java
src/main/java/com/questhelper/panel/QuestOverviewPanel.java
src/main/java/com/questhelper/panel/QuestRequirementPanel.java
src/main/java/com/questhelper/panel/QuestSelectPanel.java
src/main/java/com/questhelper/steps/overlay/IconOverlay.java

Removes the need for ImageUtil in the QuestHelper codebase and is much easier to maintain.
Replaced all unnecessary `ImageUtil.loadResourceFromStream` calls with our own.

Add enum for QuestHelper icons.

---

src/main/java/com/questhelper/quests/theknightssword/TheKnightsSword.java
src/main/java/com/questhelper/requirements/NpcRequirement.java
src/main/java/com/questhelper/requirements/ZoneRequirement.java

1. When you search the cupboard for the portrait, the cupboard wasn't highlighting when it was closed (different object id).
* Also added new requirements `ZoneRequirement` and `NpcRequirement` to see if Sir Vyin is not in the room when you search it.
2. Some step requirements were wrong with thurgo after you give him the portrait. Remove the unnecessary portrait requirement and adjusted the display text to match.

Fix Knight's Sword not highlighting cupboard and step requirement

---

src/main/java/com/questhelper/ItemCollections.java
src/main/java/com/questhelper/quests/makinghistory/MakingHistory.java

Also adds a step requirement for when entering Port Phasmatys so players know to bring 2 ecto-tokens if they haven't completed Ghosts Ahoy.
Also adds tooltip to ghostspeak amulet requirement saying that they can also use Morytania Legs 2 or higher.
Add tooltips to clarify the other options for entering Port Phasmatys (charter ship, Ghosts Ahoy completed, or what to bring to earn some ecto-tokens at the Ectofunctus).

making-history: Fix missing requirement for relleka teleport.

---

src/main/java/com/questhelper/QuestHelperConfig.java
src/main/java/com/questhelper/steps/DetailedQuestStep.java
src/main/java/com/questhelper/steps/NpcStep.java
src/main/java/com/questhelper/steps/ObjectStep.java

Adds toggle in the settings pane for the flashing arrow on the minimap and overworld (enabled by default). This change does not affect the boxes around objects, but that could be added if desired. 
This feature is one i personally wanted, as I like the quest plugin, but found the arrows made quests too easy (and thus of a feeling of accomplishment). 
Tested through Misthalin Mystery, Could enable/ disable arrows for NPCs, objects, and objectives, and arrows would automatically stop & resume being rendered.

Arrow Toggle

---

src/main/java/com/questhelper/quests/theforsakentower/PotionPuzzle.java

**Issue:** When "Cleansing fluid" appears in line 1 (aka yellow position on the wiki image below), the puzzle variation is not detected.
**Fix:** Update regex to reflect line text. 
I assume the original author had a puzzle that said "Toadflax blend is directly left of..." and accidentally included the word "blend" in the regex. I finished the rest of the quest after testing this change in game. Cheers for the awesome plugin!
Quick reference: https://oldschool.runescape.wiki/w/The_Forsaken_Tower/Quick_guide#/media/File:The_Forsaken_Tower_-_old_notes_explanation.png
More context: https://oldschool.runescape.wiki/w/The_Forsaken_Tower/Quick_guide#Potion

The Forsaken Tower: fix potion puzzle

---

src/main/java/com/questhelper/quests/thefremennikisles/TheFremennikIsles.java

As per the wiki a knife is required: https://oldschool.runescape.wiki/w/The_Fremennik_Isles#Details:~:text=A%20knife,-8

Add missing knife requirement

---

src/main/java/com/questhelper/quests/theslugmenace/TheSlugMenace.java

This adds some missing QOL teleports from Slug Menace.
It did not recommend teleports near the runecrafting altars nor did it recommend a necklace of passage for when you have to talk to Jorral.
Also added more recommended ardougne teleports since we now recommend teleporting to jorral.

Add some missing QOL teleports to Slug Menace.

---

src/main/java/com/questhelper/QuestHelperConfig.java
src/main/java/com/questhelper/QuestHelperOverlay.java

As per a request on Discord, this allows people to not show the overlay on screen. This does not include arrows/tile highlights/etc. This only prevents the actual overlay panel from being displayed.

Add the option to not show the overlay panel on screen.

---

src/main/java/com/questhelper/QuestHelperQuest.java

It's a P2P quest, not a F2P quest.
https://oldschool.runescape.wiki/w/The_Ascent_of_Arceuus

Change Ascent of Arceuus to be P2P quest instead of F2P

---

src/main/java/com/questhelper/quests/biohazard/Biohazard.java

While completing Biohazard I noticed that the helper states "Take the Plague Sample to the Chemist in Rimmington. You can take a boat from Ardougne Dock to Rimmington for 30gp."
30gp was not a recommended item, so this update just adds it

Biohazard- add 30gp to recommended items

---

src/main/java/com/questhelper/quests/bigchompybirdhunting/BigChompyBirdHunting.java
src/main/java/com/questhelper/quests/myarmsbigadventure/AddCompost.java
src/main/java/com/questhelper/quests/myarmsbigadventure/MyArmsBigAdventure.java
src/main/java/com/questhelper/quests/taibwowannaitrio/TaiBwoWannaiTrio.java
src/main/java/com/questhelper/quests/thefremennikexiles/TheFremennikExiles.java
src/main/java/com/questhelper/quests/xmarksthespot/XMarksTheSpot.java

Added Teleport to X Marks the Spot
Big Chompy Bird Hunting:
Should now correctly show to 'use' the Chompy on Rantz.
Should now correctly show 'use' with Seasoned Chompy on Rantz.
Tai Bwo Wannai Trio:
Fixed broken quest step.
Clarified quest step for skinning monkey corpse. 
My Arms Big Adventure:
Removed Ultracompost as recommended Alternative for Preparing to Grow Farming Patch.
Fremennik Exiles:
'Baldur' has returned to Odin and in his place, left behind the correct spelling of 'Bardur' in the Waterbirth Dungeon for us to discover. (Fixed Typo)

Minor Bug Fixes

---

src/main/java/com/questhelper/achievementdiaries/karamja/KaramjaMedium.java

In the Karamja Medium Diary, one of the requirements is intended to be the Shilo Village quest, but ended up being a duplicate line of The Grand Tree, probably due to a copy-paste error. This PR fixes these.

Fix karamja medium diary quest requirement

---

src/main/java/com/questhelper/quests/clientofkourend/ClientOfKourend.java

Quest 'Client of Kourend' requires completion of 'X Marks the Spot'.
Source: https://oldschool.runescape.wiki/w/Client_of_Kourend (also confirmed in-game)

Added quest requirement to 'Client of Kourend'

---

src/main/java/com/questhelper/quests/eaglespeak/EaglesPeak.java

Adds in recommended items for the "Eagles' Peak" quest.
The items are:
* Varrock teleport
* Ardougne teleport
* Dramen staff or Necklace of passage to get to the quest (multiple times throughout the quest)

Add recommended items to "Eagles' Peak" quest

---

src/main/java/com/questhelper/quests/junglepotion/JunglePotion.java

Changes `Surive` to `Survive`. This will resolve issue #322

Fix spelling mistake in 'Jungle Potion' quest

---

src/main/java/com/questhelper/quests/thefremenniktrials/TheFremennikTrials.java

These skills are technically optional however our current guide is not written to cover the optional case. I don't have a way to replay this quest currently to add the optional case, so I am making the safe change only, for now.
Resolves issue #257

Add skill requirements to 'Fremennik Trials' quest

---

src/main/java/com/questhelper/quests/recipefordisaster/RFDPiratePete.java

Adds teleports for `Lumbridge` and `Watchtower` as recommended items. Also specifies breadcrumbs when using a knife on bread, as a steak sandwich is now also an option

Add teleports as recommended items on 'RFD: Pirate Pete' quest

---

src/main/java/com/questhelper/quests/recipefordisaster/RFDLumbridgeGuide.java

Adds `Necklace of Passage` and `Lumbridge teleport` as recommended items

Add teleports to recommended items for 'RFD: Lumbridge Guide' quest

---

src/main/java/com/questhelper/achievementdiaries/falador/FaladorHard.java
src/main/java/com/questhelper/quests/dragonslayerii/DragonSlayerII.java

Fixes Amelias location in DS2, this should stop players wondering about, and getting lost. (Reported at least 2x daily)
Added Slayer Req for Fally Hard.

Fix Amelia location in DS2

---

src/main/java/com/questhelper/quests/clientofkourend/ClientOfKourend.java

Shayzien and Lovakengj shops were moved in the AKD release, current coordinates don't match their in-game locations.

ClientOfKourend: Updated shop coordinates after AKD release

---

src/main/java/com/questhelper/banktab/BankText.java
src/main/java/com/questhelper/banktab/BankWidget.java
src/main/java/com/questhelper/banktab/QuestBankTab.java

This will swap around a real item in the bank with fake items, making it appear that fake items are real and interactable.
Inspired by geheur's great work in https://github.com/geheur/bank-tag-custom-layouts.

Add ability to have duplicate bank items

---

src/main/java/com/questhelper/quests/gardenoftranquility/GardenOfTranquillity.java

I've noticed that you cannot use the Bottomless Bucket for the compost requirement during the Garden of Tranquility, though it isn't mentioned within the plugin. I've added a simple tooltip to make it known that you cannot use a bottomless bucket.

Garden of Tranquility: added tooltip to compost requirement.

---

src/main/java/com/questhelper/achievementdiaries/falador/FaladorMedium.java

The Chemist's house should have this location

Fix Chemist location in Falador Medium

---

src/main/java/com/questhelper/achievementdiaries/falador/FaladorMedium.java

The name of the area should be Mudskipper Point rather than Mogre Point, I believe.

Fix Mudskipper Point name in Falador Medium

---

src/main/java/com/questhelper/quests/ghostsahoy/GhostsAhoy.java

Closes #422 by correcting the typo in the "Talk with Robin" step.

Correct typo in Ghosts Ahoy

---

src/main/java/com/questhelper/achievementdiaries/falador/FaladorMedium.java

The name of the building containing the Wine of Zamorak is called the "[Chaos Temple](https://oldschool.runescape.wiki/w/Chaos_Temple_(Asgarnia))". Having the step refer to the "Chaos Altar" implies the [Chaos Altar](https://oldschool.runescape.wiki/w/Chaos_altar) in level 9 wilderness. This change brings the name in line with what is used on the OSRS Wiki for this [diary task](https://oldschool.runescape.wiki/w/Falador_Diary#Medium) (Falador medium - step 2).

Replace "Chaos Altar" step with "Chaos Temple"

---

src/main/java/com/questhelper/quests/mountaindaughter/MountainDaughter.java

In the Mountain Daughter quest, you need to rub mud on the tall tree to be able to climb over the tree.  If you don't have any mud it isn't extremely obvious how to get the mud (Although it does have some text mentioning you need to dig it up in the item requirements, there isn't an explicit arrow / step pointing to where you need to dig), so I added a step that explicitly calls out the need to dig up mud if you don't have any and haven't rubbed the mud on the tree already. 
This is my first contribution to the plugin so if anything is wrong / should be changed / could be better, please call it out.

Add step for digging up mud within MountainDaughter quest for clarity

---

src/main/java/com/questhelper/quests/gardenoftranquility/GardenOfTranquillity.java

Currently the plugin states that Kragen is east of Ardougne, while north-east is a more accurate description

Garden of Tranquility: clarify Kragen's location

---

src/main/java/com/questhelper/quests/belowicemountain/BelowIceMountain.java
src/main/java/com/questhelper/quests/thefremennikisles/TheFremennikIsles.java

- "Acess" -> "Access" in Below Ice Mountain
- Fixed Neitiznot shield requirement from 46 Crafting
to 56 Woodcutting in Fremennik Isles
Fixes #529
Fixes #524

Fix Below Ice Mountain & Fremennik Isles typos

---

src/main/java/com/questhelper/quests/thegrandtree/TheGrandTree.java

Minor modification to text indicating to users that two inventory slots are needed to start Grand tree.

fix: Mention that two free inventory slots are required to start Grandtree quest

---

src/main/java/com/questhelper/quests/clocktower/ClockTower.java

This commit fixes the name of the monk at the end of the quest

Fix wrong name in Clock tower quest

---

src/main/java/com/questhelper/achievementdiaries/desert/DesertMedium.java
src/main/java/com/questhelper/achievementdiaries/morytania/MorytaniaHard.java
src/main/java/com/questhelper/quests/creatureoffenkenstrain/CreatureOfFenkenstrain.java
src/main/java/com/questhelper/quests/legendsquest/LegendsQuest.java

Replaced incorrect usages of `the` with `to` in `CreatureOfFenkenstrain`, `MorytaniaHard`, & `DesertMedium`
Fixed typo in `CreatureofFenkenstrain` - `teleportToFurnance` variable & `furnance` text
Capitalized mention of `Edgeville` & `Ectophial` in `CreatureofFenkenstrain`

Fix some wording & typos

---

src/main/java/com/questhelper/quests/zogreflesheaters/ZogreFleshEaters.java

Currently the Zogre Flesh Eaters guide only mentions a single enemy to defeat (Slash Bash). However as the guide does state, you also have to kill a level 39 zombie.
The Wiki mentions both enemies - https://oldschool.runescape.wiki/w/Zogre_Flesh_Eaters.

add missing enemies to defeat during Zogre Flesh Eaters

---

src/main/java/com/questhelper/quests/kingsransom/KingsRansom.java

During King's Ransom a cast of telekinetic grab (or a lockpick) is required. This correctly indicates you have the necessary runes to cast telekinetic grab, when you do.

Telekinetic Grab requires one air rune

---

src/main/java/com/questhelper/quests/familycrest/FamilyCrest.java

Fixes the missing step in the Family Crest quest
I didn't get a chance to actually test the functionality (during the quest), but I assume existing code works but was just never called
Before
After
Fixes #582

Fix Family Crest missing step

---

src/main/java/com/questhelper/achievementdiaries/falador/FaladorEasy.java

Removed unnecessary `A`'s - moves from `1x A Bucket` to `1x Bucket`
Used the fairly constant precedent from other files

Cleanup Faladory Easy required item wording

---

src/main/java/com/questhelper/achievementdiaries/fremennik/FremennikHard.java

edit: This PR now does the following:
- Gray's out the Spellbook requirement as being in 2 different spellbooks is not possible, and adding the quest requirement is redundant.
- Adds missing quests from `General Requirements` section
- Sets Giant Dwarf status from `COMPLETED` to `IN_PROGRESS` as per the wiki
It's not possible to be in 2 different spellbooks at the same time (not including Spellbook Swap), so the current check will always fail
(I should note this "fail" is only visual, it worked as intended when showing the diary when searching `Show Meet Reqs`)
~~I've taken the approach to checking for only `LUNAR_DIPLOMACY, QuestState.FINISHED`, as the Normal spellbook is always unlocked
Unsure if there's a better approach~~
Before
After

Update General requirements in Fremennik Hard Diary

---

src/main/java/com/questhelper/quests/monkeymadnessi/MonkeyMadnessI.java

References the needed banana's in `Item Requirements`
Used the precedent from `GoblinDiplomacy` and named the new var `bananaReq`
Also fixed a comment typo
Before
After
Fixes #558

Fix missing item recommendation in Monkey Madness I

---

src/main/java/com/questhelper/achievementdiaries/karamja/KaramjaMedium.java

I was doing the Karamja Medium Diary and the axe item requirement disappeared before I completed the two cut a tree requirements.
Added "Cut a Teak Tree" and "Cut a Mahogany Tree" diary steps to Axe item requirement display condition.

Karamja Medium Diary: Added the two cut a tree diary steps to the axe item requirement display conditions

---

src/main/java/com/questhelper/quests/monkeymadnessi/MonkeyMadnessI.java

I noticed you already fixed the spelling last week, right after 2.8.0 release, but since the issue was opened I removed the space in `gree gree` and capitalized `Karamjan`
Fixes #635

Minor Monkey Madness I fixes

---

src/main/java/com/questhelper/quests/deserttreasure/DesertTreasure.java

You do not need to make two trips to the bank like it says! Items can be brought noted.

Update DesertTreasure.java to fix mistake in instructions.

---

src/main/java/com/questhelper/quests/theslugmenace/TheSlugMenace.java

Update quest step description when crafting runes to include the following line: 
"Bring extra essence (~10 extra) as it is possible to accidentally destroy the essence upon creation.". 
The "10 extra" suggestion comes from the original item requirement section, where 5 runes are required, but it is recommended to bring 15 to be safe. The "15 to be safe" may be forgotten by the time that step is reached, so a reminder is helpful. 
Old:
"Right-click each page to turn rune/pure essence into empty runes. Take each empty rune and use it on its respective Runecrafting Altar."
New: 
"Right-click each page to turn rune/pure essence into empty runes. Take each empty rune and use it on its respective Runecrafting Altar. **Bring extra essence (~10 extra) as it is possible to accidentally destroy …

Update TheSlugMenace.java Quest Step Description

---

src/main/java/com/questhelper/achievementdiaries/wilderness/WildernessHard.java

Cleaned up the `addyBar` value to be declared once
Made `barsOrPick` actually have an OR and fixed the name
Fixed Adamant scimitar name
Fixes #648

Fix Wilderness Hard Diary adamantite bar requirements

---

src/main/java/com/questhelper/achievementdiaries/fremennik/FremennikHard.java

Included text to tell the player that this step can only be completed near Relekka (as stated on the wiki)
I actually made this exact mistake myself never remembered to fix it
also capitalized Super
Fixes #650

Add Fremennik Hard diary Super def potion location warning

---

src/main/java/com/questhelper/quests/curseoftheemptylord/CurseOfTheEmptyLord.java

I'm not actually sure the reason why `ItemID.MORYTANIA_LEGS = 5093` was on here, I can't tell if it's an ancient version of the legs before some old diary change or just a non-existant database item
Fixes #643

Fix Curse of the Empty Lord morytania legs list

---

src/main/java/com/questhelper/QuestHelperConfig.java
src/main/java/com/questhelper/overlays/QuestHelperWorldLineOverlay.java

The same should be added for other overlay hints, such as inventory item highlighting. Unfortunately I do not have an OSRS account in a position to test this, so just world lines it is.

Add config to disable world line rendering

---

src/main/java/com/questhelper/achievementdiaries/morytania/MorytaniaHard.java

Watermelon seeds is not visible in the broader item req's, but is visible in the individual task. Just adding to broader item req's.

Update Morytania Hard Diary Req's

---

src/main/java/com/questhelper/quests/thefremennikexiles/TheFremennikExiles.java

Typhor is a standard monster with two attack styles, Magic and Melee. There is nothing different about its attack distribution when it hits half health.

Correct info on Typhor from The Fremennik Exiles

---

src/main/java/com/questhelper/quests/legendsquest/LegendsQuest.java

Correcting a step to specify that the Vanilla Pods are in the south *west* of the Kharazi Jungle, as shown in the image below:
Also adding a full stop to the end of this step.

Fix for a typo in Legends Quest

---

src/main/java/com/questhelper/achievementdiaries/lumbridgeanddraynor/LumbridgeMedium.java

Noticed while playing around with other changes.
before
after

Add PanelDetails for Lumbridge Medium Diary Lumbridge teleport

---

src/main/java/com/questhelper/quests/horrorfromthedeep/HorrorFromTheDeep.java

Each side of the bridge only requires 30 steel nails each.
Was confusing to me after repairing the first side, and the panel told me I required 60 steel nails for the second, even though it showed only 1 plank required. I ended up running to the bank and making another 30 steel nails before coming back.
This pull request makes that consistent with showing just 1 plank, and just 30 steel nails per side of the bridge.

Fix bridge requirements

---

src/main/java/com/questhelper/achievementdiaries/desert/DesertElite.java
src/main/java/com/questhelper/achievementdiaries/fremennik/FremennikElite.java
src/main/java/com/questhelper/achievementdiaries/lumbridgeanddraynor/LumbridgeElite.java
src/main/java/com/questhelper/achievementdiaries/lumbridgeanddraynor/LumbridgeMedium.java
src/main/java/com/questhelper/achievementdiaries/varrock/VarrockEasy.java
src/main/java/com/questhelper/achievementdiaries/varrock/VarrockElite.java

Renames some variables in Diaries that seem out of place compared to the same item(s) variables in other files.
Noticed these while doing `.quantity()` changes and figured they needed their own PR

Rename short form variables in some Diaries

---

src/main/java/com/questhelper/achievementdiaries/morytania/MorytaniaElite.java

Fix backwards requirements in MorytaniaElite.java

---

src/main/java/com/questhelper/QuestHelperConfig.java
src/main/java/com/questhelper/overlays/QuestHelperWidgetOverlay.java

- Add new config option to disable/enable widget highlighting
- Move all such options to a new configuration section, to keep things tidy
Setting disabled/enabled:
New configuration section:

Add config to disable widget hint rendering

---

src/main/java/com/questhelper/quests/mountaindaughter/MountainDaughter.java

Added Oak, Teak, and Mahogany planks as alternatives to satisfy item requirements.
Tested all planks in-game to make sure they were actually able to be used; checked both crossing into the island, and back to the mainland.

Add more planks to Item Requirements

---

src/main/java/com/questhelper/quests/legendsquest/LegendsQuest.java

-remove duplicate ItemRequirements
-remove ItemRequirements that were initialized but weren't being used
-changed how papyrus and charcoal we're being displayed in the Item Requirements Panel and added tool tips based on the wiki
-reordered the sketchWest, sketchMiddle, and sketchEast DialogSteps to match how they happen during the quest
-changed the description for the spinBull QuestStep to say "swing" to match how it appears in-game
-reworded the ItemReward for experience as it incorrectly stated rewards were given by experience lamp. Wording now matches the wiki
-added unlock rewards for wielding the dragon sq shield
-added unlock rewards for charging skills necklace and combat bracelet at Legend's Guild
-last but not least, added the bindingBook ItemRequirement to the Freeing Ungadulu …

Add Binding Book to Item Requirements for Freeing Ungadulu QuestStep

---

src/main/java/com/questhelper/achievementdiaries/kourend/KourendEasy.java

You don't need any Piscarilius favor for the easy diary requirement. I assume it was added because of The Warrens step, but no favor is needed.

remove false pisc favor in easy diary requirement

---

src/main/java/com/questhelper/quests/mourningsendpartii/MourningsEndPartII.java
src/main/java/com/questhelper/quests/regicide/Regicide.java

You can fail at the rope swing while crossing the underground pass. 
The guide as of right now only recommends bringing one rope. 
This commit adds a tooltip informing players to brings extras as they might fail.

Update Regicide.java. Tooltip about bringing extra ropes.

---

src/main/java/com/questhelper/ItemCollections.java
src/main/java/com/questhelper/QuestHelperConfig.java
src/main/java/com/questhelper/achievementdiaries/ardougne/ArdougneElite.java
src/main/java/com/questhelper/achievementdiaries/desert/DesertHard.java
src/main/java/com/questhelper/achievementdiaries/falador/FaladorEasy.java
src/main/java/com/questhelper/achievementdiaries/falador/FaladorElite.java
src/main/java/com/questhelper/achievementdiaries/falador/FaladorHard.java
src/main/java/com/questhelper/achievementdiaries/fremennik/FremennikMedium.java
src/main/java/com/questhelper/achievementdiaries/karamja/KaramjaEasy.java
src/main/java/com/questhelper/achievementdiaries/karamja/KaramjaHard.java
src/main/java/com/questhelper/achievementdiaries/karamja/KaramjaMedium.java
src/main/java/com/questhelper/achievementdiaries/kourend/KourendEasy.java
src/main/java/com/questhelper/achievementdiaries/kourend/KourendElite.java
src/main/java/com/questhelper/achievementdiaries/kourend/KourendHard.java
src/main/java/com/questhelper/achievementdiaries/kourend/KourendMedium.java
src/main/java/com/questhelper/achievementdiaries/lumbridgeanddraynor/LumbridgeElite.java
src/main/java/com/questhelper/achievementdiaries/lumbridgeanddraynor/LumbridgeMedium.java
src/main/java/com/questhelper/achievementdiaries/morytania/MorytaniaMedium.java
src/main/java/com/questhelper/achievementdiaries/varrock/VarrockHard.java
src/main/java/com/questhelper/achievementdiaries/varrock/VarrockMedium.java
src/main/java/com/questhelper/achievementdiaries/westernprovinces/WesternEasy.java
src/main/java/com/questhelper/achievementdiaries/westernprovinces/WesternMedium.java
src/main/java/com/questhelper/quests/belowicemountain/BelowIceMountain.java
src/main/java/com/questhelper/quests/coldwar/ColdWar.java
src/main/java/com/questhelper/quests/priestinperil/PriestInPeril.java
src/main/java/com/questhelper/quests/whatliesbelow/WhatLiesBelow.java

Noticed a problem with overlapping dropdown on the panel from #755. The problem stems from the padding at the end of each option in the dropdown, so there might be a more suitable fix to this.
Before:
After:
Also a bunch of diary skill req adjustments. Previously they _sometimes_ included skill requirements for quests. Which didn't really make sense because in our quest guides they don't require the skills from leading quests.

Couple fixes

---

src/main/java/com/questhelper/quests/trollstronghold/TrollStronghold.java

Probably a copy-paste mistake, the `climbingBootsOr12Coins` requirement was the same as `climbingBoots`, so even if 12 coins were held in the inventory the requirement was shown as unsatisfied.

Fix Troll Stronghold coin requirement

---

src/main/java/com/questhelper/requirements/WidgetModelRequirement.java
src/main/java/com/questhelper/requirements/WidgetPresenceRequirement.java

Yesterday, @LlemonDuck mentioned to me that I can conditionally check whether a Widget is there or not (`null` vs. `Widget` instance) to detect eg. puzzle 'interfaces' being open.
After looking into it this morning I also noticed that there's already a `WidgetModelRequirement`, which does exactly that _except_ that it also checks for a Model ID to be matching, which for the sake of detecting a widget's presence/visibility is likely not needed, so it made me wonder whether it would make sense to add a `WidgetPresenceRequirement`  and have the `WidgetModelRequirement` become a subclass of that.
While this obviously doesn't add groundbreaking new logic, it does provide an easy-to-find Requirement for people new to the project, which does exactly what they would expect it to do, so I figured …

Add WidgetPresenceRequirement

---

src/main/java/com/questhelper/quests/mourningsendparti/MourningsEndPartI.java

The skill requirement for thieving on mourning's end part 1 is actually not boostable. 
I felt so sad that I was baited that I made this PR. 
please reference: https://oldschool.runescape.wiki/w/Mourning%27s_End_Part_I

Fix: Mourning's End Part I Skill Requirement

---

src/main/java/com/questhelper/quests/bigchompybirdhunting/BigChompyBirdHunting.java
src/main/java/com/questhelper/quests/forgettabletale/ForgettableTale.java

Previously the text would have the user use the raw chompy on the NPC, but this would not progress the plugin to the next step correctly. Simply talking to the NPC works great, so I've changed the relevant step to instruct the user to do just that.

Small fix for step text

---

src/main/java/com/questhelper/quests/mourningsendparti/MourningsEndPartI.java

Accidentally forgot to make a new branch since it's just a very minor fix so I'm making a pull request from main.
The Requirement `barrelOfRottenApples` was already there, it was just not used in the right spot. This way, you are not asked to endlessly fill barrels with rotten apples and quest helper knows when you got the filled barrel in your inventory to use on the press.

Mourning's End P1 - Fix not progressing when filling apple barrel.

---

src/main/java/com/questhelper/quests/lairoftarnrazorlor/LairOfTarnRazorlor.java

Typo changed from "Mutatant" to the correction "Mutant"

typo fix - Lair of Tarn Razorlor

---

src/main/java/com/questhelper/quests/entertheabyss/EnterTheAbyss.java

As with #834, the Enter the Abyss miniquest dialogue was changed with the 23/03/2022 Guardians of the Rift update.
This PR fixes some broken dialogue highlighting, as well as updating the talkToAubury step to correctly highlight Aubury.
Regarding the talkToMageInVarrock dialogue steps, all possible dialogue options that will eventually lead the player to progressing the quest to the next step are highlighted. If you would prefer the shortest route to progress the step to be highlighted, then the dialogue steps in lines 138 and 139 can just be deleted.

Update Enter the Abyss to align with new quest version

---

src/main/java/com/questhelper/achievementdiaries/falador/FaladorMedium.java

Items required to build a Scarecrow for the step labelled "Brain not included" added to the helper's item requirements.
Item requirements were listed on the step's specific panel, but not the overall diary's item requirements.
Would resolve #829

Add missing Falador Medium diary item requirements for Scarecrow

---

src/main/java/com/questhelper/quests/landofthegoblins/LandOfTheGoblins.java

Fixes:
- Quest rewards not included in the panel
- Purple dye not listed in the requirements
- Substeps not set up properly
fixes #865

Land of the Goblins fixes

---

src/main/java/com/questhelper/quests/recipefordisaster/RFDGoblins.java

Changed from:
"You can buy one from the general store north of Shilo Village"
To:
"Can be bought from the general store in Shilo Village or the one northwest of Shilo Village"
Someone was confused by the original tooltip and charcoal is available in both

RFDGoblins -expanded on Charcoal tooltip

---

src/main/java/com/questhelper/achievementdiaries/westernprovinces/WesternHard.java

Quest helper requires 1x of each rune while Ape Atoll Teleport calls for 2x each rune. Change corrects the rune requirement.

WesternHard -rune quantity correction

---

src/main/java/com/questhelper/quests/dragonslayerii/CryptPuzzle.java

The widget for the puzzle changed at some point leaving the plugin unable to read the puzzle text. Fixed by updating the ids.

Fix Dragon Slayer 2 bust puzzle

---

src/main/java/com/questhelper/quests/clocktower/ClockTower.java
src/main/java/com/questhelper/quests/deserttreasure/DesertTreasure.java
src/main/java/com/questhelper/quests/recipefordisaster/RFDDwarf.java
src/main/java/com/questhelper/quests/recipefordisaster/RFDFinal.java
src/main/java/com/questhelper/quests/recipefordisaster/RFDSirAmikVarze.java
src/main/java/com/questhelper/quests/thefremennikexiles/TheFremennikExiles.java

Various quests have an Ice Gloves requirement, this fix adds Smiths Gloves(i) as an alternate to Ice gloves. 
This alternate item added to these quests:
-Fremennik Exiles
-Clock Tower
-Desert Treasure
-RFD: Sir Amik Varze
-RFD: Dwarf
-RFD: Final
fixes #863  and beyond

Added Smiths Gloves(i) as alt to Ice Gloves

---

src/main/java/com/questhelper/achievementdiaries/desert/DesertEasy.java
src/main/java/com/questhelper/achievementdiaries/desert/DesertElite.java
src/main/java/com/questhelper/achievementdiaries/desert/DesertHard.java
src/main/java/com/questhelper/achievementdiaries/desert/DesertMedium.java

Pharaoh's Sceptre charge rewards needed updated as they did not correctly reflect the number of charges awarded after completing each diary. This is due to an update in late April 2022 which increased the number of max charges awarded for completing the diary. The fix reflects the updated rewarded charges.

DesertDiary -fix charges reward

---

src/main/java/com/questhelper/quests/hauntedmine/HauntedMine.java

Food added to recommended items. Food is currently not mentioned in either of the req items or rec items, this fix better reflects the wiki guide and lets the user know, before starting the quest, that food is recommended. Requested by a Discord user.

HauntedMine -food added to rec items

---

src/main/java/com/questhelper/quests/rovingelves/RovingElves.java

Games Necklace was added to recommended items as it provides teleports handy to the quest. This was suggested by a user on the Discord.

RovingElves -games necklace added to rec items

---

src/main/java/com/questhelper/quests/insearchofknowledge/InSearchOfKnowledge.java
src/main/java/com/questhelper/quests/mountaindaughter/MountainDaughter.java

Fix makes the staff/pole requirement visible. Tool-tip for staff/pole has been expanded upon. Lastly, information on obtaining the pole has been included in the steps. This has been requested numerous times on the Discord.
Also removed an extra space typo from a quest.

MountainDaughter -pole/staff clarity

---

src/main/java/com/questhelper/achievementdiaries/karamja/KaramjaMedium.java

The `Raw karambwanji, or a small fishing net to catch some` text in item requirements were not correctly highlighted as green if you had a small fishing net in your inventory, as per the text instruction.

Karamja Medium Diary: add small fishing net as alternate item to raw karambwanji

---

src/main/java/com/questhelper/quests/ratcatchers/RatCatchers.java

1. Adds 'kwuarm' , 'vial', 'red spiders' eggs' to required items 
-giving these items to Jack gives you the rat poison, this may be more convenient to the player and less confusing
-the current version would have someone running back to the Clocktower if they didn't have the poison without mentioning the much simpler alternate
2. Moves 'rat poison' to recommended item
-tooltip states that the item can be obtained during the quest
3. Note added that tells you where rat poison could be obtained
-the note informs the user that they could retrieve the rat poison before the quest if they so choose
-tells the user that if they wish to do this the kwuarm, vial, and eggs will not be necessary
4. Added text to the step where you talk with Jack, telling the user to obtain the poison by giving the …

Ratcatchers -poison changes

---

src/main/java/com/questhelper/achievementdiaries/fremennik/FremennikMedium.java

"Partial completion of Olaf's Quest" was not in the general requirements but was in one of the steps. This was leading people to believe that they had all the requirements until reaching this step.
This has been added to the general requirements.

FremMed -addedGenReq

---

src/main/java/com/questhelper/quests/dragonslayerii/DragonSlayerII.java

This fixes a tiny typo where it appears the quest instructs you to *pray missiles when he shouts.*, as opposed to always praying missiles during the whole fight like I think it meant.
Example:

DS2: Add period to end of sentence instructing what to pray against Robert the Strong

---

src/main/java/com/questhelper/QuestHelperConfig.java
src/main/java/com/questhelper/achievementdiaries/fremennik/FremennikMedium.java
src/main/java/com/questhelper/achievementdiaries/kourend/KourendHard.java
src/main/java/com/questhelper/panel/QuestOverviewPanel.java
src/main/java/com/questhelper/quests/beneathcursedsands/BeneathCursedSands.java
src/main/java/com/questhelper/quests/dragonslayerii/DragonSlayerII.java
src/main/java/com/questhelper/quests/icthlarinslittlehelper/IcthlarinsLittleHelper.java
src/main/java/com/questhelper/quests/mourningsendparti/MourningsEndPartI.java
src/main/java/com/questhelper/quests/trollromance/TrollRomance.java
src/main/java/com/questhelper/quests/wanted/Wanted.java
src/main/java/com/questhelper/requirements/player/Boosts.java
src/main/java/com/questhelper/requirements/player/SkillRequirement.java

revamped 'boostable' skill requirements, displaying orange if a boost is in range for the player
Added option in settings to enable spicy stew boosts
fixed rewards not properly displaying 'none' if null
before:
after:
Plus a bunch of other various fixes: #900, #902, #912

Revamped Boostable Skill Requirements and Minor Fixes

---

src/main/java/com/questhelper/quests/darknessofhallowvale/DarknessOfHallowvale.java

Included that you can alternatively use the Protect from Melee prayer to negate all of the damage from Vanstrom Klause.

Add additional details to Darkness of Hallowvale

---

src/main/java/com/questhelper/achievementdiaries/westernprovinces/WesternMedium.java

The player needs to travel to Feldip Hills, not the desert. This PR will fix that typo.

Fix typo in Western med diary

---

src/main/java/com/questhelper/quests/watchtower/Watchtower.java

When entering the cave with a lit light source, there will be a warning message about bringing a tinderbox in case the light source goes out. Because this won't happen during the quest I've added dialog steps to help the player make a decision.

Add dialog step about tinderbox warning

---

src/main/java/com/questhelper/achievementdiaries/lumbridgeanddraynor/LumbridgeHard.java

This is an issue I originally implemented in #698 
When attempting to cleanup `.quantity()` usage, I didn't look at the context of the `LogicType.NOR` that the `earthRune4` &`earthRune10` used, because of this mistake on my part, when both steps that require `earthRune`'s are incomplete, both steps are missing their `earthRune` requirements.
This PR reverts that bug by setting the `quantity()` values where they originally were.

Fix issue in Lumbridge diary when you haven't completed both steps that require `earthRune`'s

---

src/main/java/com/questhelper/quests/shilovillage/ShiloVillage.java
src/main/java/com/questhelper/quests/theslugmenace/TheSlugMenace.java

Issue #1015  Remove lumberyard tele from slug menace tooltip as it was removed from game. Added Ring Of The Elements as a tooltip.

Remove Lumberyard Teleport From Slug Menace

---

src/main/java/com/questhelper/quests/bonevoyage/BoneVoyage.java
src/main/java/com/questhelper/quests/recipefordisaster/RFDSirAmikVarze.java
src/main/java/com/questhelper/quests/thefremennikisles/TheFremennikIsles.java
src/main/java/com/questhelper/quests/thegreatbrainrobbery/TheGreatBrainRobbery.java

<details>
<summary>Fixed TheGreatBrainRobbery NPE</summary>
```
[Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
at client.getVarbitValue(client.java:9184)
at client.getVarbitValue(client.java:58466)
at com.questhelper.quests.thegreatbrainrobbery.TheGreatBrainRobbery.lambda$setupRequirements$0(TheGreatBrainRobbery.java:275)
at com.questhelper.quests.thegreatbrainrobbery.TheGreatBrainRobbery.setupRequirements(TheGreatBrainRobbery.java:276)
at com.questhelper.QuestHelperPlugin.lambda$startUp$0(QuestHelperPlugin.java:318)
at java.base/java.util.HashMap.forEach(HashMap.java:1425)
at com.questhelper.QuestHelperPlugin.lambda$startUp$1(QuestHelperPlugin.java:316)
at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThrea …
```

fix: avoid varbit lookup in quest setup when not logged in

---

src/main/java/com/questhelper/achievementdiaries/wilderness/WildernessElite.java

Fixes issue https://github.com/Zoinkwiz/quest-helper/issues/1041 Wildy Elite doesnt recommend hammere - added hammer to requirements at src/main/java/com/questhelper/achievementdiaries/wilderness/WildernessElite line 284

Fix issue #1041 added hammer requirement

---

src/main/java/com/questhelper/panel/questorders/QuestOrders.java

Mostly for The Garden of Death ordering, but also for placeholder quests.
https://oldschool.runescape.wiki/w/Optimal_quest_guide
https://oldschool.runescape.wiki/w/Optimal_quest_guide/Ironman

Update quest ordering to match wiki

---

src/main/java/com/questhelper/quests/waterfallquest/WaterfallQuest.java

Waterfall quest didn't have a guide to get through the maze, whilst Tree Gnome Village did. I took inspiration from the RatCatchers quest, which had a similar structure. Please let me know if there is anything that needs changing.

Added lines to guide through maze in Waterfall Quest

---

src/main/java/com/questhelper/quests/waterfallquest/WaterfallQuest.java

Latest PR added a new variable and renamed the old one, but never declared the renamed var.
The step is now unused, so this PR removes the old variable to fix the build.

Fixed compilation error in WaterfallQuest script

---

src/main/java/com/questhelper/quests/myarmsbigadventure/MyArmsBigAdventure.java
src/main/java/com/questhelper/requirements/var/VarbitRequirement.java

Fix for issue #1055
The Tai Bwo Favour tracker only recognizes you have the favour requirement if you've checked your status since restarting RuneLite. This hides the quest when it shouldn't if "show meets reqs" is selected, as I imagine people rarely check their favour outside of doing the Karamja diary.

Changing the Tai Bwo favour requirement on My Arm's Big Adventure to be optional

---

src/main/java/com/questhelper/quests/secretsofthenorth/SecretsOfTheNorth.java

Hey,
Love the plugin really useful.
Just noticed Secrets of the North was added. Where it had the 50k exp reward and 40k exp reward as farming experience.
RSWiki reckons it's 50k thieving and 40k hunter https://oldschool.runescape.wiki/w/Secrets_of_the_North

Update skill rewards in SotN

---

src/main/java/com/questhelper/quests/secretsofthenorth/SecretsOfTheNorth.java

Add missing Quest Point reward.
The [wiki article](https://oldschool.runescape.wiki/w/Secrets_of_the_North#Rewards) says the quest gives 2 Quest Points.
Left a comment at https://github.com/Zoinkwiz/quest-helper/pull/1071, but decided to make a PR.
---
I have not compiled the code, but I assume it works.

fix: add quest point rewards for SotN

---

src/main/java/com/questhelper/VisibilityHelper.java
src/main/java/com/questhelper/steps/ObjectStep.java
src/main/java/com/questhelper/steps/QuestStep.java

This change prevents outlines from being used when there is no object with a visible model (the outline renderer will simply not render anything in that scenario). Instead it falls back on using a clickbox highlight so there is a useful highlight visible.

Add visibility check for outline highlights of tile objects

---

src/main/java/com/questhelper/QuestHelperQuest.java
src/main/java/com/questhelper/panel/questorders/QuestOrders.java
src/main/java/com/questhelper/quests/secretsofthenorth/SecretsOfTheNorth.java

Fixes: https://github.com/Zoinkwiz/quest-helper/issues/1080, https://github.com/Zoinkwiz/quest-helper/issues/1117 by matching external quest resources enum: https://github.com/Zoinkwiz/quest-helper/blob/86cd794df5a4d402e8a46aea50c68b545a37808a/src/main/java/com/questhelper/ExternalQuestResources.java#L178
Tested locally:

Rename Secrets of the North to match external quest resources enum

---

README.md
src/main/java/com/questhelper/helpers/quests/monkeymadnessii/MM2Route.java

Next month imgur is [cleaning house](https://help.imgur.com/hc/en-us/articles/14415587638029), which includes deleting an unfortunate amount of anonymously uploaded images.
While I'm unsure if the images used in this repo will be removed, it's very possible, so I went ahead and replaced them now.

Replace imgur links with githubusercontent links

---

src/main/java/com/questhelper/HelperConfig.java
src/main/java/com/questhelper/ItemCollections.java
src/main/java/com/questhelper/QuestBank.java
src/main/java/com/questhelper/QuestHelperConfig.java
src/main/java/com/questhelper/QuestHelperPlugin.java
src/main/java/com/questhelper/QuestHelperQuest.java
src/main/java/com/questhelper/banktab/QuestBankTab.java
src/main/java/com/questhelper/banktab/QuestBankTabInterface.java
src/main/java/com/questhelper/banktab/QuestHelperBankTagService.java
src/main/java/com/questhelper/helpers/mischelpers/herbrun/FarmingHandler.java
src/main/java/com/questhelper/helpers/mischelpers/herbrun/FarmingPatch.java
src/main/java/com/questhelper/helpers/mischelpers/herbrun/FarmingRegion.java
src/main/java/com/questhelper/helpers/mischelpers/herbrun/FarmingWorld.java
src/main/java/com/questhelper/helpers/mischelpers/herbrun/HerbRun.java
src/main/java/com/questhelper/helpers/mischelpers/herbrun/PatchImplementation.java
src/main/java/com/questhelper/helpers/mischelpers/herbrun/PatchPrediction.java
src/main/java/com/questhelper/helpers/mischelpers/herbrun/PatchState.java
src/main/java/com/questhelper/panel/QuestHelperPanel.java
src/main/java/com/questhelper/panel/QuestOverviewPanel.java
src/main/java/com/questhelper/panel/QuestRequirementPanel.java
src/main/java/com/questhelper/questhelpers/QuestHelper.java
src/main/java/com/questhelper/requirements/Requirement.java
src/main/java/com/questhelper/requirements/item/ItemRequirement.java
src/main/java/com/questhelper/requirements/item/ItemRequirements.java
src/main/java/com/questhelper/requirements/runelite/RuneliteRequirement.java
src/main/java/com/questhelper/steps/playermadesteps/RuneliteConfigSetter.java

This current has a few improvements needed:
* Need to have some dropdown selections available within the helper sidebar to let users select things such as which plots to include, and which seeds to recommend
* Preferably I can make better use of the existing timers plugin rather than relying on duplicating things getting messy

Add basic herb run helper

---

src/main/java/com/questhelper/helpers/quests/mourningsendpartii/MourningsEndPartII.java

Added missing alternates to death talisman, cleaned up code a bit with tooltips.
Removed a note that was put as a required item, this note was added to a step description.
I would have liked to only use a single item req, deathTalisman, but deathTalismanHeader remains. It is an important note that should be made aware to the user when checking the initial item req, rather than hidden within a tooltip. I added alts to the header so it wouldn't remain red if you had the alternate items.
closes #1164

#1164 death talisman tooltip & alts

---

src/main/java/com/questhelper/helpers/quests/sleepinggiants/SleepingGiants.java

Sleeping Giants did not recognize Imcando Hammer as an alternate for hammer.
Added Imcando hammer as an alt and included a tooltip that mentions it can be used instead. 
closes #1187

Added alt & tooltip for hammer in Sleeping Giants

---

src/main/java/com/questhelper/helpers/achievementdiaries/wilderness/WildernessElite.java

Subtask panel is missing hammer requirement for smithing.

Add hammer to wildy elite panel

---

src/main/java/com/questhelper/helpers/quests/deathplateau/DeathPlateau.java

The correct past participle of "go" is "gone"

Fix tiny grammatical mistake in Death Plateau

---

src/main/java/com/questhelper/helpers/quests/merlinscrystal/MerlinsCrystal.java

Fixes #425
Note that I **have not tested this** because I don't have any available alts atm, but this _should_ fix WidgetTextRequirement not triggering when the dialogue box shows.
Having a look at Runelite's consts [here](https://github.com/runelite/runelite/blob/f029989a291601a6430465494353d4ce7702adcf/runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java#L220C25-L220C25) I suspect it's because the child ID is 5 when it's supposed to be 6 for the player's dialogue text.

Merlin's Crystal fix Lady of the Lake step

---

src/main/java/com/questhelper/helpers/achievementdiaries/ardougne/ArdougneElite.java
src/main/java/com/questhelper/helpers/achievementdiaries/varrock/VarrockElite.java

Quick glance without processing what I was doing while finishing up Varrock elite ended up with bank search that returned no item, as Rune bar is not an osrs item.
Other Elite diaries and GM quests properly mention this item as Runite bar
I went ahead and ignored the variable and just replaced the user-facing instance, but I can update the variable(s) too if needed

Fix mentions of Runite bars being Rune bars in elite diaries

---

src/main/java/com/questhelper/helpers/achievementdiaries/varrock/VarrockMedium.java

A minor step text change, but useful for players who might not want to shoo away their kitten.

Update Varrock Medium Diary kitten step text

---

src/main/java/com/questhelper/helpers/achievementdiaries/varrock/VarrockHard.java

- Varrock Hard: Fix Smite Altar check
- Change the prompt from "make a spotty cape" to "make a spottier cape"
What it looks with this PR:
https://github.com/Zoinkwiz/quest-helper/assets/962989/1e170007-9b76-4e33-80e3-739997cef7aa

Varrock Hard: Fix Smite prayer & cape typo

---

src/main/java/com/questhelper/helpers/achievementdiaries/varrock/VarrockHard.java

This PR is a bit more questionable, it goes into a lot of effort to ensure the previous step stops immediately as the item is looted, but it feels hacky.
Maybe there's a better solution to this, but it works
https://github.com/Zoinkwiz/quest-helper/assets/962989/7f4364a0-50c3-48a1-ba3e-ecb5551b48e3
https://github.com/Zoinkwiz/quest-helper/assets/962989/9e51662b-5161-41c2-8bf0-840c8b9650b2

Varrock Hard: Invoke Skull Sceptre

---

src/main/java/com/questhelper/helpers/quests/deserttreasure/DesertTreasure.java

Antipoison is mentioned in the big "required items" list, but the player will have banked a few times before coming to this step, so it's good to give the player a gentle reminder

Add antipoison as a suggested/required item for the "Freeing Azzanadra" step

---

src/main/java/com/questhelper/helpers/quests/eadgarsruse/EadgarsRuse.java

After beginning the quest in Taverly, you must go immediately to Tenzing west of Burthorpe.
This PR adds a Games necklace/Burthorpe teleport as a recommended item.

Eadgar's Ruse - Add Burthorpe teleport as recommended item

---

src/main/java/com/questhelper/helpers/quests/contact/Contact.java

What it looks like in the main version:
What it looks like after my fix:
I also snuck in a reward typo fix that was showing the reward as `2x 2x Experience Lamps`

Contact!: Fix the trap path break & reward typo

---

src/main/java/com/questhelper/helpers/quests/deserttreasure/DesertTreasure.java

Replace "picklocks" with "lockpicks" to better match the item name `Lockpick`.

Fix a typo in DesertTreasure.java

---

src/main/java/com/questhelper/helpers/quests/theeyesofglouphrie/TheEyesOfGlouphrie.java

In every case, the NPC ID was `NpcID.BRIMSTAIL_11431` for me, and `NpcID.BRIMSTAIL` was used in every cutscene, however,
there's a chance the NPC ID differs based on your other quest progress so I thought it best to just check for both.
Fixes https://discord.com/channels/772056816242130964/1077652787522969620
<details>
<summary>NPC ID images</summary>
</details>
The world point was too far away from the real position, so it wouldn't light up
<details>
<summary>Image of the highlight failing with coordinates</summary>
</details>

The Eyes of Glouphrie: Fix NPC highlights

---

src/main/java/com/questhelper/helpers/miniquests/daddyshome/DaddysHome.java
src/main/java/com/questhelper/helpers/quests/atailoftwocats/ATailOfTwoCats.java
src/main/java/com/questhelper/helpers/quests/atasteofhope/ATasteOfHope.java
src/main/java/com/questhelper/helpers/quests/cabinfever/CabinFever.java
src/main/java/com/questhelper/helpers/quests/clientofkourend/ClientOfKourend.java
src/main/java/com/questhelper/helpers/quests/clocktower/ClockTower.java
src/main/java/com/questhelper/helpers/quests/contact/Contact.java
src/main/java/com/questhelper/helpers/quests/doricsquest/DoricsQuest.java
src/main/java/com/questhelper/helpers/quests/fairytaleii/FairytaleII.java
src/main/java/com/questhelper/helpers/quests/fightarena/FightArena.java
src/main/java/com/questhelper/helpers/quests/gettingahead/GettingAhead.java
src/main/java/com/questhelper/helpers/quests/hazeelcult/HazeelCult.java
src/main/java/com/questhelper/helpers/quests/lunardiplomacy/LunarDiplomacy.java
src/main/java/com/questhelper/helpers/quests/makinghistory/MakingHistory.java
src/main/java/com/questhelper/helpers/quests/monkeymadnessi/MonkeyMadnessI.java
src/main/java/com/questhelper/helpers/quests/murdermystery/MurderMystery.java
src/main/java/com/questhelper/helpers/quests/olafsquest/OlafsQuest.java
src/main/java/com/questhelper/helpers/quests/onesmallfavour/OneSmallFavour.java
src/main/java/com/questhelper/helpers/quests/sheepherder/SheepHerder.java
src/main/java/com/questhelper/helpers/quests/sheepshearer/SheepShearer.java
src/main/java/com/questhelper/helpers/quests/shieldofarrav/ShieldOfArravBlackArmGang.java
src/main/java/com/questhelper/helpers/quests/shieldofarrav/ShieldOfArravPhoenixGang.java
src/main/java/com/questhelper/helpers/quests/swansong/SwanSong.java
src/main/java/com/questhelper/helpers/quests/thedigsite/TheDigSite.java
src/main/java/com/questhelper/helpers/quests/thefeud/TheFeud.java
src/main/java/com/questhelper/helpers/quests/watchtower/Watchtower.java
src/main/java/com/questhelper/helpers/quests/xmarksthespot/XMarksTheSpot.java

The display text of some of the item rewards in the rewards panel would show the quantity of the reward twice (see image above). This PR removes any quantities that were hardcoded in the names of the item rewards and should now correctly display.

Removed quantities from item reward names

---

src/main/java/com/questhelper/helpers/quests/betweenarock/BetweenARock.java

- Between a Rock...: Highlight mine carts when searching for pages
- Between a Rock...: Highlight Scorpions when searching for the first page
- Between a Rock...: Add highlights to eligible low level rocks
- Between a Rock...: Clarify that you can mine the same rocks over and over again while searching for the third page
<details>
<summary>Various screenshots I took of the new look</summary>
</details>

Between a Rock...: Add more highlights

---

src/main/java/com/questhelper/helpers/quests/undergroundpass/UndergroundPass.java

Bucket and Tinderbox can be obtained from the dwarven camp during the quest when they are needed.
Quest sidebar currently doesn't show this:

Update Underground Pass sidebar item requirements

---

src/main/java/com/questhelper/helpers/quests/olafsquest/OlafsQuest.java

The "Finding treasure" panel now tells the player they will need 10 free inventory spots (for ropes and barrels), and to bring their combat gear.

Olaf's Quest - Added inventory slot requirement

---

src/main/java/com/questhelper/helpers/quests/heroesquest/HeroesQuest.java

<details>
<summary>Add Smiths gloves (i) as an alternative to Ice gloves (+ use `canBeObtainedDuringQuest()`)</summary>
_In the general quest requirements_
_When prompted to travel to Entrana_
</details>
<details>
<summary>Highlight relevant items for the "Make an oily rod" step</summary>
</details>
<details>
<summary>Highlight the relevant items for the "Use the Blamish oil on your rod" step</summary>
</details>
<details>
<summary>Highlight the misc key on the ground after your partner dropped it</summary>
</details>
<details>
<summary>Highlight the misc key in your inventory when prompted to unlock the door</summary>
</details>
<details>
<summary>Highlight the candlestick on the ground</summary>
</details>

Heroes' Quest: Various fixes

---

src/main/java/com/questhelper/helpers/quests/throneofmiscellania/ThroneOfMiscellania.java

<details>
<summary>Fix Astrid archery answer</summary>
_This was correct previously, but has since been changed by Jagex_
</details>
<details>
<summary>Add 1x energy restore item as a recommendation</summary>
</details>

Throne of Miscellania: Various fixes

---

src/main/java/com/questhelper/helpers/quests/familycrest/FamilyCrest.java

- Family Crest: Add teleport hint in the Talk to Caleb step
- Family Crest: Add teleport hint in the Talk to Gem Trader step
- Family Crest: Add teleport hint to the Dwarven Mine
- Family Crest: Add teleport hint to the Witchaven ruin step
- Family Crest: Add teleport hint for smelting the 'perfect' gold bars
- Family Crest: Make use of charged item check for alkharid teleports
- Family Crest: Add "Pull North Lever Again" step to "Avan's piece" category
- Family Crest: Clean up the 'perfect' gold smelting process
- Family Crest: Hint at Varrock tele when heading to Johnathon
- Family Crest: Highlight antipoison in your inventory
Dependent on https://github.com/Zoinkwiz/quest-helper/pull/1268 in its current state, will need a rebase afterwards.
Can also merge that part out if we're not …

Family Crest: Some polish

---

.editorconfig
.github/workflows/gradle.yml

This PR adds a simple "gradle build" workflow that will run on commits pushed to the main branch, and to all future PRs
You can see this in action what this looks like on my fork: https://github.com/pajlada/quest-helper/pull/1
the CI job won't automatically run on this PR since the main branch does not have workflow defined, and this PR comes from a fork
If you want to protect your main branch (which would make sure the CI job has to complete before you can merge in PRs), you can:
1. go [here](https://github.com/zoinkwiz/quest-helper/settings/branch_protection_rules/new)
2. set the "Branch name pattern" to `master`
3. enable "Require status checks to pass before merging"
4. type `gradle` in the text box and selecting the job that shows up. if no job has shown up, you might need to have …

Add GitHub Actions CI

---

src/main/java/com/questhelper/helpers/achievementdiaries/ardougne/ArdougneEasy.java

There's already a warning at the lever, but since this is something newer players do we might as well be a bit extra hand-holdy.
I've re-used the text from the Wilderness Easy diary.
See https://discord.com/channels/772056816242130964/772225322354475059/1152616234022604844 for the original suggestion

Add an extra Wilderness warning in the Ardougne Easy diary

---

src/main/java/com/questhelper/helpers/miniquests/thegeneralsshadow/TheGeneralsShadow.java

When adding in the additional recommended teleport items previously, I forgot to include the Camelot and Skills teleports into the recommended items panel.
Continues from PR #1244

Fix missing General's Shadow recommendations

---

src/main/java/com/questhelper/helpers/quests/landofthegoblins/LandOfTheGoblins.java

<details>
<summary>Add a travel hint dialog step when speaking to Kazgar</summary>
</details>
<details>
<summary>Add skills necklace teleport options</summary>
</details>
<details>
<summary>Add Amulet of Glory as the Draynor Village teleport hint</summary>
</details>
<details>
<summary>fix: Keys to the Crypt step now correctly tracks in the side panel</summary>
It used to show up like this:
Now it shows up like this:
</details>
<details>
<summary>Add Combat Bracelet (Ranging Guild) tele hint to Hemnester catch step</summary>
</details>
I wanted to add a teleport hint to use the Dorgesh-kaan sphere in the last step, but since it's a conditional step & it uses the same "climb down the basement" part as the first step of the quest does, I didn't feel confident enough messing around in there, …

Land of the Goblins: Various fixes

---

src/main/java/com/questhelper/helpers/quests/recipefordisaster/RFDSirAmikVarze.java

<details>
<summary>Add Draynor Village teleport hint</summary>
</details>
<details>
<summary>Add Lumbridge Teleport hint when about to end the quest</summary>
</details>
chore: Run Reformat code on the quest file

RFD - Sir Amik Varze: Minor polish

---

src/main/java/com/questhelper/helpers/quests/olafsquest/OlafsQuest.java

<details>
<summary>Add the "Pick up the dropped key" as a substep to the "Kill skeleton" step</summary>
This means the side menu doesn't flip out when being prompted to loot the key
Before (side menu closed on its own):
After (side menu stays open in the right spot):
</details>
Highlight the barrels in your inventory when prompted to use them on the walkway
chore: Run Reformat code on the quest file

Olaf's Quest: Minor polish

---

src/main/java/com/questhelper/helpers/quests/akingdomdivided/AKingdomDivided.java

This PR mostly just adds teleport hints - there's a lot of teleporting around so there are definitely some better routes to take in some places, but it complicates what to bring since the user needs combat gear / food for certain parts.
<details>
<summary>feat: Add tele to lovakengj hint</summary>
</details>
<details>
<summary>feat: Add teleport hint to kill Judge of Yama</summary>
</details>
<details>
<summary>feat: Add tele hint to wintertodt</summary>
</details>
<details>
<summary>feat: Add another tp hint to Piscarilius</summary>
</details>
<details>
<summary>chore: Change the text tele hint for the crate inspection to a real tele hint</summary>
</details>
<details>
<summary>feat: Recommend bringing 1 antipoison for "The Mysteruous Mage" step</summary>
</details>
<details> …

A Kingdom Divided: Polish

---

src/main/java/com/questhelper/panel/DynamicPaddedGridLayout.java
src/main/java/com/questhelper/panel/QuestHelperPanel.java
src/main/java/com/questhelper/panel/QuestOverviewPanel.java
src/main/java/com/questhelper/panel/QuestStepPanel.java

The panel is based on https://github.com/runelite/runelite/blob/754ea00/runelite-client/src/main/java/net/runelite/client/ui/DynamicGridLayout.java 2023-09-20
These gaps would show up if some requirements were hidden due to the relevant step already being completed.
This happens mostly for achievement diaries
Originally reported [in Discord](https://discord.com/channels/772056816242130964/1151245409658867712)
<details>
<summary>What the old solution looked like with hidden requirements</summary>
With an exaggerated padding/gap:
</details>
<details>
<summary>What it looks like with this PR</summary>
With an exaggerated padding:
</details>

fix: remove double gaps in quest requirements

---

src/main/java/com/questhelper/helpers/quests/swansong/FishMonkfish.java
src/main/java/com/questhelper/helpers/quests/swansong/SwanSong.java

- chore: Reformat SwanSong.java
- 1.1: Add teleport hint
- 1.1: Add "Yes." dialog step to start the quest
- 1.2: Add Draynor Village teleport hint
- 1.2: Add Wise old Man dialog step
- 2.1: Add teleport hint to Piscatoris
- 2: Add "Talk to Franklin again" step to the side panel
- fix: monk fish fishing step requirements not showing
- 5.1: Add teleport hint to Yanille
- 5.2: Add teleport hint step to the crafting guild
- 5.3: Highlight Brown Apron in inventory
- 5.5: Hint that the player should gear up now if they weren't already

Swan Song: Minor polish

---

src/main/java/com/questhelper/ItemWithCharge.java
src/main/java/com/questhelper/helpers/quests/thegreatbrainrobbery/TheGreatBrainRobbery.java
src/main/java/com/questhelper/steps/NpcStep.java
src/main/java/com/questhelper/steps/ObjectStep.java

PR diff without the last commit's reformatting: https://github.com/Zoinkwiz/quest-helper/pull/1287/files/76e62ea3c1b2c94ea6c982e88a85711aaa2a10de
Most notably, this fixes ObjectStep's copy function - it didn't copy teleports before.
NpcStep now also has a copy function
The rest of the quest steps were mostly small teleport additions, recovery fixes (e.g. if you teleport away, it will now guide you back easier),
I also made the ectophial tp recommendation also suggest a Mos le'harmless teleport scroll
You're not allowed to bring a pet under water, so I added a hint in the requirements that you shouldn't bring a pet.
I would use the "no follower" thing but you also can't have a pet in your inventory, so I didn't want to give a false sense of "I'm ok" if you just have a pet in your …

The Great Brain Robbery: Some polish

---

build.gradle

Since RuneLite & plugin hub plugins are now built with Java 11, we can get some niceties by upgrading our source & target compatability.
This gives us access to some nice `.of` functions, and the use of `var` to avoid repeating the type of local variables.

Bump minimum Java version from 8 to 11

---

src/main/java/com/questhelper/ItemCollections.java

Specifically for The Path of Glouphrie, the user should wear a slayer helmet instead of earmuffs since they give more defense - I assume this will be the case for most other scenarios

Prefer Slayer Helmets over Earmuffs, Nose peg, Facemask, and Spiny helmet

---

src/main/java/com/questhelper/helpers/quests/gettingahead/GettingAhead.java

Fixes https://discord.com/channels/772056816242130964/1158253185664811038
<details>
<summary>Before image</summary>
</details>
<details>
<summary>After image</summary>
</details>
I have not tested step-tracking, but this should be good

Getting Ahead: Fix missing sidebar entry

---

src/main/java/com/questhelper/helpers/quests/deserttreasureii/SucellusSteps.java

Notice that the pickaxe is actually on the east, and the pestle and mortar is on the west.
Screenshot has compass with south side up.

Duke Sucellus -- Fix reversed east & west instructions

---

src/main/java/com/questhelper/helpers/quests/fairytalei/FairytaleI.java

fixes #1303 
Treznor's npc id was [apparently updated ](https://oldschool.runescape.wiki/w/Treznor#Changes) in late 2022, and I confirmed the new id 11957 to be accurate on my character (who did already have the quest done, but I don't think it would change).

changed Treznor NPC ID to reflect recent update 

---

src/main/java/com/questhelper/helpers/quests/xmarksthespot/XMarksTheSpot.java

Only the turn-in npc has its ID changed, so I only added the alternate NPC ID there

X Marks the Spot: Add alternate Npc ID for Veos from speedrunning worlds

---

src/main/java/com/questhelper/requirements/player/SkillRequirement.java

Fixes #1273:
Thieving currently has a static max boost of "3", reworking checkRange to be more dynamic.

Re-working checkRange to make take into account thieving boost

---

src/main/java/com/questhelper/helpers/quests/enlightenedjourney/GrandTreeBalloonFlight.java

This path is unlike the others and only costs 3 magic logs instead of 10.

fix: bts grand tree only requires 3 logs

---

build.gradle
src/main/java/com/questhelper/domain/AccountType.java
src/main/java/com/questhelper/helpers/achievementdiaries/ardougne/ArdougneMedium.java
src/main/java/com/questhelper/helpers/achievementdiaries/desert/DesertMedium.java
src/main/java/com/questhelper/helpers/quests/mourningsendpartii/MourningsEndPartII.java
src/main/java/com/questhelper/helpers/quests/recipefordisaster/RFDPiratePete.java
src/main/java/com/questhelper/helpers/quests/thefremennikisles/TheFremennikIsles.java
src/main/java/com/questhelper/util/Utils.java

Adds a `Utils` UtilityClass, with the `getAccountType` function that takes a RuneLite `Client` & returns the `AccountType`.
I implemented the helper function `isAnyIronman` on the `AccountType` since that's how it was mostly used.

fix: Removed deprecated AccountType/getAccountType usages

---

src/main/java/com/questhelper/helpers/quests/hazeelcult/HazeelCult.java
src/main/java/com/questhelper/helpers/quests/secretsofthenorth/SecretsOfTheNorth.java

- Fix typo "Almone" -> "Alomone"
- Fix typo "Clocktower" -> "Clock Tower"
Fixes #1342

Fix some minor typos in the "Hazeel Cult" quest

---

src/main/java/com/questhelper/steps/tools/QuestPerspective.java

- Replace deprecated `getMapAngle` with `getCameraYawTarget`
This is the recommended replacement, and it returns the same values from my testing in a RuneLite shell & when making
sure the minimap arrow points in the right direction
- Replace use of deprecated `RenderOverview` with `WorldMap`
For this change I've tested to make sure the miniimap point & world map point still render as expected

refactor: Remove the last remaining deprecated RuneLite API usages

---

src/main/java/com/questhelper/steps/overlay/DirectionArrow.java

At the default minimap zoom level, this changes nothing.
The following video shows the old & new behaviour - the blinking arrow effect was disabled to show better how it works
https://github.com/Zoinkwiz/quest-helper/assets/962989/5c7e1cc7-bdf5-4a13-8fa1-b57e9b57b608

feat: Support minimap zoom levels when rendering the direction arrow

---

src/main/java/com/questhelper/helpers/quests/heroesquest/HeroesQuest.java

This could technically be baked into the "Talk to Straven" step, but having clear directions at the beginning of a new side panel category is nice imo.
Looks like this:

Heroes' Quest: Add missing sidepanel step for Phoenix Gang members

---

src/main/java/com/questhelper/helpers/achievementdiaries/lumbridgeanddraynor/LumbridgeHard.java

The "Move to the Lumbridge furnace" has been changed to an ObjectStep which just points at the correct furnace
The step coords were wrong, and were outside of the area where it would tell you to actually smelt the diamond amulet.
Alternatively, the step could've been removed entirely but this felt like an easy enough fix.
I also changed the wording of it to say "Furnace" instead of "Smithy"
The 3-step-process of smelting -> stringing -> enchanting were flipped, so it checks the last step first.
Previously it would get stuck on the "Smelt ammy" step since that was always true

Lumbridge & Draynor Hard Diary: Polish Power Amulet step

---

src/main/java/com/questhelper/helpers/achievementdiaries/falador/FaladorMedium.java

- The Mogre step now properly highlights the area on the map, and correctly steps through & highlights the Mogre once it has spawned
- Fix the steps not progressing as expected for the Falador wall grapple step
The coordinates for the wall had changes (or were just wrong from the beginning)
- Change the scarecrow requirement checks to instead ask for the material for a scarecrow, as that's more likely to be what people have.
- Added 47 Farming, 59 Fletching, and 59 Smithing skill requirements for ironmen to grow watermelons & to craft the mithril grapple
I have tested this to the best of my ability on Leagues

Falador Medium Diary: Polish

---

src/main/java/com/questhelper/helpers/miniquests/alfredgrimhandsbarcrawl/AlfredGrimhandsBarcrawl.java

Actual improvements:
- Separate getting started & Drinking step
this allows us to add the card as a sidebar requirement
Refactors:
- Rename "talk to guard" step to include that you get a card there
- Minor refactors/List.of/modernizations
This has a chance to be more modernized, by adding conditional steps everywhere that if you don't have the card on you, you should go and get it, but that's a bigger change & riskier to do without testing this.
On that note: I have not tested this change - all of my characters have already completed this quest
but it looks good in the sidebar!
I could also add it as a requirement to each step - let me know!

Alfred Grimhand's Barcrawl: Polish

---

src/main/java/com/questhelper/helpers/quests/shadowofthestorm/IncantationStep.java
src/main/java/com/questhelper/helpers/quests/shadowofthestorm/ShadowOfTheStorm.java

- Clean up incantation step
- I verified & documented the varbits we use, moving them to proper annotated variables
- I converted the HashMap that held the varbitvalue -> word to an array
- I split up the two early out conditions for the hint update
- I "simplified" the incantation order calculations. This removed our reliance on ArrayUtils for (imo) no loss in code clarity.
- Highlight quest start step (just making sure the "Yes." is blue)
- Highlight carpet ride to Uzer
- There are two times during the quest where, during an optimal-ish run, the player will be taking the carpet ride from outside Shantay Pass to Uzer. We now highlight Uzer for both of those times.
- Add missing step to talk to Denath to the side panel
- The step was being tracked properly, but it just wasn't added to the …

Shadow of the Storm: Minor polish

---

src/main/java/com/questhelper/helpers/achievementdiaries/kourend/KourendMedium.java

The ID was confirmed in leagues & on normal worlds

Kourend & Kebos Medium Diary: Fix Mahogany tree object ID

---

build.gradle
src/main/java/com/questhelper/QuestHelperPlugin.java

This makes Quest Helper work with the Runeltie flatlaf changes (https://github.com/runelite/runelite/issues/17284). There's the opportunity still to improve the aesthetic to look better with the new styling (image qualities, some weird outlining, etc), but from what I can tell it's all thankfully fairly functional.

Fix: Flatlaf Runelite compatability

---

src/main/java/com/questhelper/helpers/achievementdiaries/ardougne/ArdougneHard.java

As shown on the wiki, and confirmed personally just a few mins ago

Ardougne Hard Diary thieving requirement is boostable

---

src/main/java/com/questhelper/util/Utils.java
src/test/java/com/questhelper/util/UtilsTest.java

We previously relied on a ComponentID from RuneLite staying constant, which is not the case.
We now build our own ComponentID based on an Interface ID & a Child ID, and test the function with that
I've also removed our packWidget function since it
1. wasn't used
2. is now implemented in RuneLite if we need it going forward

fix: widget pack/unpack test failing

---

src/main/java/com/questhelper/managers/QuestManager.java

The SwingUtilities usage in adding and removing the sidepanel for quests was unneccesary and resulted in issues for Varbit usage.
fixes #1338

fix:Removed incorrect swing usage when adding quests

---

src/main/java/com/questhelper/helpers/achievementdiaries/kandarin/KandarinMedium.java

Adds a text hint if you're in boostable range of the 70 Agility shortcut in Taverley Dungeon for the Kandarin Medium diary.
closes #1372

feature:Added hint for Tav Dungeon Agility shortcut boost

---

src/main/java/com/questhelper/helpers/achievementdiaries/morytania/MorytaniaHard.java

Uses the correct one now for entering the salve mine.
fixes #1382

bug: Change tunnel entrance used in Mory Hard

---

src/main/java/com/questhelper/questhelpers/BasicQuestHelper.java

Usually a quest doesn't have a decrementing value for its state, however for Witch's House and on Quest Speedrunning worlds it can.
This allows for detection of changing state even on the value going down.
fixes #1221

fix:Allow for decrementing state of quests

---

src/main/java/com/questhelper/helpers/quests/monkeymadnessii/MM2Sabotage.java

fix:Move incorrect safe spot hint in MM2 sabotage

---

src/main/java/com/questhelper/helpers/quests/betweenarock/BetweenARock.java

Problem:
Between A Rock quest has an instruction line that appears to be incorrect and inconsistent with the message in the side panel. 
Solution:
Remove the unexpected word from the string.

Fix quest instruction typo

---

src/main/java/com/questhelper/helpers/achievementdiaries/falador/FaladorMedium.java
src/main/java/com/questhelper/helpers/quests/recipefordisaster/RFDPiratePete.java

Fally medium and RFD Pirate Pete both had their general requirements instantiated in the setupConditions function, which is only called on a quest being loaded up.
This means it wouldn't be initially instantiated for the 'meet reqs' filter, so they'd show incorrectly.

fix:Ensure general reqs are instantiated for meet req check

---

src/main/java/com/questhelper/helpers/quests/defenderofvarrock/DefenderOfVarrock.java
src/main/java/com/questhelper/helpers/quests/heroesquest/HeroesQuest.java

Hopefully should result in less confusion on needing to take one side over the other.
Although the check is for the black arm gang, in reality the check will check for the quest overall, not just one side.
fixes #748

feat:Reduced mentions of SoA to exclude side taken

---

src/main/java/com/questhelper/QuestHelperConfig.java
src/main/java/com/questhelper/QuestHelperPlugin.java
src/main/java/com/questhelper/config/SkillFiltering.java
src/main/java/com/questhelper/managers/QuestManager.java
src/main/java/com/questhelper/panel/QuestHelperPanel.java
src/main/java/com/questhelper/panel/skillfiltering/SkillFilterPanel.java
src/main/java/com/questhelper/panel/skillfiltering/SkillIconLabel.java
src/main/java/com/questhelper/panel/skillfiltering/SkillTabGroup.java
src/test/java/com/questhelper/helpers/quests/pures/OneDefPureTest.java

This is somewhat an inverse implementation of https://github.com/Zoinkwiz/quest-helper/pull/1283, where this would work to filter out quests with skill requirements/rewards. It could still be used for the intent of only showing quests requiring/rewarding X, but it means it should also be useful for various limited accounts as well.

feat:Added filters for quests giving/requiring exp in any skill

---

src/main/java/com/questhelper/panel/QuestOverviewPanel.java
src/main/java/com/questhelper/panel/QuestRequirementPanel.java
src/main/java/com/questhelper/panel/QuestStepPanel.java

This should make it easier to go down a quest chain and see what a bottom req is.
This takes on the work started in https://github.com/Zoinkwiz/quest-helper/pull/291 for issue #265.

feat:Added click to load quest option on quest reqs

---

src/main/java/com/questhelper/helpers/quests/defenderofvarrock/DefenderOfVarrock.java

You can't even start Defender of Varrock without 55 Smithing (I sadly just ran into this personally). Wiki also backs this up.

Fix Defender of Varrock smithing requirement.

---

src/main/java/com/questhelper/helpers/quests/akingdomdivided/AKingdomDivided.java
src/main/java/com/questhelper/steps/DetailedQuestStep.java

All steps are completable with Kharedst's Memoirs, but often Xeric's Talisman is a little faster - suggesting both here.
One thing I would have liked to add is a highlight on which option to take on the Xeric's Talisman - but afaict that's not possible (at least it's not a dialogue step)

feat: Added Xeric's Talisman tele suggestions to A Kingdom Divided

---

src/main/java/com/questhelper/helpers/quests/fairytaleii/FairytaleII.java

This ensures they are initialized when quests that have Fairytale II as a requirement might want to see what's required
Fixes https://discord.com/channels/772056816242130964/1225106185158660186
How to reproduce the bug before this PR:
1. Enable the "Show full quest requirements" option
2. Open a helper that has Fairytale II as a pre-requisite (e.g. Kourend & Kebos Medium Diary)

fix: Initialize Fairytale II requirements in setupRequirements

---

src/main/java/com/questhelper/helpers/mischelpers/herbrun/HerbRun.java
src/test/java/com/questhelper/MockedTest.java
src/test/java/com/questhelper/MockedTestBase.java
src/test/java/com/questhelper/helpers/quests/pures/OneDefPureTest.java
src/test/java/com/questhelper/questhelpers/QuestHelperTest.java

- **chore: Use `configManager` directly where possible, instead of getting it from QuestHelperPlugin**
- **chore: Allow the injector to be used in tests**
- **chore: Mock a bunch of stuff in MockedTest**
- **chore: Add test for ensuring requirements are set up in the setupRequirements function**
The tests will fail until https://github.com/Zoinkwiz/quest-helper/pull/1519 has been merged in

Add a test ensuring requirements from quests are not null

---

src/main/java/com/questhelper/QuestHelperPlugin.java
src/main/java/com/questhelper/managers/QuestBankManager.java

This current implementation makes use of the IN_RAID_PARTY VarPlayer to determine a quest has been reset, as it shouldn't be used in most circumstances of doing speedrunning, but does get set to 0 for the quests I tested.
Ideally we'd identify a var more correlated to  quest speedrunning.

fix: Add bank resetting for Quest Speedrunning worlds

---

src/main/java/com/questhelper/requirements/var/VarbitRequirement.java
src/main/java/com/questhelper/util/Utils.java

Previously, if a varbit failed to read (e.g. if the varbit had been deleted), we didn't handle the exception causing the helper & client to misbehave.
Now, we catch the exception & post a message in chat instructing the user to notify us via the Quest Helper discord.
This uses `client.addChatMessage` which can only be called from the client thread. The varbit check function is only ever called from there, so for this use this is ok.
To test this, open the Kourend medium diary helper & skip the steps until you get to the bluegill step, it should show up like the image below
Questions:
- Is the color for the chat message ok?

feat: Warn on failed varbit reads (without big refactor)

---

src/main/java/com/questhelper/QuestHelperPlugin.java
src/main/java/com/questhelper/helpers/achievementdiaries/ardougne/ArdougneMedium.java
src/main/java/com/questhelper/helpers/achievementdiaries/desert/DesertMedium.java
src/main/java/com/questhelper/helpers/achievementdiaries/falador/FaladorMedium.java
src/main/java/com/questhelper/helpers/achievementdiaries/varrock/VarrockHard.java
src/main/java/com/questhelper/helpers/quests/mourningsendpartii/MourningsEndPartII.java
src/main/java/com/questhelper/helpers/quests/recipefordisaster/RFDPiratePete.java
src/main/java/com/questhelper/helpers/quests/thefremennikisles/TheFremennikIsles.java
src/main/java/com/questhelper/managers/QuestManager.java
src/main/java/com/questhelper/statemanagement/GameStateManager.java
src/main/java/com/questhelper/statemanagement/PlayerStateManager.java
src/test/java/com/questhelper/MockedTest.java

This fixes an issue where the requirements were being built off the client thread & tried to access the account type to make certain decisions. Now those decisions can be made based on the last cached value.
The meaty change takes place in https://github.com/Zoinkwiz/quest-helper/pull/1557/files#diff-6cb742383761b936054e8727d98f95eae56260b27b01e53d3f09e5615f1bf46eR297-R305 where the order & timing of some of the initializations are made.
Some unrelated changes I've made:
1. `GameStateManager` renamed to `PlayerStateManager` (as discussed in #development)
2. `setupRequirements` that iterates over all quest helpers & refreshes their requirements has been moved from `QuestHelperPlugin` to `QuestManager`. This makes it a bit easier to access from places like `PlayerStateManager`
You can test …

feat: store Account Type (e.g. ironman) in PlayerStateManager

---

src/main/java/com/questhelper/QuestHelperPlugin.java
src/main/java/com/questhelper/panel/QuestHelperPanel.java

I've noticed some support tickets coming in regarding quests not being visible, and often the cause is that the user has accidentally, or just forgotten, that they've enabled some skill filter.
This PR aims to make it easier both for users & for support members to identify this by showing how many (if any) skill filters are enabled next to the "Skill filtering" setting

feat: list numbers of active skill filters next to the dropdown

---

src/main/java/com/questhelper/bank/banktab/QuestBankTab.java

Tried wracking my brain for why this was important when I added it, but even the comment doesn't help me lol. Everything 'seems' to work properly without it, and it avoids any potential future issues. I have a hunch it might've been something to do with the quest filtering functionality sometimes getting overrided by a normal bank tab, but I've not seen that happen without it 🤷 .
It'd be great if I could get a second pair of eyes on it just to make sure nothing is out of place.

Remove event name changing in the QuestBankTab

---

src/main/java/com/questhelper/steps/AbstractWidgetHighlight.java
src/main/java/com/questhelper/steps/DetailedQuestStep.java
src/main/java/com/questhelper/steps/QuestStep.java
src/main/java/com/questhelper/steps/SpellWidgetHighlight.java
src/main/java/com/questhelper/steps/WidgetHighlight.java

I went with the OOP approach of making the existing `WidgetHighlights` into an abstract class (now `AbstractWidgetHighlight`), moving the old implementation to `WidgetHighlight`.
`SpellWidgetHighlight` extends `AbstractWidgetHighlight` and adds the `addSpellHighlight` function to quest steps.
Example usage:
```java
castNormalSpellbookSpell = new ObjectStep(this, ObjectID.ANCIENT_GATE_2930, new WorldPoint(2763, 9314, 0), "Cast a charge orb spell on the ancient gate.", normalSpellbook);
castNormalSpellbookSpell.addSpellHighlight("Camelot Teleport");
```
The implementation of `SpellWidgetHighlight` is stateful in its approach to ensure we don't look for the spell more than necessary.
Right now, a spell search only takes place once every time the spellbook is opened. Theoretically, this might …

feat: highlight spell widget based on spell name

---

src/main/java/com/questhelper/managers/QuestManager.java

There was an issue of the quest being counted as loaded in QuestManager, but that not having yet propagated to the panels. This adds a check to wait for them to be ready to be updated.

fix: Only try to setup highlights in sidebar once quest is loaded

---

src/main/java/com/questhelper/playerquests/bikeshedder/BikeShedder.java
src/main/java/com/questhelper/steps/ObjectStep.java

This changes the behaviour of the setting **Display icons on NPC and objects** when prompted to use an item on an object
Setting **on**, both prior & with this PR, when prompted to use something on an NPC
Setting **off**, both prior & with this PR, when prompted to use something on an NPC
Setting **on**, both prior & with this PR when prompted to use an item on an object
Setting **off**, with the changes of this PR when prompted to use an item on an object (**This is the new behaviour**)
Fixes #1502

fix: respect "Display icons on NPC and objects" settings when prompted to use item on object

---

src/main/java/com/questhelper/helpers/quests/thefremennikexiles/TheFremennikExiles.java

Small fix to the buy kegs of beer step, warning the player that she will be unable to trade later in the quest.

Update clarity on Fremenik Exiles

---

src/main/java/com/questhelper/helpers/achievementdiaries/kandarin/KandarinHard.java
src/main/java/com/questhelper/helpers/achievementdiaries/kandarin/KandarinMedium.java

The coin value always showed 1x coins - now it correctly shows 25000 coins, 95000 coins, or 120000 coins depending on which tasks the player has remaining.
This can be tested in-game on a new character by using the following commands
`::setvarp 1179 0` - this will act as if you haven't completed the granite body or house step
`::setvarp 1179 4` - this will act as if you've completed the granite body step
`::setvarp 1179 8` - this will act as if you've completed the house step
`::setvarp 1179 12` - this will act as if you've completed the granite body and house step
when using the above-mentioned commands, the coin value will change (or more exactly, one coin requirement will be
hidden and another will be shown)
Fixes #1605

fix: Kandarin Hard Diary not calculating coin requirement correctly

---

src/main/java/com/questhelper/helpers/achievementdiaries/wilderness/WildernessHard.java

Trivial.
lmk if there is anything else I need to add. It was already part of the total requirements but was never put into the panel.

Fix: Add hammer as requirement for smithing step

---

src/main/java/com/questhelper/helpers/achievementdiaries/kandarin/KandarinElite.java
src/main/java/com/questhelper/helpers/achievementdiaries/kandarin/KandarinHard.java
src/main/java/com/questhelper/helpers/quests/royaltrouble/RoyalTrouble.java

This is due to a report from nightfirecat on the Runelite Discord, of the condition for the quest requirements not being initialized in a certain scenario.
I wasn't able to reproduce it, but this should ensure that it shouldn't be possible at the very least.

Fix broken requirement inits

---

src/main/java/com/questhelper/QuestHelperPlugin.java

Fixes #1638
reproduction steps described in the linked issue

fix: quests not initializing on first load if starting from empty profile

---

src/main/java/com/questhelper/helpers/quests/thepathofglouphrie/ThePathOfGlouphrie.java

The list was manually adding alternatives and missed the dragon hunter crossbow. Rather than appending it manually, I opted to reuse the `ItemCollections.CROSSBOWS`.

Use any crossbow for ThePathOfGlouphrie.

---

src/main/java/com/questhelper/helpers/mischelpers/allneededitems/AllNeededItems.java
src/main/java/com/questhelper/steps/DetailedQuestStep.java

This should ensure the background helper overlay text should only appear where the normal item highlighting does.

fix: Add item already had check for background highlighting

---

src/main/java/com/questhelper/helpers/quests/goblindiplomacy/GoblinDiplomacy.java

The GE/Bank item search only includes item requirements that are part of a requirement in the panel steps. 
If we add the goblin mail as part of the requirements for the step "Prepare goblin mail" then it will show in the GE/bank.

Fix: Goblin Diplomacy Item Reqs for GE/Bank

---

src/main/java/com/questhelper/helpers/achievementdiaries/desert/DesertHard.java
src/main/java/com/questhelper/helpers/achievementdiaries/fremennik/FremennikHard.java
src/main/java/com/questhelper/helpers/achievementdiaries/fremennik/FremennikMedium.java
src/main/java/com/questhelper/helpers/achievementdiaries/karamja/KaramjaElite.java
src/main/java/com/questhelper/helpers/achievementdiaries/karamja/KaramjaMedium.java
src/main/java/com/questhelper/helpers/achievementdiaries/lumbridgeanddraynor/LumbridgeHard.java
src/main/java/com/questhelper/helpers/achievementdiaries/lumbridgeanddraynor/LumbridgeMedium.java
src/main/java/com/questhelper/helpers/achievementdiaries/morytania/MorytaniaHard.java
src/main/java/com/questhelper/helpers/achievementdiaries/wilderness/WildernessElite.java
src/main/java/com/questhelper/helpers/achievementdiaries/wilderness/WildernessMedium.java

https://secure.runescape.com/m=news/project-rebalance-skilling--poll-81-mta-changes?oldschool=1
Achievement Diary requirements were removed from some agility shortcuts. This PR brings the achievement diaries up to date.

Project Rebalance Achievement Diary Agility Shortcut Changes

---

src/main/java/com/questhelper/helpers/quests/whileguthixsleeps/DolmenType.java

As reported multiple times in the Discord.

fix: changed WGS's restore potion to require harralander not snapdragon

---

src/main/java/com/questhelper/helpers/miniquests/hisfaithfulservants/BarrowsHelper.java

This means the route will update correctly upon re-entering the crypts for another run.

fix: Correctly updated KC in barrows helper

---

src/main/java/com/questhelper/helpers/quests/lunardiplomacy/MemoryChallenge.java

I think this is right, looking at what the values stored were for the varbits used for the columns of the memory puzzle. However, ideally we do test this first.

fix: Corrected west->east order in Lunar Diplomacy Memory Puzzle

---

src/main/java/com/questhelper/helpers/achievementdiaries/desert/DesertHard.java

Should be: Increased experience on the Pollnivneach Rooftop Course.
Not Rellekka, as currently stated.
https://oldschool.runescape.wiki/w/Desert_Diary#Hard
"Increased experience on the [Pollnivneach Rooftop Course](https://oldschool.runescape.wiki/w/Pollnivneach_Rooftop_Course)."

Fix: Incorrect Reward in Desert Diary Hard Rewards

---

src/main/java/com/questhelper/helpers/quests/defenderofvarrock/DefenderOfVarrock.java

The plant is southwest of the inn, not south east.

fix: Defender of Varrock small direction issue

---

src/main/java/com/questhelper/helpers/quests/theforsakentower/TheForsakenTower.java

This PR amends the NPC ID for Lady Vulcana Lovakengj. The NPC is a multinpc; currently the quest helper uses the id from A Kingdom Divided (NPC ID 11145), when the NPC ID ought to be 11035.
Can be tested by setting varbit associated with A Kingdom Divided (varbit 12296)
<details>
<summary>View</summary>
Forsaken Tower first quest step  
Forsaken Tower final quest step
A Kingdom Divided status
</details>

fix: forsaken tower lady vulcana npc id

---

src/main/java/com/questhelper/helpers/quests/deathplateau/DeathPlateau.java

Technically you can get lucky with gambling and win without it, but there is too much chance for us to direct a player to not use it.
fixes #1685.

feat: Require premade blurb for Death Plateau

---

src/main/java/com/questhelper/helpers/quests/eadgarsruse/EadgarsRuse.java

This 'might' fix the issue reported in #796, based on the [missing weirdgloop state](https://chisel.weirdgloop.org/varbs/display?varplayer=335). Preferably someone can test this before this is merged.
fixes #796

fix:Add potential fix for state missing in Eadgar's Ruse

---

src/main/java/com/questhelper/helpers/achievementdiaries/karamja/KaramjaHard.java
src/main/java/com/questhelper/helpers/achievementdiaries/karamja/KaramjaMedium.java

There was a change to the Karamja diaries in May 2024:
Access to the underground portion of the Shilo Village mine is now granted upon completion of the Medium Karamja Diary. 
https://oldschool.runescape.wiki/w/Karamja_Diary
I also added that the medium diary reward for bonus xp for redeeming tickets only applies when wearing the Karamja gloves, as stated in the wiki.

Fix: Karamja diary reward changes - Access to Shilo Village Mine

---

src/main/java/com/questhelper/helpers/quests/whileguthixsleeps/HerblorePuzzle.java

The overarching condition already has NOR in it, so by noring inside a NOR'd Condition it was presumably negating itself. I hope this fixes it.
Hopefully we can test this though before merging though.

fix: Fixed Guthix rest checks for WGS

---

src/main/java/com/questhelper/helpers/quests/thegardenofdeath/TheGardenOfDeath.java

Kharedst was incorrectly spelled as Khardest.
Before:
After:

Fix: The Garden of Death Kharedst Typo

---

src/main/java/com/questhelper/helpers/quests/recipefordisaster/RFDAwowogei.java

I have no strong feelings on whether the game's odd grammar is to be followed in the helper, but I looked up "giant snake" on the wiki and it took me to the Royal Trouble snake. So I think this snake should be changed to the appropriate name for Recipe for Disaster.

RFD Awowogei: giant snake -> Big Snake

---

src/main/java/com/questhelper/helpers/quests/thepathofglouphrie/Solution.java
src/test/java/com/questhelper/helpers/quests/thepathofglouphrie/SolutionTest.java

Before the Solution was assuming there'd be two ItemRequirement per double solution, while there are sometimes only one, with a quantity of 2.
This should hopefully mean this scenario is now handled.

Fix double disc bug path of glouphrie

---

src/main/java/com/questhelper/helpers/quests/thedigsite/TheDigSite.java

"Digging Deeper" panel will now include the trowel as required. The trowel is used in this step.
Resolves this issue:  https://github.com/Zoinkwiz/quest-helper/issues/1731

Fix: The Dig Site - Include trowel as required in last step.

---

src/main/java/com/questhelper/helpers/quests/regicide/Regicide.java

The wiki says to add two coal, then additional coal as needed. We are saying to "slowly" add coal, which is ambiguous. Update step to match wiki based on feedback in Discord.

Improve Regicide bomb making step.

---

src/main/java/com/questhelper/collections/ItemCollections.java

I'm not 100% sure if the order matters here - I've ensured it's Catalytic/Elemental Tiara -> Catalytic/Elemental Talisman -> elemental-specific Tiara -> elemental-specific talisman, but I can see a world where we'd prioritize tiara's over talismans. But I haven't checked if the order matters at all
Fixes #1736

fix: include catalytic/elemental tiaras & talismans for accessing rune altars

---

src/main/java/com/questhelper/overlays/QuestHelperTooltipOverlay.java
src/main/java/com/questhelper/steps/DetailedQuestStep.java

This ensures it won't get shifted by other overlay placements.

fix: Set item tooltip overlay to be a tooltip type

---

src/main/java/com/questhelper/config/AssistanceLevel.java
src/main/java/com/questhelper/managers/QuestMenuHandler.java
src/main/java/com/questhelper/panel/AssistLevelPanel.java
src/main/java/com/questhelper/panel/QuestHelperPanel.java
src/main/java/com/questhelper/panel/QuestSelectPanel.java

This PR is intended to make it easier for players to get started with Quest Helper in a customised to desired use way. It adds three tiers of assistance, minimum, medium, and full assistance.
When you first click on a quest after this update is live in the sidebar, you will be prompted to select an assistance level.
When you select one, you will be taken to the normal quest page.
If you hit the cog at the top of the sidebar, it will let you access this page again to adjust the level of assistance you're getting.
Currently this prompt won't occur if you activate the helper via the in-game quest list, or if the quest helper is activated automatically. I think we may want these both captured, but I want to make sure we don't result in more confusion from people say not knowing about the …

Feat add assistance level groupings

---

src/main/java/com/questhelper/helpers/miniquests/barbariantraining/BarbarianTraining.java
src/main/java/com/questhelper/helpers/quests/clocktower/ClockTower.java
src/main/java/com/questhelper/helpers/quests/fairytalei/FairytaleI.java
src/main/java/com/questhelper/helpers/quests/legendsquest/LegendsQuest.java
src/main/java/com/questhelper/helpers/quests/monkeymadnessi/MonkeyMadnessI.java
src/main/java/com/questhelper/helpers/quests/naturespirit/NatureSpirit.java
src/main/java/com/questhelper/helpers/quests/princealirescue/PrinceAliRescue.java
src/main/java/com/questhelper/helpers/quests/shilovillage/ShiloVillage.java
src/main/java/com/questhelper/helpers/quests/taibwowannaitrio/TaiBwoWannaiTrio.java
src/main/java/com/questhelper/helpers/quests/thedigsite/TheDigSite.java
src/main/java/com/questhelper/helpers/quests/thefremenniktrials/TheFremennikTrials.java
src/main/java/com/questhelper/helpers/quests/thegiantdwarf/TheGiantDwarf.java
src/main/java/com/questhelper/helpers/quests/watchtower/Watchtower.java
src/main/java/com/questhelper/playerquests/bikeshedder/BikeShedder.java
src/main/java/com/questhelper/requirements/widget/WidgetTextRequirement.java
src/main/java/com/questhelper/statemanagement/BarbarianTrainingStateTracker.java

In the latest OSRS update, the child IDs for the quest journal https://github.com/runelite/runelite/commit/ed8619a2e1cc2cf7cfdd4331821be70565b996f3#diff-9a4617133d1883cb6a1ea7643bc34df5fe0544576ec7f4149f39352ae6dc4df0R278-R281
This broke all the quest sync checking for:
- Barbarian Training (and its state tracker)
- Clock Tower
- Fairy Tale part 1
- Legend's Quest
- Monkey Madness 1
- Nature Spirit
- Prince Ali Rescue
- Shilo Village
- Tai Bwo Wannai Trio
- The Dig Site
- The Fremennik Trials
- The Giant Dwarf
- Watchtower
To fix this change, I decided to use RuneLite's ComponentID's `DIARY_TITLE` and `DIARY_TEXT` instead of rawdogging the IDs like we did previously. This should help in the future if Jagex changes these, but it does make the diff a bit more difficult to read.
If we don't …

fix: quest journal sync widget ID changes

---

src/main/java/com/questhelper/helpers/achievementdiaries/lumbridgeanddraynor/LumbridgeElite.java
src/main/java/com/questhelper/requirements/var/VarComparisonRequirement.java
src/main/java/com/questhelper/requirements/var/VarType.java

There's a varbit used which holds the total quest points. This makes use of this in the Lumbridge Elite Diary.
This also creates a new Requirement, VarComparisonRequirement, which makes it simple to compare the active values of various varbits and varps.

feat: Create VarComparisonRequirement for Lumbridge Elite quests complete check

---

src/main/java/com/questhelper/helpers/quests/ragandboneman/RagAndBoneManII.java
src/main/java/com/questhelper/helpers/quests/ragandboneman/RagBoneGroups.java
src/main/java/com/questhelper/helpers/quests/ragandboneman/RagBoneState.java

Quest Helper named a non existent item "Ogre Bone"  it was Ogre ribs.
https://oldschool.runescape.wiki/w/Ogre_ribs

Fixed typo in Rag and Bone Man II

---

src/main/java/com/questhelper/helpers/quests/fishingcontest/FishingContest.java
src/main/java/com/questhelper/panel/AssistLevelPanel.java
src/main/java/com/questhelper/panel/JGenerator.java
src/main/java/com/questhelper/panel/QuestHelperPanel.java
src/main/java/com/questhelper/panel/QuestOverviewPanel.java
src/main/java/com/questhelper/panel/QuestRequirementsPanel.java
src/main/java/com/questhelper/panel/QuestSelectPanel.java
src/main/java/com/questhelper/panel/QuestStepPanel.java
src/main/java/com/questhelper/panel/skillfiltering/SkillFilterPanel.java
src/main/java/com/questhelper/panel/skillfiltering/SkillIconButton.java
src/main/java/com/questhelper/panel/skillfiltering/SkillTabGroup.java
src/main/java/com/questhelper/questhelpers/QuestHelper.java
src/main/java/com/questhelper/requirements/item/ItemRequirement.java
src/main/java/com/questhelper/util/Fonts.java

HTML throws as a warning for plugin-hub PRs, so where we can it makes sense to avoid it.
Not 100% sure this has been done right, but seems pretty much right, and everything from what I've scoured looks the same with these changes.

feat: Remove html usage

---

src/main/java/com/questhelper/steps/ObjectStep.java

This is for objects with no outline/visible aspects to highlight, such as gaps, top of stairs, etc.

fix: Fall back to clickbox highlight for objects

---

src/main/java/com/questhelper/panel/QuestHelperPanel.java

If you logged out after selecting a quest and  being prompted to select an assist level, it would try to direct you to a quest panel once you selected the assist level. This would occur even when you then logged out then selected it.
This ensures that the player is instead directed to the usual 'log in to see quests' page.

fix: Improve logout behaviour of the assist panel

---

src/main/java/com/questhelper/helpers/quests/whileguthixsleeps/WhileGuthixSleeps.java

change direction to east of door when waiting for Silif to interact with you
issue:  #https://github.com/Zoinkwiz/quest-helper/issues/1793

Update WhileGuthixSleeps.java modify direction of Silif map step

---

src/main/java/com/questhelper/managers/QuestManager.java
src/main/java/com/questhelper/steps/DetailedQuestStep.java
src/main/java/com/questhelper/steps/QuestStep.java

This removes checks for removing the shortest path, as well as ensures the correct active step is used for disabling.

fix: Remove condition for disabling shortest path

---

src/main/java/com/questhelper/helpers/quests/biohazard/GiveIngredientsToHelpersStep.java
src/main/java/com/questhelper/helpers/quests/deserttreasureii/MemoryPuzzle.java
src/main/java/com/questhelper/helpers/quests/dragonslayerii/CryptPuzzle.java
src/main/java/com/questhelper/helpers/quests/enlightenedjourney/TaverleyBalloonFlight.java
src/main/java/com/questhelper/helpers/quests/lunardiplomacy/MimicChallenge.java
src/main/java/com/questhelper/helpers/quests/lunardiplomacy/NumberChallenge.java
src/main/java/com/questhelper/helpers/quests/recruitmentdrive/LadyTableStep.java
src/main/java/com/questhelper/helpers/quests/theeyesofglouphrie/PuzzleStep.java
src/main/java/com/questhelper/helpers/quests/theforsakentower/AltarPuzzle.java
src/main/java/com/questhelper/helpers/quests/theforsakentower/JugPuzzle.java
src/main/java/com/questhelper/helpers/quests/theforsakentower/PotionPuzzle.java
src/main/java/com/questhelper/helpers/quests/theheartofdarkness/LockedChestPuzzle.java
src/main/java/com/questhelper/helpers/quests/whileguthixsleeps/WeightStep.java
src/main/java/com/questhelper/managers/QuestManager.java
src/main/java/com/questhelper/steps/ConditionalStep.java
src/main/java/com/questhelper/steps/DetailedOwnerStep.java

A few helpers made direct use of the OwnerStep, when they were better suited to make use of the DetailedOwnerStep which implements much of the boilerplate already.
This shifts those steps to DetailedOwnerStep.

refactor: Clean up OwnerStep usage

---

src/main/java/com/questhelper/helpers/quests/ragandboneman/RagBoneState.java

This resolve the issue with the the changes to the quest journal ID.
A potential issue is that this quest was already known to be a bit laggy due to the amount of checks going on, so having it check all rows for all items may make this worse.
An alternative is to wait until I'm sure on the offset of the widgets from the original positions to then keep all the checks to be a single widget check.

fix: Update rag and bone journal check to use DIARY_TEXT

---

src/main/java/com/questhelper/helpers/quests/whileguthixsleeps/WhileGuthixSleeps.java

Indicate to the player they need to weight >= 0kg to enter Movario's lair in WGS.

fix: Add weight requirement to door in WGS text

---

src/main/java/com/questhelper/helpers/quests/thefremennikisles/TheFremennikIsles.java

"Either 8 tin ores, 7 pieces of coal, or 6 mithril ores (depends on your Mining level; level 1 will require tin ore, 2-54 will require coal, and 55-99 require mithril ore). Note: The ores can be noted." from https://oldschool.runescape.wiki/w/The_Fremennik_Isles
Fixes https://github.com/Zoinkwiz/quest-helper/issues/1799

Fix up the level requirements for Fremennick Isles

---

src/main/java/com/questhelper/helpers/quests/trollromance/TrollRomance.java

Added note telling players to check the wiki to setup a safe spot before fighting Arrg. Also added two safe spot world points in the Troll arena which are mentioned in the wiki. Resolves #1003. 
First safe spot:
Second safe spot:

Added safe spot for killing Arrg

---

src/main/java/com/questhelper/helpers/quests/deathontheisle/DeathOnTheIsle.java
src/main/java/com/questhelper/helpers/quests/ethicallyacquiredantiquities/EthicallyAcquiredAntiquities.java
src/main/java/com/questhelper/helpers/quests/theheartofdarkness/LockedChestPuzzle.java
src/main/java/com/questhelper/helpers/quests/theheartofdarkness/TheHeartOfDarkness.java
src/main/java/com/questhelper/panel/QuestStepPanel.java
src/main/java/com/questhelper/steps/NpcStep.java
src/main/java/com/questhelper/steps/ObjectStep.java
src/main/java/com/questhelper/steps/PuzzleWrapperStep.java
src/main/java/com/questhelper/steps/QuestStep.java

This is primarily focusing on implementing the PuzzleWrapperStep to the newest Varlamore quests.
As part of this, I made a few QuestStep functions return said QuestStep. This is intended to make it a bit easier to make things like PuzzleWrapperStep in the future when there's various things needing to be applied to the base QuestStep.
I also needed to fix a bug in the sidebar with how substeps were detected for section highlighting, as it was causing the sidebar to not highlight correctly for substeps of puzzle wrappers.
The parts I've added a puzzle hide to are:
**Heart of Darkness**
- The first floor puzzle is entirely hidden, except a prompt saying to work out the passphrase for the guy.
- The third floor puzzle is entirely hidden, except for a prompt saying to work out who is guilty.
- …

Varlamore Part 2 Quest Cleanup

---

src/main/java/com/questhelper/helpers/quests/ghostsahoy/GhostsAhoy.java

Potential fix to a very minor issue (#1835), showing duplicated quantities for Ecto-tokens required:

Fix: remove duplicated quantities for ecto-tokens

---

src/main/java/com/questhelper/helpers/quests/whileguthixsleeps/WhileGuthixSleeps.java

Reworded the Item requirement of khazard teleport to show as "2x Khazard teleports, Ardougne cloak or Spirit tree (3)"
Instead of
"2x Spirit tree (3), Ardougne cloak or Khazard teleport"
As this might look a bit confusing with the 2x spirit tree and the 3 digit after which is well the number, just looks more easily understandable this way.
Also changed the widget highlight to 44 instead of 47, as 47 is Smoggy. Issue was posted about it in https://github.com/Zoinkwiz/quest-helper/issues/1821

While Guthix Sleeps feedback changes

---

src/main/java/com/questhelper/helpers/quests/coldwar/ColdWar.java

Removed "canBeBoosted" boolean from Hunter requirement as it is incorrect and cannot be boosted.
Fixes #1822

Fix: Cold War hunter requirement

---

src/main/java/com/questhelper/QuestHelperConfig.java
src/main/java/com/questhelper/panel/QuestOverviewPanel.java
src/main/java/com/questhelper/panel/QuestRewardsPanel.java

The default behaviour has not changed, so rewards show for people unless they tick the "Hide quest rewards" config
Once it's ticked and they start a new quest helper, the rewards section is still there, but instead with text explaining that the rewards are hidden due to the config they've enabled.

feat: Add config to hide quest rewards

---

src/main/java/com/questhelper/QuestHelperPlugin.java
src/main/java/com/questhelper/bank/banktab/QuestHelperBankTagService.java
src/main/java/com/questhelper/helpers/quests/ragandboneman/RagAndBoneManI.java
src/main/java/com/questhelper/helpers/quests/ragandboneman/RagAndBoneManII.java
src/main/java/com/questhelper/helpers/quests/thepathofglouphrie/Solution.java
src/main/java/com/questhelper/managers/ItemAndLastUpdated.java
src/main/java/com/questhelper/managers/QuestContainerManager.java
src/main/java/com/questhelper/managers/QuestManager.java
src/main/java/com/questhelper/panel/QuestHelperPanel.java
src/main/java/com/questhelper/panel/QuestOverviewPanel.java
src/main/java/com/questhelper/panel/QuestRequirementsPanel.java
src/main/java/com/questhelper/panel/QuestStepPanel.java
src/main/java/com/questhelper/requirements/item/ContainerState.java
src/main/java/com/questhelper/requirements/item/ContainerStateForRequirement.java
src/main/java/com/questhelper/requirements/item/FollowerItemRequirement.java
src/main/java/com/questhelper/requirements/item/ItemRequirement.java
src/main/java/com/questhelper/requirements/item/ItemRequirements.java
src/main/java/com/questhelper/requirements/item/KeyringRequirement.java
src/main/java/com/questhelper/requirements/item/TrackedContainers.java
src/main/java/com/questhelper/requirements/var/VarComparisonRequirement.java
src/main/java/com/questhelper/steps/DetailedQuestStep.java
src/test/java/com/questhelper/MockedTest.java
src/test/java/com/questhelper/helpers/quests/thecurseofarrav/KeysAndLeversTest.java
src/test/java/com/questhelper/helpers/quests/thepathofglouphrie/SolutionTest.java

This PR intends to improve the efficiency of ItemRequirement checks by including some caching where possible. I've tried to introduce the concept of cached containers (inventory, equipped, bank), which I hope will in the future make it easier for us to include new container concepts such as the rune pouch, POH storage, etc.
I've checked how long the checks take for the sidebar each tick for the Check all items helpers as it's the largest in terms of requirements. Generally across 1000 ticks the new method while cached is 2x faster on average. I've included a 100s sample below with in the cache, with the average for it being:
```
old: 3266746 ns
new: 1408209 ns
```
[newDiff.txt](https://github.com/user-attachments/files/17851199/newDiff.txt) …

ItemRequirement rework

---

src/main/java/com/questhelper/helpers/quests/spiritsoftheelid/SpiritsOfTheElid.java

Made a couple of small changes that I believe make for clearer step descriptions:
- Changed an occurrence of "telegrab" to the spell's name to avoid confusion for players unfamiliar with the term;
- Added missing instructions to use rope on the root to enter the ravine cave.

fix: clarity changes to "Spirits of the Elid" steps

---

src/main/java/com/questhelper/helpers/achievementdiaries/falador/FaladorElite.java
src/main/java/com/questhelper/helpers/quests/holygrail/HolyGrail.java

fix: Taverley typo

---

src/main/java/com/questhelper/QuestHelperPlugin.java

When progressing through a quest, the sidepanel is currently a bit slow at progressing.
This PR tries to avoid this by ensuring the event that triggers sidepanel updates is done at the end of the GameTick event
Before:
https://github.com/user-attachments/assets/f5c77bcc-dbde-475f-a31a-e7880e7650ba
After:
https://github.com/user-attachments/assets/80035f8b-ceb9-45a9-b6dd-c159ee04c9e8
This is probably one of these things that'd be good to get some testing with to ensure it doesn't silently break something

fix: speed up sidepanel responsiveness to quest state changes

---

src/main/java/com/questhelper/helpers/quests/inaidofthemyreque/FillBurghCrate.java
src/main/java/com/questhelper/helpers/quests/inaidofthemyreque/InAidOfTheMyreque.java

fixes #1859 
Proposed fix to the issue in which cooked snail meat items are expected by the helper instead of their raw counterparts.

fix: incorrect expected items for raw snails in "In Aid of the Myreque"

---

src/main/java/com/questhelper/managers/QuestManager.java
src/main/java/com/questhelper/panel/QuestOverviewPanel.java

Previously, when a quest was shut down, we did not reset the `lastStep` variable in `QuestManager`
The `lastStep` variable is used to check if the highlight in the quest helper's side panel should change, and if we don't reset it, then stop & start the same quest, we'll have an active but unhighlighted step.
This PR prevents this.
The first commit consolidates all public `QuestManager` "shut down quest" functions into a single one to ensure I don't have to copy paste the `lastStep` logic elsewhere. It would be good to take an extra look at this to ensure I have missed anything where maybe the background helper should actually remain closed if a quest is shut down in a special way. I tested this to the best of my ability (starting/stopping the "Check all items" quest & other quests, while …

fix: ensure last step is reset on quest shutdown

---

src/main/java/com/questhelper/panel/QuestHelperPanel.java

I don't know of a better way to do this in Swing, but this worked and is barely noticeable and a big improvement over every new quest scrolling to a random spot towards the end of the quest. Not sure what introduced it originally, I tried disabling a bunch of JTextArea behaviours but nothing changed.

fix: scroll to top of quest after the quest is selected

---

src/main/java/com/questhelper/helpers/quests/theheartofdarkness/TheHeartOfDarkness.java

Just a typo I noticed: https://oldschool.runescape.wiki/w/Prince_Itzla_Arkan

Change instances of Prinze to Prince in Heart of Darkness quest

---

src/main/java/com/questhelper/helpers/achievementdiaries/kandarin/KandarinEasy.java

Update kandarin easy achievement diary steps per issue #1087

---

src/main/java/com/questhelper/helpers/quests/kingsransom/KingsRansom.java

https://oldschool.runescape.wiki/w/King%27s_Ransom
It can be obtained before the quest, so should be listed in the required items for the quest and not just the panel step.

fix: Kings Random quest should have animate rock scroll as required

---

src/main/java/com/questhelper/panel/QuestHelperPanel.java

When you had a search for a quest, you would have the assist panel shown it an assist level wasn't selected, but then the search text being set to empty would then cause the quest list panel to be made active, hiding it again.
This ensures that the active state of the assist panel is considered for trying to show the quest list.

fix: Avoid assist level panel being overriden by list on search change

---

src/main/java/com/questhelper/helpers/achievementdiaries/fremennik/FremennikEasy.java

[Completing the quest is not required to do the fremennik diary](https://oldschool.runescape.wiki/w/Fremennik_Diary#Easy). The current requirement made me confused in leagues because completing the giant dwarf requires asgarnia, which would be weird to lock the fremennik diary behind.

fremennik easy diary: correct giant dwarf requirement

---

src/main/java/com/questhelper/collections/TeleportCollections.java
src/main/java/com/questhelper/playerquests/bikeshedder/BikeShedder.java

Add runes, Falador/Ardougne to TeleportCollections.
- Added teleport runes to TeleportCollections
- Use `ItemRequirement` superclass instead of `TeleportItemRequirement` superclass so we can return any child of `ItemRequirement`
- Additionally so we can return `ItemRequirements` when we have a logical OR condition on the requirements (e.g. need either some teleportation item OR prerequisite teleport runes)
Tested in-game, and ran all tests. 
Will follow this up in the next day or two to start migrating the quest requirements to use the `TeleportCollections` class while generating teleport requirements.

Add runes, Falador/Ardougne to TeleportCollections

---

src/main/java/com/questhelper/helpers/quests/thefremennikexiles/TheFremennikExiles.java

- Removed the duplicate sidebar step as noted in [this discord message](https://discord.com/channels/772056816242130964/772056861934354433/1309374830411255838)
- Added the missing sidebar step as noticed by the sidebar step test (and also noted by the above discord message)
- Prioritized the "Pick up letter" part of the first quest section, ensuring the user isn't told to search the sandpit if the letter is on the ground.
- Add a missing dialog step that you might need to click if you cancel out of a conversation at the start of the investigation with Brundt
- Re-implemented the "talk about the shield with Brundt" substeps. I tested all of these during the quest & everything worked as expected, with the fallback step just being "talk to him about everything".
Fixes #1928

The Fremennik Exiles: Minor polish

---

src/main/java/com/questhelper/helpers/quests/royaltrouble/RoyalTrouble.java

- Fixes an issue towards the end of the quest where it would jump back to an old step due to the full cavern not being covered by the ZoneRequirement
- Add a missing dialog step hint for the start of the quest

Royal Trouble: Minor polish

---

src/main/java/com/questhelper/helpers/quests/templeofikov/TempleOfIkov.java

- Fix Lucien's NPC ID for bringStaffToLucien quest step in TempleOfIkov
Noticed Lucien wasn't properly highlighted in this step while using the quest helper. Booted up the developer tools, and noticed the ID wasn't correct, modified to the correct ID and validated in-game the NPC was properly highlighted.

Fix Lucien's NPC ID for bringStaffToLucien quest step in TempleOfIkov

---

src/main/java/com/questhelper/helpers/quests/animalmagnetism/AnimalMagnetism.java

I didn't test this, I assumed it to be `TURAEL_13434` based on the 0 info we had from the original reporter, but `[proc,cluehelper_infobox_target_display].cs2` calls `TURAEL_13618` so I just added all of them.
hub plugin privilege do whatever and it probably works
Fixes #1674

fix: add alternate Turael npcID's to animal magnetism

---

src/main/java/com/questhelper/requirements/player/Boosts.java
src/main/java/com/questhelper/requirements/player/SkillRequirement.java
src/test/java/com/questhelper/requirements/player/SkillRequirementTest.java

Fixes https://discord.com/channels/772056816242130964/772059156710031390/1326472562494013452
This change was split up into 2 commits
1. Add tests
2. Fix the broken test
If you run the tests on the first commit, you'll see the test on line 51 fail, and that's the one @Spaenny described in Discord.
With the second commit applied, which includes a bunch of refactoring & the actual fix, you'll see it and all other tests pass.

fix: ensure SkillRequirement checks doesn't try to stack boosts

---

src/main/java/com/questhelper/helpers/achievementdiaries/kourend/KourendEasy.java
src/main/java/com/questhelper/helpers/achievementdiaries/kourend/KourendElite.java

Added these rewards to the Kourend Diary
**Easy Diary**
- Access to the cooking range in the Hosidius Kitchen, which has a 5% reduced burn rate
- The allotment, flower, and herb patches in Hosidius will never get diseased.
**Elite Diary**
- 10% increased chance of obtaining higher-tier ores in the Blast mine.

Kourend Diary Rewards update

---

.github/workflows/gradle-snapshot.yml
build.gradle

To verify that it works:
```sh
./gradlew dependencyInsight --configuration compileClasspath --dependency net.runelite:client
```
output includes: `net.runelite:client:latest.release -> 1.10.47`
```sh
./gradlew dependencyInsight -Puse.snapshot --configuration compileClasspath --dependency net.runelite:client
```
output includes: `net.runelite:client:latest.integration -> 1.10.48-SNAPSHOT`
From @iProdigy 's work in https://github.com/pajlads/DinkPlugin/pull/640 and https://github.com/pajlads/DinkPlugin/pull/641

chore(ci): also build with RuneLite's snapshot

---

src/main/java/com/questhelper/helpers/achievementdiaries/wilderness/WildernessEasy.java
src/main/java/com/questhelper/helpers/achievementdiaries/wilderness/WildernessElite.java
src/main/java/com/questhelper/helpers/achievementdiaries/wilderness/WildernessHard.java
src/main/java/com/questhelper/helpers/achievementdiaries/wilderness/WildernessMedium.java

Updated Wilderness Diary Rewards for Each Tier

---

src/main/java/com/questhelper/QuestHelperPlugin.java
src/main/java/com/questhelper/bank/banktab/BankTabItem.java
src/main/java/com/questhelper/bank/banktab/PotionStorage.java
src/main/java/com/questhelper/bank/banktab/QuestBankTab.java
src/main/java/com/questhelper/bank/banktab/QuestBankTabInterface.java
src/main/java/com/questhelper/bank/banktab/QuestHelperBankTagService.java
src/main/java/com/questhelper/managers/QuestBankManager.java
src/main/java/com/questhelper/managers/QuestContainerManager.java
src/main/java/com/questhelper/requirements/item/ItemRequirement.java
src/main/java/com/questhelper/requirements/item/ItemRequirements.java
src/main/java/com/questhelper/requirements/item/TrackedContainers.java
src/main/java/com/questhelper/steps/DetailedQuestStep.java

This PR allows for the potion storage to be considered for requirements, as well as for the bank filtering for removing/adding potions from it. The bank work is based on the way the core Bank Tags plugin has done it for Layouts.
In tandem based on this, this also moves the Quest Helper filter for the bank from moving real bank items around to instead just making items into the items we're interested in, now that it's an allowed method due to implementation in the core client. This generally means quite a lot less processing per bank event.
~~Widgets which are still made (section headers and dividers, numbers for quantities needed) will now be trimmed off the size of the bank. From across my accounts the max element in BANK_ITEM_CONTAINER is always 1248, BUT this is a bit sketchy as it's …

Bank improvements

---

src/main/java/com/questhelper/requirements/item/ItemRequirement.java

This might fix an issue where an inventory change occurs on the same tick as the check occurs.
My theory is that the item added event occurs after the inventory check for an ItemRequirement on the same tick.
This has been observed to occur for receiving items in Throne of Miscellania, and for At First Light. Ideally we can test those.

fix: Update container state for ItemRequirement on same tick

---

src/main/java/com/questhelper/helpers/achievementdiaries/fremennik/FremennikMedium.java

Horror from the Deep added to list of general requirements.
Mentioned on Discord,
>  "Suggestion - Completion of Horror from the Deep should be added to general requirements; it's properly listed in the "Waterbirth to Lighthouse" step, but isn't mentioned in the general requirements"
Suggestion is reflected by the information on the wiki.

Added horror from the deep to general req list - Frem. Med. Diary

---

src/main/java/com/questhelper/requirements/npc/DialogRequirement.java

This should ensure things like spaces in usernames work as expected.

fix: Sanitize text for DialogRequirement

---

src/main/java/com/questhelper/helpers/quests/monkeymadnessii/MonkeyMadnessII.java

Noticed in the quest that the item requirement for Translation Book in Starting Off is not in the overall item requirements. Figured to add it.

Add Translation Book to Item Requirements

---

build.gradle
src/main/java/com/questhelper/requirements/conditional/NpcCondition.java
src/main/java/com/questhelper/requirements/item/FollowerItemRequirement.java
src/main/java/com/questhelper/requirements/npc/FollowerRequirement.java
src/main/java/com/questhelper/requirements/npc/NpcInteractingRequirement.java
src/main/java/com/questhelper/requirements/npc/NpcInteractingWithNpcRequirement.java
src/main/java/com/questhelper/requirements/npc/NpcRequirement.java
src/main/java/com/questhelper/runeliteobjects/GlobalFakeObjects.java
src/main/java/com/questhelper/runeliteobjects/extendedruneliteobjects/RuneliteObjectManager.java
src/main/java/com/questhelper/steps/MultiNpcStep.java
src/main/java/com/questhelper/steps/NpcStep.java

This was causing issues with npcs rendering for some reason, so I've removed the npc iteration of NpcRequirement from being used within drawCallback.

fix: Remove npcs() iteration from drawCallback

---

src/main/java/com/questhelper/QuestHelperConfig.java
src/main/java/com/questhelper/bank/banktab/QuestHelperBankTagService.java
src/main/java/com/questhelper/helpers/quests/legendsquest/LegendsQuest.java
src/main/java/com/questhelper/helpers/quests/ragandboneman/RagAndBoneManI.java
src/main/java/com/questhelper/helpers/quests/ragandboneman/RagAndBoneManII.java
src/main/java/com/questhelper/helpers/quests/whileguthixsleeps/WhileGuthixSleeps.java
src/main/java/com/questhelper/managers/QuestContainerManager.java
src/main/java/com/questhelper/panel/QuestRequirementsPanel.java
src/main/java/com/questhelper/playerquests/bikeshedder/BikeShedder.java
src/main/java/com/questhelper/requirements/item/ItemRequirement.java
src/main/java/com/questhelper/requirements/item/ItemRequirements.java
src/main/java/com/questhelper/requirements/item/KeyringRequirement.java
src/main/java/com/questhelper/steps/DetailedQuestStep.java

This generally looks to add a more consistent means of conveying information of which containers an item is in, and starts work towards making ItemRequirements have more defined of a state.
The sidebar now for items will always be white, or whatever you've set your 'partial success' config colour to be, if you have items generally to pass a condition, just not on you. The tooltip will let you know which containers have it.
The overlay does the same now. It may need some reconsideration in terms of default colours and readability.
Currently if you are missing some of an ItemRequirement or ItemRequirements, it will simply indicate 'failed', and not give any hints as to where what bits you do have are.

Feat: container check improvements

---

src/main/java/com/questhelper/helpers/achievementdiaries/morytania/MorytaniaElite.java
src/main/java/com/questhelper/helpers/quests/ragandboneman/RagAndBoneManII.java

Already released as v4.7.6.2
Abyssal demon ID confirmed
Basilisk ID confirmed

fix: update NPC IDs for RuneLite 1.11.2

---

src/main/java/com/questhelper/helpers/quests/throneofmiscellania/ThroneOfMiscellania.java

I added a tooltip to the `logs` required item for the Throne of Miscellania quest, adding context that there are trees available to be chopped on Miscellania.
This tooltip can save users time, and is more consistent with the `flowers` tooltip, which informs users that they can be bought on Miscellania.
N/A

Add tooltip to logs requirement for Throne of Miscellania

---

src/main/java/com/questhelper/helpers/quests/taibwowannaitrio/TaiBwoWannaiTrio.java

The Wiki says that rum with sliced banana will not break if you teleport, and I confirmed this in game during the quest.

Clarify that you can teleport with rum in Tai Bwo Wannai Trio

---

src/main/java/com/questhelper/requirements/item/ItemOnTileConsideringSceneLoadRequirement.java
src/main/java/com/questhelper/requirements/item/ItemOnTileRequirement.java
src/main/java/com/questhelper/requirements/location/TileIsLoadedRequirement.java
src/main/java/com/questhelper/runeliteobjects/extendedruneliteobjects/ExtendedRuneliteObject.java
src/main/java/com/questhelper/steps/DetailedQuestStep.java
src/main/java/com/questhelper/steps/ObjectStep.java
src/main/java/com/questhelper/steps/overlay/DirectionArrow.java
src/main/java/com/questhelper/steps/overlay/WorldLines.java
src/main/java/com/questhelper/steps/tools/QuestPerspective.java

This specifically came up in A Forgettable Tale... where the platforms with chests in the puzzle section exist a few times in the same space.
This meant sometimes the first LocalPoint found was actually the incorrect point. This change is intended to make it so that all LocalPoints can be considered by Steps before actually drawing arrows and highlights.
A note is I feel that the final section of DS2 might possibly be impacted by this, but I can't really predict in what way.

fix: Allow for better handling for copied instances

---

src/main/java/com/questhelper/panel/QuestRequirementsPanel.java

This avoids all the non-item requirements from having info boxes.

fix: Start sidebar info button as invisible

---

src/main/java/com/questhelper/steps/ConditionalStep.java

This should ensure we only try highlighting wrapper steps like ConditionalStep and its children if is is active.
This is important for some quests like Another Slice of H.A.M, where the same steps are used for different ConditionalSteps, but we only want the active section to highlight in the sidebar.

fix: Check ConditionalStep for if started for highlighting

---

src/main/java/com/questhelper/overlays/QuestHelperWidgetOverlay.java
src/main/java/com/questhelper/steps/ConditionalStep.java
src/main/java/com/questhelper/steps/DetailedOwnerStep.java
src/main/java/com/questhelper/steps/DetailedQuestStep.java
src/main/java/com/questhelper/steps/QuestStep.java
src/main/java/com/questhelper/steps/tools/QuestPerspective.java

This should ensure that a parent step with requirements like DetailedOwnerStep and ConditionalStep have access to item highlighting. Also simplifies the divide between teleport item highlighting and normal item highlighting.

fix: Allow item highlights to work for ConditionalStep

---

src/main/java/com/questhelper/helpers/achievementdiaries/westernprovinces/WesternMedium.java
src/main/java/com/questhelper/helpers/miniquests/alfredgrimhandsbarcrawl/AlfredGrimhandsBarcrawl.java
src/main/java/com/questhelper/helpers/quests/monkeymadnessi/MonkeyMadnessI.java
src/main/java/com/questhelper/helpers/quests/theeyesofglouphrie/TheEyesOfGlouphrie.java
src/main/java/com/questhelper/helpers/quests/thegrandtree/TheGrandTree.java
src/main/java/com/questhelper/helpers/quests/thepathofglouphrie/sections/InformKingBolren.java
src/main/java/com/questhelper/util/QHObjectID.java

Quite a lot of object IDs to update - I _believe_ I caught them all.
Not all of these changes were required for things to update, but that's only because only one of the ladders actually broke.
Ladders at all floors have updated and would have failed to highlight.
I found the ladders by grepping for the coords `2466, 3495`, and updating the IDs depending on the plane.
Bottom floor:
Floor 1:
Floor 2:
Top floor:
Released as part of https://github.com/Zoinkwiz/quest-helper/compare/release/v4.7.6.3 in https://github.com/runelite/plugin-hub/pull/7797

Fix object IDs for Runelite v1.11.6

---

src/main/java/com/questhelper/QuestHelperPlugin.java
src/main/java/com/questhelper/helpers/quests/theeyesofglouphrie/PuzzleStep.java
src/main/java/com/questhelper/managers/QuestOverlayManager.java
src/main/java/com/questhelper/overlays/QuestHelperOverlay.java
src/main/java/com/questhelper/steps/PuzzleWrapperStep.java
src/main/java/com/questhelper/steps/QuestStep.java
src/main/java/com/questhelper/steps/WidgetStep.java

This PR looks at the render order of the overlay for the puzzle with a new method in QuestStep, updating some details to gamevals, and a few small improvements to make it work a bit better, namely ensuring it considers all viable insertion discs properly when prompting the player to click a new disc to add to their hand image.

Fix: improvements to Eyes of Glouphrie puzzle

---

src/main/java/com/questhelper/steps/ConditionalStep.java

Sometimes we want to use a ConditionalStep as a sidebar step, but also sometimes in another spot just a normal step which is a step within a ConditionalStep.
This usually results in the sidebar highlighting both, as the step can be active in a depth search, as well as as the higher conditionalstep being active.
This allows for full depth searching to not be done for sidebar consideration for specific conditional steps.

feat: Added sidebar highlight depth toggle for ConditionalStep

---

src/main/java/com/questhelper/helpers/achievementdiaries/desert/DesertEasy.java
src/main/java/com/questhelper/helpers/quests/coldwar/ColdWar.java

The primary goal of these changes is to ensure these quests do not appear when filtering out attack and strength.
Cold War provides 40-120 attack experience depending on how many icelords you are required to kill. I wasn't sure what amount to put, so I did the minimum.
Desert Easy Diary provides 20 strength experience when opening the sarcophagus.
Fixes #1829

fix: Added combat xp from Cold War and Desert Easy Diary required actions as rewards

---

src/main/java/com/questhelper/helpers/mischelpers/farmruns/TreeRun.java

technically a bit of a code stink - in a normal quest helper run, initializeRequirements gets called by the QuestManager when the user logs in or they change their profile.
We don't call that for this unit test, but it's not a problem for most unit tests because they defensively call initializeRequirements in more places.

fix: tree helper unit test

---

src/main/java/com/questhelper/helpers/quests/makingfriendswithmyarm/MakingFriendsWithMyArm.java

This removes a space to fix text alignment in the general requirements section of the Making Friends with My Arm quest.

Fix: Minor edit for text alignment in Making Friends with My Arm

---

src/main/java/com/questhelper/helpers/quests/thefremenniktrials/TheFremennikTrials.java

Changes a dialogue option with Brundt during 'The Fremennik Trials' quest when doing Sigmunds task from  `Talk about anything else.` to `Ask about anything else.`
https://github.com/Zoinkwiz/quest-helper/issues/2086#issuecomment-2915527580

Changes Brundt dialog options from talk to ask in The Fremennik Trials quest

---

src/main/java/com/questhelper/helpers/quests/makinghistory/MakingHistory.java

Ardougne capes have been added as alternates to teleport tabs, if following the optimal quest route players should already have their unlimited ardy monastery tele cape
https://github.com/Zoinkwiz/quest-helper/issues/2117

Adds Ardougne capes to alternate Ardy teleports in the Making History Quest

---

src/main/java/com/questhelper/helpers/quests/deathontheisle/DeathOnTheIsle.java

The first step under the final "The show must go on" section had the word "theatre" an extra time. This change removes the redundant use of the word.
The text for this step could be more descriptive by mentioning the agility rocks to the south that have to be climbed first. It looks like there's code to do this but it wasn't functional when I went through the quest.

Fix typo in Death on the Isle

---

src/main/java/com/questhelper/bank/banktab/BankTabItem.java
src/main/java/com/questhelper/bank/banktab/QuestBankTab.java
src/main/java/com/questhelper/steps/tools/QuestPerspective.java

This means in the quest bank, in addition to all the bank items in sections needed being listed, there will be an additional section for all the remaining items. This is mainly useful for the Check all items helper, as it lets you see the items you don't need for any remaining content. For other quests and helpers it's still useful for when you want to grab an additional item which isn't listed as part of the helper sections.

feat: Reimplemented remaining items section in quest bank

---

src/main/java/com/questhelper/helpers/quests/olafsquest/OlafsQuest.java

- Volf's last name was incorrectly listed as "Hradson" but it is ["Olafson"](https://oldschool.runescape.wiki/w/Volf_Olafson)
- Added NPC location text to the Ingrid and Volf steps

Fix a name and add NPC location detail in Olaf's Quest

---

src/main/java/com/questhelper/helpers/achievementdiaries/morytania/MorytaniaEasy.java
src/main/java/com/questhelper/helpers/achievementdiaries/morytania/MorytaniaElite.java
src/main/java/com/questhelper/helpers/achievementdiaries/morytania/MorytaniaHard.java
src/main/java/com/questhelper/helpers/achievementdiaries/morytania/MorytaniaMedium.java

This pull request adds in boost information for every individual step of the achievement diary and includes boost information for the general requirements as well.
Relates to: #2142

fix: add missing boost information for Morytania diaries

---

src/main/java/com/questhelper/helpers/achievementdiaries/lumbridgeanddraynor/LumbridgeEasy.java
src/main/java/com/questhelper/helpers/achievementdiaries/lumbridgeanddraynor/LumbridgeElite.java
src/main/java/com/questhelper/helpers/achievementdiaries/lumbridgeanddraynor/LumbridgeHard.java
src/main/java/com/questhelper/helpers/achievementdiaries/lumbridgeanddraynor/LumbridgeMedium.java

This pull request adds in boost information for every individual step of the achievement diary and includes boost information for the general requirements as well.
Relates to: #2142

fix: add missing boost information for Lumbridge diaries

---

src/main/java/com/questhelper/helpers/achievementdiaries/varrock/VarrockEasy.java
src/main/java/com/questhelper/helpers/achievementdiaries/varrock/VarrockElite.java
src/main/java/com/questhelper/helpers/achievementdiaries/varrock/VarrockHard.java
src/main/java/com/questhelper/helpers/achievementdiaries/varrock/VarrockMedium.java

This pull request adds in boost information for every individual step of the achievement diary and includes boost information for the general requirements as well.
Relates to: #2142

fix: add missing boost information for Varrock diaries

---

src/main/java/com/questhelper/helpers/achievementdiaries/westernprovinces/WesternEasy.java
src/main/java/com/questhelper/helpers/achievementdiaries/westernprovinces/WesternElite.java
src/main/java/com/questhelper/helpers/achievementdiaries/westernprovinces/WesternHard.java
src/main/java/com/questhelper/helpers/achievementdiaries/westernprovinces/WesternMedium.java

This pull request adds in boost information for every individual step of the achievement diary and includes boost information for the general requirements as well.
Relates to: #2142

fix: add missing boost information for Western Provinces diaries

---

src/main/java/com/questhelper/helpers/quests/thelosttribe/TheLostTribe.java

- Add stair highlight during The Lost tribe quest #2118
- Swapped the ObjectID of goUpToF1 to the correct one so that it highlights properly on the given step.
- Swapped the ObjectId of goDownFromF2 to the correct one so that it highlights properly on the given step.

fix: highlights for the Lost Tribe quest

---

src/main/java/com/questhelper/QuestHelperConfig.java
src/main/java/com/questhelper/QuestHelperPlugin.java
src/main/java/com/questhelper/helpers/mischelpers/farmruns/TreeRun.java
src/main/java/com/questhelper/panel/PanelDetails.java
src/main/java/com/questhelper/panel/QuestOverviewPanel.java
src/main/java/com/questhelper/panel/QuestStepPanel.java
src/main/java/com/questhelper/questhelpers/BasicQuestHelper.java
src/main/java/com/questhelper/questhelpers/ComplexStateQuestHelper.java
src/main/java/com/questhelper/questhelpers/QuestHelper.java
src/main/java/com/questhelper/steps/ConditionalStep.java
src/main/java/com/questhelper/steps/QuestStep.java
src/main/java/com/questhelper/steps/ReorderableConditionalStep.java

This PR adds the ability for specific helpers to have reorganizable sidebars. This doesn't usually make sense for normal quests, but can be quite nice for repeatable content where players have ordering preferences like Farm Runs.
The current implementation allows for IDs to be attached to quest steps, and to side panel sections. The side panel by default is in the order of declaration as normal, but if you use a grip on a sidebar element to drag it up or down, it will save the new order by ID to the config.
The ConditionalStep current step check now will, if ids are specified, find the passing step which has the earliest index in the ordered list. This means it will for these helpers have to check all steps which is less efficient then the normal first-pass is used, but works especially …

feat: Sidebar reordering

---

src/main/java/com/questhelper/helpers/quests/thecurseofarrav/MetalDoorSolver.java

Original bug report by Streetlight and Gramps here: https://discord.com/channels/772056816242130964/1397581739823468595/1397581739823468595
Debugging with @coopermor here: https://discord.com/channels/772056816242130964/772059156710031390/1398768936522223676
I had hardcoded the place where I read the password from. This now uses the interfaceid gameval, which should be more correct.

fix(Curse of Arrav): metal door solver

---

src/main/java/com/questhelper/helpers/quests/deserttreasureii/VardorvisSteps.java

vardorvis section doesn't tell you to get food until half way into the section and this is kinda annoying, thought adding a reminder to the start of the section where most people gear up would be better

Add Food recommendation to Vardorvis section of DT2

---

src/main/java/com/questhelper/collections/ItemCollections.java

Only tested in the "Scrambled!" quest, but unless Jagex spaghetti has taken over it should work everywhere where the
mainhand version works.

fix: add Amy's saw (offhand) as a possible Saw

---

src/main/java/com/questhelper/helpers/quests/cooksassistant/CooksAssistant.java
src/main/java/com/questhelper/steps/widget/WidgetHighlight.java

Same idea as the previous polishes, some refactor commits first, and then the actual meaty updates (if any)
I believe I cleaned up this fairly recently so it shouldn't need many changes
What's actually changed:
Some highlights
fixed cook NPC ID (it was just NpcID.COOK). Confirmed in normal f2p worlds & speedrun worlds
changed the order to egg -> mill -> milk to match speedrun strategies
changed which cow to milk to the one north of lumbridge instead

polish: Cook's Assistant

---

src/main/java/com/questhelper/QuestHelperPlugin.java
src/main/java/com/questhelper/managers/QuestManager.java
src/main/java/com/questhelper/panel/QuestHelperPanel.java
src/main/java/com/questhelper/questhelpers/QuestHelper.java

It's awkwardly placed underneath the search bar to ensure it's always visible without having to scroll up in the current quest.
I didn't bother hiding it when no quest is enabled, since it's only a dev mode thing.

feat: add a quest reload button in developer mode

---

src/main/java/com/questhelper/helpers/miniquests/barbariantraining/BarbarianTraining.java

Addresses the final point on #1907 where combat gear, and an anti-dragon shield are required to fight a level 304 Mithril dragon.

polish: Barbarian training mithril dragon requirements

---

src/main/java/com/questhelper/QuestHelperConfig.java
src/main/java/com/questhelper/QuestHelperPlugin.java

essentially just saves me from typing ::questhelperdebug enable every time i restart the client

feat: add option to always show debug overlay in developer mode

---

src/main/java/com/questhelper/helpers/quests/shadowsofcustodia/ShadowsOfCustodia.java

Protect from Melee does not prevent the strange creatures from inflicting the Bleed effect. I tested this with prayers up before talking to Antos and still got affected. This does not matter for most players, but low levels may need to heal.

Shadows of Custodia: Change "all damage" to "most"

---

src/main/java/com/questhelper/helpers/quests/elementalworkshopii/ElementalWorkshopII.java

I’ve run into this step several times and ended up circling the catwalk for crates I already cleared.
This change emphasizes the STAIRS instruction in ALL CAPS to make the next step more obvious.

polish: improve cog search step for Elemental Workshop II

---

src/main/java/com/questhelper/requirements/widget/WidgetTextRequirement.java

This makes it slightly more clear what we're trying to check for in quest helpers

feat(WidgetTextRequirement): add static helper for message box checks

---

src/main/java/com/questhelper/helpers/quests/demonslayer/DemonSlayer.java

When Gypsy Aris was removed in 40b0cbc549c151be678e891911b61c9fd5e24c21 the alternate NPC was redundant.

Demon Slayer: Remove alternate NPC

---

src/main/java/com/questhelper/helpers/quests/deathplateau/DeathPlateau.java

Clarified the `goNorth` `DetailedQuestStep` text to specify going north into Tenzing’s backyard and passing through the stile

polish: Death Plateau

---

src/main/java/com/questhelper/helpers/quests/witchshouse/WitchsHouse.java
src/test/java/com/questhelper/questhelpers/QuestHelperTest.java

Adds an optional step (the user can opt out by checking the checkpoint section) to read the diary, ensuring the middle door is never locked if the witch throws the player out
Makes the texts a bit more fool proof in case jagex changes the locked/unlocked state of the shed door

polish: Witch's House
