- build.gradle
- src/main/java/com/questhelper/ItemCollections.java
- src/main/java/com/questhelper/quests/undergroundpass/UndergroundPass.java
I'm back, with the UndergroundPass guide completed.
For the doll-imbuing portion of the quest, I had to rely on some varbit stuff, so I stuck a todo on each to confirm that it's the right varbit.
I also bumped the version number on the runelite dependency to match the current stable release, as of writing this.
> Add Underground Pass guide, and bump runelite version to 1.6.26.1

- src/main/java/com/questhelper/quests/coldwar/ColdWar.java
- src/main/java/com/questhelper/quests/coldwar/PenguinEmote.java
- src/main/java/com/questhelper/steps/WidgetStep.java
I'm back again with another quest guide, this time for Cold War!
This quest seemed to update the varbit at nearly every opportunity, so it should be quite easy for the plugin to land on the right step. :)
> Add Cold War

- src/main/java/com/questhelper/quests/princealirescue/PrinceAliRescue.java
fixes #9 
This helps with automatic detection of whether you've handed in your key mould or not, as well as providing a prompt to re-sync in case the user logs in/out.
> Improved Prince Ali Rescue state detection

- src/main/java/com/questhelper/quests/dragonslayer/DragonSlayer.java
fixes #10 
- Also fixes a few co-ordinate issues for DS
> Added blocking step for Lozar's Map to allow blocking steps to work

- src/main/java/com/questhelper/quests/theyesofglouphrie/TheEyesOfGlouphrie.java
Fixed highlight dialogue EyesOfGlouphrie 3rd dialogue when starting quest
> Eyes of Glouphrie highlight

- src/main/java/com/questhelper/quests/daddyshome/DaddysHome.java
Fixed the required items and added 3x varrock teleports and 1x lumberyard teleport to recommended items
> Recommended items and required items fix for Daddys home

- src/main/java/com/questhelper/quests/ghostsahoy/GhostsAhoy.java
Fixed the starting dialogue of ghost ahoy
> Ghost ahoy start of quest dialogue was wrong

- src/main/java/com/questhelper/quests/clientofkourend/ClientOfKourend.java
Updated the coords for Leenz. Wrong coordinates on X-axis.
> Updated coordinate on Leenz

- src/main/java/com/questhelper/quests/swansong/SwanSong.java
Swansong Franklin Hammer added
"Franklin will give you one" setTip
> Swansong Franklin Hammer

- src/main/java/com/questhelper/ItemCollections.java
Added these teleport jewellery types
Games necklace
Ring of dueling
Burning amulet
Necklace of passage
Ring of wealth
Combat bracelet
Amulet of glory
Digsite pendant
> ItemCollections added teleport jewellery

- src/main/java/com/questhelper/quests/thefremennikisles/TheFremennikIsles.java
Add collectedKeepa to the conditions for collecting from Flosi and talking to Gjuki.
Should fix #43 but needs testing.
> Fix checks for collecting beard tax from Keepa and Flosi

- src/main/java/com/questhelper/quests/holygrail/HolyGrail.java
Ran through quest on 2 separate accounts, worked on both.
> Added Holy Grail Quest

- src/main/java/com/questhelper/quests/tribaltotem/CombinationLockStep.java
- src/main/java/com/questhelper/quests/tribaltotem/PuzzleStep.java
- src/main/java/com/questhelper/quests/tribaltotem/TribalTotem.java
I should probably rename CombinationLockStep to PuzzleStep but the rest should be good. I also need to see if checkstyle is good. Just opening the PR for now (:
> Tribal totem

- src/main/java/com/questhelper/ItemCollections.java
Added all logs that are able to be firemaked for quest reqs like "any log" if its needed for fire
> Logs for fires ItemCollections

- src/main/java/com/questhelper/quests/thequeenofthieves/TheQueenOfThieves.java
Add The Queen of Thieves quest to the plugin.
> Add Queen of Thieves

- src/main/java/com/questhelper/quests/demonslayer/IncantationStep.java
- src/main/java/com/questhelper/steps/ConditionalStep.java
- src/main/java/com/questhelper/steps/QuestStep.java
- src/main/java/com/questhelper/steps/choice/DialogChoiceSteps.java
Requires this PR before it works https://github.com/Zoinkwiz/quest-helper/pull/79
> Demon slayer - hightlight incantation

- src/main/java/com/questhelper/quests/merlinscrystal/MerlinsCrystal.java
> Fixed combat gear in wrong panel for Merlins Crystal

- src/main/java/com/questhelper/quests/murdermystery/MurderMystery.java
> Fixed small murder mystery bug

- src/main/java/com/questhelper/quests/thegiantdwarf/TheGiantDwarf.java
Currently only gives the option to join the opal company. I'm not sure what would be a good way to track which company tasks need to done, have been done or have been completed.
> Add The Giant Dwarf

- src/main/java/com/questhelper/quests/gertrudescat/GertrudesCat.java
> Fixed a dumb mistake in gertrudes cat

- src/main/java/com/questhelper/quests/fightarena/FightArena.java
> Add quest Fight Arena

- src/main/java/com/questhelper/quests/monkeymadnessii/MonkeyMadnessII.java
Kob's dialog was missing incorrect, Keef's was missing.
> Corrected Kob/Keef dialog steps in MM2

- src/main/java/com/questhelper/quests/betweenarock/BetweenARock.java
| Before | After |
| --- | --- |
| ![between-a-rock-before](https://user-images.githubusercontent.com/11782/102423038-013ec280-4000-11eb-95c2-09a8df92b744.png) | ![between-a-rock-after](https://user-images.githubusercontent.com/11782/102423044-0439b300-4000-11eb-94e8-779b1a7cf9de.png) |
> Fix Between a rock's step requirements and improve dialog steps

- src/main/java/com/questhelper/quests/familypest/FamilyPest.java
Let me know if anything needs to be changed :)
> Added Family Pest miniquest.

- src/main/java/com/questhelper/quests/deathplateau/DeathPlateau.java
Adds #107.
It's mostly done, but...
I'm not sure if you need to enter the equipment room and talk to the archer.
I'm not sure if you need to talk to Saba.
After talking to Dunstan at the anvil, you need to talk to Denulth, but I'm not sure how to tell when Dunstan has been talked to. I don't think there are any varbit changes or messages in chat.
> Add Death plateau

- src/main/java/com/questhelper/quests/betweenarock/BetweenARock.java
- src/main/java/com/questhelper/quests/toweroflife/PuzzleSolver.java
- src/main/java/com/questhelper/quests/toweroflife/TowerOfLife.java
- src/main/java/com/questhelper/steps/PuzzleStep.java
- Added Tower of Life Quest
- Added generic Puzzle Step
- Fixed a substep in Between a Rock
> Add Tower of Life quest

- src/main/java/com/questhelper/quests/songoftheelves/SongOfTheElves.java
Some minor SOTE changes:
-Added dialogue open for Elena while in the hideout.
-Added Talking to Elena in the Cell to the panel
-Limestone bricks requirement listed twice
> Small SOTE changes

- src/main/java/com/questhelper/quests/mountaindaughter/MountainDaughter.java
Added a few extra things on here, combatgear req, fixed a place where it said you need spade, added more alternate gloves.
> A few updates to mountain daughter

- src/main/java/com/questhelper/QuestHelperConfig.java
Picture: https://i.imgur.com/0Iadls4.png
> Add colors to their own section in the Quest Helper config.

- src/main/java/com/questhelper/quests/gettingahead/GettingAhead.java
Any saw for getting ahead quest
> Getting ahead any saw

- src/main/java/com/questhelper/quests/fishingcontest/FishingContest.java
We don't talk about the [last PR]( https://github.com/Zoinkwiz/quest-helper/pull/149.)
> Add Fishing Contest quest

- src/main/java/com/questhelper/quests/sinsofthefather/SinsOfTheFather.java
About as small of a change that can be made lol.  Corrected the dialog option when talking to Veliaf.
> Tiny SOTF fix

- src/main/java/com/questhelper/quests/deathtothedorgeshuun/DeathToTheDorgeshuun.java
- src/main/java/com/questhelper/quests/familycrest/FamilyCrest.java
Fixed a typo in death to the dorgeshuun and just added a Zones note
> Fixed typo

- src/main/java/com/questhelper/quests/mourningsendparti/MourningsEndPartI.java
> mourningsendparti: fix typo

- src/main/java/com/questhelper/quests/recipefordisaster/RFDStart.java
Signed-off-by: Senmori <thesenmori@gmail.com>
> Add dialog options for starting RFD.

- src/main/java/com/questhelper/quests/asoulsbane/ASoulsBane.java
- src/main/java/com/questhelper/quests/shadowofthestorm/ShadowOfTheStorm.java
- src/main/java/com/questhelper/quests/tribaltotem/TribalTotem.java
Shadow of the Storm also does highlight Silverlight when equipped with the dyed silverlight.
As well, A Soul's Bane was missing some recommended items/combat requirements.
> Fix Tribal Totem using wrong coins.

- src/main/java/com/questhelper/quests/gettingahead/GettingAhead.java
Updated GettingAhead to add a dialog for the part where you have to take nails from a workbench
> Updated GettingAhead to add dialog option for workbench

- .gitignore
- src/main/java/com/questhelper/quests/thedepthsofdespair/TheDepthsOfDespair.java
> Add the Depths of Despair

- src/main/java/com/questhelper/quests/creatureoffenkenstrain/CreatureOfFenkenstrain.java
This is a rebase of #188 and some further changes to fix logic, and make it work with the current structure.
> Add Creature of Fenkenstrain

- src/main/java/com/questhelper/panel/PanelDetails.java
- src/main/java/com/questhelper/panel/QuestStepPanel.java
- src/main/java/com/questhelper/quests/scorpioncatcher/ScorpionCatcher.java
- src/main/java/com/questhelper/requirements/ItemRequirement.java
- Add Scorpion Catcher 
- Add `PanelDetails.contains` to check all substeps for the current step as well when choosing the panel to highlight.
> Add Scorpion Catcher and recursive check for substeps

- src/main/java/com/questhelper/quests/thelosttribe/TheLostTribe.java
Highlights how to get out of the tunnels after finding the brooch.
> Add a highlighted step to the Lost Tribe

- src/main/java/com/questhelper/quests/animalmagnetism/AnimalMagnetism.java
- src/main/java/com/questhelper/quests/animalmagnetism/PuzzleSolver.java
Notes:
- there is a dialogue path of buying one chicken at a time that isn't covered by this helper yet
> Add Animal Magnetism

- src/main/java/com/questhelper/steps/NpcStep.java
Rebase of https://github.com/Zoinkwiz/quest-helper/pull/206.
> Add the ability for NpcStep to show safespots for fights.

- src/main/java/com/questhelper/quests/theascentofarceuus/TheAscentOfArceuus.java
#179
The rocks you need to search were not highlighted. This adds those rock's object ids.
> Add object ids to the searchrocks step of ascent of arceuus.

- src/main/java/com/questhelper/quests/shilovillage/ShiloVillage.java
Adds safespots to the Nazastrool fight in Shilo Village.
> Add safespots to Nazastrool

- src/main/java/com/questhelper/quests/curseoftheemptylord/CurseOfTheEmptyLord.java
> Added mory legs check to curse of the empty lord

- src/main/java/com/questhelper/quests/throneofmiscellania/ThroneOfMiscellania.java
Made it check correctly for the bows in the quest and a tooltip that you lose the bow during the quest
> Fixed bow check for throne of miscellania

- src/main/java/com/questhelper/quests/regicide/Regicide.java
Also added some tooltips for better explanation of some requirements.
> Use new convenience methods in Regicide

- src/main/java/com/questhelper/quests/olafsquest/OlafsQuest.java
> Fixed recommended item Olafs quest

- src/main/java/com/questhelper/quests/theslugmenace/TheSlugMenace.java
Skill Necklace -> Skills Necklace
> Fix typo in TheSlugMenace.java

- src/main/java/com/questhelper/quests/deviousminds/DeviousMinds.java
Rebases https://github.com/Zoinkwiz/quest-helper/pull/155.
> Add Devious Minds

- src/main/java/com/questhelper/quests/merlinscrystal/MerlinsCrystal.java
Changed all instances of `excalabur` to `excalibur`
> Fixed spelling mistakes in Merlin's Crystal

- src/main/java/com/questhelper/quests/taibwowannaitrio/TaiBwoWannaiTrio.java
Rebase + improved handling for https://github.com/Zoinkwiz/quest-helper/pull/273.
> Add tai bwo wannai trio

- build.gradle
- src/main/java/com/questhelper/quests/betweenarock/BetweenARock.java
- src/main/java/com/questhelper/quests/deserttreasure/DesertTreasure.java
- src/main/java/com/questhelper/quests/recipefordisaster/RFDAwowogei.java
- src/main/java/com/questhelper/quests/recipefordisaster/RFDDwarf.java
- src/main/java/com/questhelper/quests/taibwowannaitrio/TaiBwoWannaiTrio.java
> A few small typos n stuff

- build.gradle
- src/main/java/com/questhelper/ExternalQuestResources.java
- src/main/java/com/questhelper/QuestHelperQuest.java
- src/main/java/com/questhelper/QuestVarbits.java
- src/main/java/com/questhelper/quests/belowicemountain/BelowIceMountain.java
- src/main/java/com/questhelper/steps/emote/QuestEmote.java
One TODO left with regards to runelite/runelite#13482 for the new emote id
I tested it as well as I could, but could use another pass by someone else.
> Add Below Ice Mountain

- src/main/java/com/questhelper/quests/deserttreasure/DesertTreasure.java
- src/main/java/com/questhelper/quests/monkeymadnessii/MonkeyMadnessII.java
- src/main/java/com/questhelper/quests/recipefordisaster/RFDPiratePete.java
MM2 - Dialogue when talking to Narnode
RFD Pirate Pete - Fishcake
> Typo fix (RFD Pirate Pete and MM2)

- src/main/java/com/questhelper/quests/deserttreasure/DesertTreasure.java
Desert Treasure - Fixed typo Pyrimid :+1:
> Desert Treasure typo

- src/main/java/com/questhelper/ItemCollections.java
- src/main/java/com/questhelper/quests/belowicemountain/BelowIceMountain.java
- src/main/java/com/questhelper/quests/betweenarock/BetweenARock.java
- src/main/java/com/questhelper/quests/deserttreasure/DesertTreasure.java
- src/main/java/com/questhelper/quests/dragonslayer/DragonSlayer.java
- src/main/java/com/questhelper/quests/dragonslayerii/DragonSlayerII.java
- src/main/java/com/questhelper/quests/theascentofarceuus/TheAscentOfArceuus.java
Added Antifire potion ItemCollection
Few typo fixes
Added saw alternate for DS2
and a few other things idk
> Few fixes to things again

- src/main/java/com/questhelper/quests/onesmallfavour/OneSmallFavour.java
accross->across
Credit to RickyDactyl
> chore(onesmallfavour): fix typo

- src/main/java/com/questhelper/quests/gettingahead/GettingAhead.java
> Add skill requirements for GettingAhead quest

- src/main/java/com/questhelper/quests/thequeenofthieves/TheQueenOfThieves.java
> Add X Marks The Spot to The Queen of Thieves Quest Requirement

- src/main/java/com/questhelper/quests/atailoftwocats/ATailOfTwoCats.java
Didn't know that I had to wait for the potatos to grow. Added some extra detail
> Add extra potato growing detail

- build.gradle
- src/main/java/com/questhelper/quests/priestinperil/PriestInPeril.java
Quick Adjustment to priest in peril to add Zammy monk to sidebar as "Enemies to defeat" was missing it - Requested by @Koponeen#5806 on discord
Adjustment to the temple dog to specify mage only and ring of recoil info  
Also updated build,gradle to latest runelite build but thats not important
> Changes to PriestInPeril - SideBar Fix

- src/main/java/com/questhelper/quests/architecturalalliance/ArchitecturalAlliance.java
Adds 100% favour in all areas as a General Requirement, and adds `Kharedst's Memoirs` as a Recommended Item. I believe this miniquest it supposed to be about gaining 100% favours (at least by the looks of the wiki) however our guide only covers the minimum steps of speaking to each of the architects which requires 100% already.
> Add General Requirements, Recommended Items to 'Architectural Alliance' miniquest

- src/main/java/com/questhelper/quests/rumdeal/RumDeal.java
Davey won't give you the holy wrench unless you have 47 prayer points
> Add prayer points req to speak to Davey step in 'Rum Deal' quest

- src/main/java/com/questhelper/quests/heroesquest/HeroesQuest.java
Added pickaxe a recommended item to be brought along for this step. Suggested via discord.
> Add pickaxe to get ice gloves step in `Heroes Quest` quest

- src/main/java/com/questhelper/quests/animalmagnetism/AnimalMagnetism.java
Fix undeadChickens dropping quest after first chicken is but before second chicken is handed to Ava.
Add missing steps to acquire blessed axe from UndeadTwigs to side panel.
--
Lets be done with this forever, eh? 🥇
> Animal Magnetism Fixes (Finally)

- src/main/java/com/questhelper/quests/architecturalalliance/ArchitecturalAlliance.java
- Updated NPC location and description for Shayda to her new location after the Shayzien Remap
- Changed Lovada step decription from 'Lovajengj' to 'Lovakengj'
> Fixed a typo and updated npc location for Shayda in Shayzien

- src/main/java/com/questhelper/quests/taleoftherighteous/TaleOfTheRighteous.java
Updates the `Tale of the Righteous` quest locations and NPCs caused by Kourend rework
> Update `Tale of the Righteous` Quest

- src/main/java/com/questhelper/achievementdiaries/fremennik/FremennikMedium.java
Moved petRockPOH down so the ordering matches what's displayed on the panel. 
Added that it's a pet house that needs to be built in the petRockPOH step as I was unsure what I needed when testing and had to double check the wiki.
> Fremennik Medium Diary tweaks

- src/main/java/com/questhelper/quests/theascentofarceuus/TheAscentOfArceuus.java
Update NPC ID caused by Kourend rework
> Update `The Ascent of Arceuus` Quest

- src/main/java/com/questhelper/quests/thedepthsofdespair/TheDepthsOfDespair.java
Update NPC ID change caused by Kourend rework
> Update `The Depths of Despair` Quest

- src/main/java/com/questhelper/quests/betweenarock/BetweenARock.java
- src/main/java/com/questhelper/quests/deviousminds/DeviousMinds.java
- src/main/java/com/questhelper/quests/goblindiplomacy/GoblinDiplomacy.java
- src/main/java/com/questhelper/quests/impcatcher/ImpCatcher.java
- src/main/java/com/questhelper/quests/naturespirit/NatureSpirit.java
- src/main/java/com/questhelper/quests/theslugmenace/TheSlugMenace.java
> Fixes to stuff i guess again.

- src/main/java/com/questhelper/quests/akingdomdivided/AKingdomDivided.java
- src/main/java/com/questhelper/quests/taibwowannaitrio/TaiBwoWannaiTrio.java
Typo in A Kingdom Divided
Added missing requirement for Tai Bwo Wannai Trio, fixed typo and mentioned that you lose spear during the quest
> Fixed a few things

- src/main/java/com/questhelper/quests/recipefordisaster/RFDPiratePete.java
Weird looking ground kelp id :+1:
> RFD Pirate Pete

- src/main/java/com/questhelper/quests/junglepotion/JunglePotion.java
- src/main/java/com/questhelper/quests/theslugmenace/TheSlugMenace.java
Updated  Us to Use in Slug Menace - Requested by @Slimmerik#6062
Adjusted Jungle Potion Changed volcania moss to Volencia Moss and Changed Fairy Tail to Fairy Tale - Requested by @jim#6969
> Gramatical fixes

- src/main/java/com/questhelper/achievementdiaries/falador/FaladorMedium.java
- src/main/java/com/questhelper/achievementdiaries/fremennik/FremennikElite.java
Use the item id 9419 (Mithril Grapple) rather than the item id 9418 (Mithril Grapple (unf))
> Fix MITH_GRAPPLE item id

- src/main/java/com/questhelper/quests/animalmagnetism/AnimalMagnetism.java
- src/main/java/com/questhelper/quests/gardenoftranquility/GardenOfTranquillity.java
- src/main/java/com/questhelper/quests/horrorfromthedeep/HorrorFromTheDeep.java
3 small typos/grammatical errors in 3 separate quests that I happened to come across.
> small typos

- src/main/java/com/questhelper/achievementdiaries/kandarin/KandarinEasy.java
- src/main/java/com/questhelper/achievementdiaries/kandarin/KandarinElite.java
- src/main/java/com/questhelper/achievementdiaries/kandarin/KandarinHard.java
- src/main/java/com/questhelper/achievementdiaries/kandarin/KandarinMedium.java
- src/main/java/com/questhelper/banktab/QuestHelperBankTagService.java
- src/main/java/com/questhelper/panel/PanelDetails.java
- src/main/java/com/questhelper/panel/QuestOverviewPanel.java
> Add hidden sections to kandarin diaries

- src/main/java/com/questhelper/ExternalQuestResources.java
- src/main/java/com/questhelper/QuestHelperQuest.java
- src/main/java/com/questhelper/QuestVarbits.java
- src/main/java/com/questhelper/panel/questorders/QuestOrders.java
- src/main/java/com/questhelper/quests/anightatthetheatre/ANightAtTheTheatre.java
A Night at the Theatre quest for the reworked parts. Includes everything except for ToB battle guides. The entire last part for ToB is entered under one step, "Complete Theatre of Blood"
> A Night at the Theatre

- src/main/java/com/questhelper/quests/clientofkourend/ClientOfKourend.java
Veos ID on the Port Piscarillius docks is incorrect, probably from the AKD update
> client of kourend: updated Veos NPC id

- src/main/java/com/questhelper/quests/thefeud/TheFeud.java
Fixes for Issues #428 and #429
> Fix The Fued duplicated step and typos

- src/main/java/com/questhelper/quests/anightatthetheatre/ANightAtTheTheatre.java
Closes #440 by correcting the misspelling of Drakan's Medallion
> Rename Draken's Medallion to Drakan's Medallion

- src/main/java/com/questhelper/quests/rumdeal/RumDeal.java
> Fix typo in Rum deal

- src/main/java/com/questhelper/quests/merlinscrystal/MerlinsCrystal.java
Seems to be 5 and not 4 https://i.imgur.com/WQIV2x0.png
> Talk to Lady of the Lake fix

- build.gradle
- src/main/java/com/questhelper/quests/thefremenniktrials/CombinationPuzzle.java
- src/main/java/com/questhelper/quests/thefremenniktrials/TheFremennikTrials.java
- src/main/java/com/questhelper/requirements/RuneliteRequirement.java
- src/main/java/com/questhelper/steps/ConditionalStep.java
- src/main/java/com/questhelper/steps/QuestStep.java
This will add usage of RuneliteRequirement to allow for a more persisted experience, as well as fixing a couple issues with incorrect Widget checks.
> Fremmy trials fixes

- src/main/java/com/questhelper/quests/throneofmiscellania/ThroneOfMiscellania.java
MIscellania changed to Miscellania
> Fixed rewards typo in Throne of Miscellania

- src/main/java/com/questhelper/quests/deathtothedorgeshuun/DeathToTheDorgeshuun.java
- src/main/java/com/questhelper/quests/fairytalei/FairytaleI.java
:) fixed a few things to not trigger my ocd with a spacebar on fairytale and also a missing req for death to the dorgeshuun
> Death to dorg req and change to text on fairytale p1

- src/main/java/com/questhelper/quests/alfredgrimhandsbarcrawl/AlfredGrimhandsBarcrawl.java
- src/main/java/com/questhelper/quests/onesmallfavour/OneSmallFavour.java
- src/main/java/com/questhelper/quests/shilovillage/ShiloVillage.java
- src/main/java/com/questhelper/quests/taibwowannaitrio/TaiBwoWannaiTrio.java
Just fixing a few typos I noticed while questing.
> Minor text fixes

- src/main/java/com/questhelper/quests/clocktower/ClockTower.java
Noticed a small typo while doing the quest :)
> Update spelling of trough

- src/main/java/com/questhelper/quests/mourningsendparti/MourningsEndPartI.java
- src/main/java/com/questhelper/quests/mourningsendpartii/MourningsEndPartII.java
Finally got the ranged lvl to do these quests. Just some minor changes for clarity and direction.
> Mournings End pt 1 & 2 changes

- src/main/java/com/questhelper/achievementdiaries/varrock/VarrockHard.java
I'm dumb and change the task panel boostable when I put in this change a while ago.
> fix for #573

- src/main/java/com/questhelper/quests/makinghistory/MakingHistory.java
Fixed non-existant code
Fixes #583
> Fix Making History suggested Fairy ring(s)

- src/main/java/com/questhelper/quests/wanted/Wanted.java
It needs to specify in the readable instructions that 20 is required.
> Specify you need 20 rune or pure essence

- src/main/java/com/questhelper/quests/deserttreasure/DesertTreasure.java
Taken from https://oldschool.runescape.wiki/w/Desert_Treasure/Quick_guide
Adding because I was confused and got totally monked running around looking for a safespot
> Improve safespot description for desert treasure

- src/main/java/com/questhelper/quests/regicide/Regicide.java
Just something I missed during regicide quest
> Added more info in regicide quest dialog

- src/main/java/com/questhelper/quests/onesmallfavour/OneSmallFavour.java
Just info I missed while doing one small favour
> More info in one small favour quest

- src/main/java/com/questhelper/achievementdiaries/ardougne/ArdougneMedium.java
Didn't get a chance to test - sub isn't active, but logically this should be the fix
Fixes #622
> Fix Ardy Medium Diary Mith Grapple

- src/main/java/com/questhelper/achievementdiaries/falador/FaladorMedium.java
- src/main/java/com/questhelper/achievementdiaries/fremennik/FremennikElite.java
- src/main/java/com/questhelper/achievementdiaries/kandarin/KandarinMedium.java
- src/main/java/com/questhelper/achievementdiaries/lumbridgeanddraynor/LumbridgeMedium.java
Removed references of 'Mithril' grapple
Removed capital G in grapple 
Noticed while doing #625 - I wish the G actually was capitalized but it's not so 😄
Also included the Ardougne reference in #625 to prevent merge conflicts
> Cleanup Mith grapple references in diaries

- src/main/java/com/questhelper/quests/mourningsendparti/MourningsEndPartI.java
> Fix Mournings End Part 1 typo

- src/main/java/com/questhelper/quests/mountaindaughter/MountainDaughter.java
Add 5 Muddy Rocks instead of just saying collect muddy rocks.
> Edit Mountain Daughter helper text string

- src/main/java/com/questhelper/achievementdiaries/falador/FaladorMedium.java
Changed visual text from `2` to `4`
also snuck in the usual capitalization/plural changes in the other runes
Fixes #629
> Fix rune requirement in Falador Medium Diary

- src/main/java/com/questhelper/quests/songoftheelves/SongOfTheElves.java
> Fix Song of the Elves quest rewards

- src/main/java/com/questhelper/achievementdiaries/ardougne/ArdougneHard.java
Levels were mixed up
Fixes #647
> Fix Ardougne Hard Diary farming requirements

- src/main/java/com/questhelper/achievementdiaries/morytania/MorytaniaHard.java
Mentioned needing to toggle on piety to complete the task.
Fixes #663
> Fix Morytania Hard Diary piety pray step

- src/main/java/com/questhelper/quests/taibwowannaitrio/TaiBwoWannaiTrio.java
> Fix Tai Bwo Wannai Trio wording

- src/main/java/com/questhelper/achievementdiaries/desert/DesertElite.java
> Update Desert Elite Diary

- src/main/java/com/questhelper/ItemCollections.java
- src/main/java/com/questhelper/quests/makingfriendswithmyarm/MakingFriendsWithMyArm.java
- src/main/java/com/questhelper/quests/monkeymadnessii/MM2Sabotage.java
- src/main/java/com/questhelper/quests/monkeymadnessii/MonkeyMadnessII.java
- src/main/java/com/questhelper/quests/sinsofthefather/SinsOfTheFather.java
- src/main/java/com/questhelper/quests/thefremennikexiles/TheFremennikExiles.java
handful of fixes to late game quests. Largely changed the path for MM2 sabotage, each step now has a route. Without any failures it is linear path to follow compared to the clusterfuck that was it earlier. Also added a 'reset' path +  step in the even someone does get caught they aren't completely lost on where to go. Sidenote: there are two 'styles' of route being used right now and a style someone else made for satchel 3+. The two styles are the movement to safe spot and solid line. It was a bit weird and somewhat confusing when I went through the platform. I'll leave that up to you if you want to change it.
Other changes are mostly just for clarity or fixing incorrect things.
> More quest changes

- src/main/java/com/questhelper/achievementdiaries/ardougne/ArdougneHard.java
> Fix typo in ArdougneHard.java

- src/main/java/com/questhelper/achievementdiaries/desert/DesertElite.java
Re-alphabetize the skill requirements changed in #672
> Re-order SkillRequirements in DesertElite.java

- src/main/java/com/questhelper/achievementdiaries/desert/DesertElite.java
> Fix Gold Leaf requirement in Desert Elite Diary

- src/main/java/com/questhelper/quests/thedigsite/TheDigSite.java
Added note to not left click the vial as you will empty it.
> Update TheDigSite.java - Include warning about liquid

- src/main/java/com/questhelper/quests/animalmagnetism/AnimalMagnetism.java
> Add missing XP rewards

- src/main/java/com/questhelper/quests/animalmagnetism/AnimalMagnetism.java
I remember seeing my suggestion was acknowledged but I never re-looked at the code
> Fix Animal Magnetisim missed mistake

- src/main/java/com/questhelper/quests/toweroflife/TowerOfLife.java
Wiki has no mention of gloves either. 🤷
Fixes #717
> Remove gloves requirement in TowerOfLife.java

- src/main/java/com/questhelper/achievementdiaries/falador/FaladorMedium.java
I'm unsure what ID:`6660` is used for, but the alternate already exists in `RagAndBoneManII` so I'm copying it.
Fixes #725
> Fix missing fishingExplosive in Falador Medium diary

- src/main/java/com/questhelper/achievementdiaries/westernprovinces/WesternMedium.java
Not a Kyatt, was a copy error added feldip to be a bit more specific
> Text change

- src/main/java/com/questhelper/quests/atasteofhope/ATasteOfHope.java
if youre an idiot (like me) and forgot where _Veliaf Hurtz_ is during the quest, this would be a big help (its not on the wiki)
> where to find Veliaf Hurtz

- src/main/java/com/questhelper/quests/mourningsendpartii/MourningsEndPartII.java
Add Teleport Crystal as a recommended item. 
Add Catalytic Talisman as alternate for Death Talisman.
> Update Mourning's End Part II. Implement changes from #753 .

- src/main/java/com/questhelper/ExternalQuestResources.java
- src/main/java/com/questhelper/QuestHelperQuest.java
- src/main/java/com/questhelper/QuestVarbits.java
- src/main/java/com/questhelper/panel/questorders/QuestOrders.java
- src/main/java/com/questhelper/quests/beneathcursedsands/BeneathCursedSands.java
- src/main/java/com/questhelper/quests/beneathcursedsands/TombRiddle.java
This PR adds a step-by-step for the new [Beneath Cursed Sands](https://oldschool.runescape.wiki/w/Beneath_Cursed_Sands) quest. 
Since I only have one account and am not able to go back and re-check past steps, it might be that a handful of them are not working perfectly, especially since this is my first shot at coding anything RuneLite/Quest Helper related, so some review/testing is definitely required. For 95%+ of the quest, things should work smoothly and work as expected, though.
Some TODO's, all of which are added to the quest's code itself:
> Quest: Beneath Cursed Sands

- src/main/java/com/questhelper/quests/ragandboneman/RagAndBoneManII.java
Expanded helper text to prevent others farming these for a while
> Update helper text for RagAndBoneManII to save other poor souls

- src/main/java/com/questhelper/quests/anightatthetheatre/ANightAtTheTheatre.java
> A Night at the Theatre: Fix typo

- src/main/java/com/questhelper/achievementdiaries/ardougne/ArdougneMedium.java
- src/main/java/com/questhelper/achievementdiaries/kandarin/KandarinElite.java
- src/main/java/com/questhelper/quests/rumdeal/SlugSteps.java
- src/main/java/com/questhelper/steps/NpcStep.java
diary was pointing to the lobby tuna swordfish spot, this is the shark spot.
> shark fishing spot is 1520

- src/main/java/com/questhelper/quests/zogreflesheaters/ZogreFleshEaters.java
> Zogre Flesh Eaters: Fix side-panel steps

- src/main/java/com/questhelper/quests/icthlarinslittlehelper/IcthlarinsLittleHelper.java
> Icthlarin's Little Helper: add linen to item requirements

- src/main/java/com/questhelper/quests/recipefordisaster/RFDSirAmikVarze.java
* Add Ice Gloves to panel for step `Making the brulee`
* Correct typo `acces` -> `access`
> Recipe for Disaster/Sir Amik Varze: add Ice Gloves to panel step and spelling correction

- src/main/java/com/questhelper/panel/questorders/QuestOrders.java
> Optimal Ironman Order: Move Architectural Alliance

- src/main/java/com/questhelper/quests/demonslayer/DemonSlayer.java
"Delirth" corrected to "Delrith"
> fixed typo in Demon Slayer

- src/main/java/com/questhelper/achievementdiaries/kourend/KourendMedium.java
Fixes #843
To be honest, I didn't build the source and test it properly but I think this is OK? :)
> Fix item requirement for Kourend medium

- src/main/java/com/questhelper/quests/dreammentor/DreamMentor.java
Slight changes to the wording of the food requirements along with adding a note about using sacks of food to complete the task.
Example of changes:
Original:
7x 7 of one type of food
7x 7 of one type of food
6x 6 of a third type of food
14x food, 5x of 2 different types of food, and 4x of another
Modified:
7x some type of food
7x some other type of food
6x a third type of food
14x food: 5x some type of food, 5x some other type of food, 4x a third type of food
If there is a way to be any more clear or concise please let me know.
EDIT: sorry for double
> Dream Mentor -food req clarity

- src/main/java/com/questhelper/quests/wanted/Wanted.java
Added Ring of Dueling to recommended items as it includes several teleports that are helpful to the quest(Castle Wars, Al Kharid). Ring of Dueling is recommended on the wiki and has been requested by user in the Discord. Additionally capitalized "Glory" in "Amulet of Glory".
> Wanted -add recommend item Ring of Dueling

- src/main/java/com/questhelper/achievementdiaries/kourend/KourendMedium.java
- src/main/java/com/questhelper/achievementdiaries/wilderness/WildernessHard.java
- src/main/java/com/questhelper/quests/runemysteries/RuneMysteries.java
- src/main/java/com/questhelper/quests/thetouristtrap/TheTouristTrap.java
Kourend Medium typo fix
Wilderness Hard typo fix
Rune Mysteries typo fix
The Tourist Trap requirement change (It should only be 10 feathers but I am not completely sure on this one)
> Fixed some typos in quests and diares, changed wrong tourist trap req

- src/main/java/com/questhelper/achievementdiaries/kourend/KourendHard.java
Fixed a small typo in the Kourend Hard diary rewards
> Fix typo in Kourend Hard diary rewards

- src/main/java/com/questhelper/quests/princealirescue/PrinceAliRescue.java
Prince Ali Rescue had some of its dialogue rewritten in the 27/04/2022 game update. This PR aligns the quest dialogue steps with the current version.
> Update Prince Ali Rescue to align with new quest version

- src/main/java/com/questhelper/panel/questorders/QuestOrders.java
> add hopespear's will to ironman optimal order

- src/main/java/com/questhelper/quests/watchtower/Watchtower.java
Added recommended item antifire/antifire shield (item collections of both) to the Watchtower quest. There are instances where you must run by blue dragons hence why these items are recommended.
fixes #882
> Watchtower -ItemRecAntifire

- src/main/java/com/questhelper/quests/bonevoyage/BoneVoyage.java
Added information on the bank chest which can be created after completing Bone Voyage:
-added note
-added recommended items
fixes #893
> BoneVoyage - RecBankChest

- src/main/java/com/questhelper/quests/mourningsendparti/MourningsEndPartI.java
Added tip to have 7 free inventory spots after I got out there with a full inv and learned the hard way 😎
> need free spaces to pick up everything mourner drops

- src/main/java/com/questhelper/achievementdiaries/kandarin/KandarinHard.java
- src/main/java/com/questhelper/quests/biohazard/Biohazard.java
- src/main/java/com/questhelper/quests/royaltrouble/RoyalTrouble.java
Biohazard -order fix
Kandarin Hard -order fix
Royal Trouble -incorrect NpcID fix
> Minor Fixes

- src/main/java/com/questhelper/achievementdiaries/ardougne/ArdougneElite.java
- src/main/java/com/questhelper/achievementdiaries/ardougne/ArdougneHard.java
- src/main/java/com/questhelper/achievementdiaries/ardougne/ArdougneMedium.java
- src/main/java/com/questhelper/achievementdiaries/falador/FaladorElite.java
- src/main/java/com/questhelper/achievementdiaries/fremennik/FremennikMedium.java
- src/main/java/com/questhelper/achievementdiaries/kandarin/KandarinElite.java
- src/main/java/com/questhelper/achievementdiaries/kandarin/KandarinMedium.java
- src/main/java/com/questhelper/achievementdiaries/karamja/KaramjaElite.java
- src/main/java/com/questhelper/achievementdiaries/karamja/KaramjaMedium.java
- src/main/java/com/questhelper/achievementdiaries/kourend/KourendElite.java
- src/main/java/com/questhelper/achievementdiaries/lumbridgeanddraynor/LumbridgeHard.java
- src/main/java/com/questhelper/achievementdiaries/morytania/MorytaniaHard.java
- src/main/java/com/questhelper/achievementdiaries/varrock/VarrockHard.java
- src/main/java/com/questhelper/achievementdiaries/westernprovinces/WesternHard.java
Fixed frem medium also added message to the farming tasks on how to skip them using the tick boxes
> Diary Changes

- src/main/java/com/questhelper/achievementdiaries/kandarin/KandarinEasy.java
Updated the Tiny net name to correctly increment through the steps.
> Fix Tiny net name

- src/main/java/com/questhelper/achievementdiaries/desert/DesertElite.java
> Fix typo in Elite Desert Diary step

- src/main/java/com/questhelper/achievementdiaries/morytania/MorytaniaEasy.java
Sarah sells empty sacks for 1gp, confirmed in game and on the [Wiki](https://oldschool.runescape.wiki/w/Sarah%27s_Farming_shop.)
> fix morytania easy quest step

- src/main/java/com/questhelper/quests/theeyesofglouphrie/TheEyesOfGlouphrie.java
Previously attempted in 702f406b3ee868c69984a64b206eae37333da34a but they only edited one of two places so it doesn't show up.
> Fix Fairy Ring tip in Eyes of Glouphrie

- src/main/java/com/questhelper/quests/inaidofthemyreque/InAidOfTheMyreque.java
Updated the wording of returning to the hideout to be clearer during the Ivandis' Legacy step of the In Aid of the Myreque quest.
> Updated step wording in Aid of the Myreque

- src/main/java/com/questhelper/quests/thedigsite/TheDigSite.java
> Fix grinding charcoal for making explosive step

- src/main/java/com/questhelper/quests/thegiantdwarf/TheGiantDwarf.java
- Add dialog steps for taking the assigned tasks
- Add "go down the stairs" as sub step
- This will keep the last step of the quest active while going to Commander Veldaban.
> The Giant Dwarf improvements

- src/main/java/com/questhelper/quests/forgettabletale/ForgettableTale.java
- Highlight "Yes please." while traveling to Keldagrim
- Change Dwarven Stout reward quantity to 2
> Forgettable Tale improvements

- src/main/java/com/questhelper/quests/recruitmentdrive/RecruitmentDrive.java
Removed the female requirement as this was removed 09/11/2022 as seen on the wiki https://oldschool.runescape.wiki/w/Recruitment_Drive
> Update Recruitment Drive to remove the female requirement

- src/main/java/com/questhelper/quests/woodcutting/Woodcutting.java
Changed from normal trees to oak trees between 15 and 35 Woodcutting
> Add oak trees until lvl 35

- src/main/java/com/questhelper/quests/ernestthechicken/ErnestTheChicken.java
You can't leave through the front door
> Specify how to exit the manor

- src/main/java/com/questhelper/achievementdiaries/desert/DesertElite.java
- src/main/java/com/questhelper/achievementdiaries/lumbridgeanddraynor/LumbridgeMedium.java
Address https://github.com/Zoinkwiz/quest-helper/issues/993
> fix al kharid typos in code and messages

- src/main/java/com/questhelper/QuestHelperQuest.java
- src/main/java/com/questhelper/achievementdiaries/fremennik/FremennikElite.java
- src/main/java/com/questhelper/quests/thefremennikexiles/TheFremennikExiles.java
Exactly what it says on the tin.
> Typo fixes related to dagannoths

- src/main/java/com/questhelper/quests/clientofkourend/ClientOfKourend.java
> Add games necklace to client of kourend recommended items

- src/main/java/com/questhelper/quests/heroesquest/HeroesQuest.java
> Add ice gloves to heroes quest step

- src/main/java/com/questhelper/quests/shilovillage/ShiloVillage.java
Fixes issue #988 Typo in Shilo Village - dolem to dolmen in src/main/java/com/questhelper/quests/shilovillage/ShiloVillage.java line 361
> Fix issue #988 Typo in Shilo Village

- src/main/java/com/questhelper/quests/fightarena/FightArena.java
https://oldschool.runescape.wiki/w/General_Khazard
Khazard is lvl 142
> Fight Arena Typo

- src/main/java/com/questhelper/QuestHelperConfig.java
- src/main/java/com/questhelper/overlays/QuestHelperWorldOverlay.java
- src/main/java/com/questhelper/questhelpers/QuestHelper.java
- src/main/java/com/questhelper/steps/DetailedQuestStep.java
- src/main/java/com/questhelper/steps/ItemStep.java
- src/main/java/com/questhelper/steps/NpcStep.java
- src/main/java/com/questhelper/steps/ObjectStep.java
- src/main/java/com/questhelper/steps/QuestStep.java
- src/main/java/com/questhelper/steps/QuestSyncStep.java
This adds new highlighting styles. 
Also cleaned things up a little bit here and there. Also seems the automatic formatting did not agree with how things were formatted in the files I worked on.
If there are other things that can reliably be highlit in other ways, I don't mind adding that as well.
> Add highlight styles

- src/main/java/com/questhelper/quests/clientofkourend/ClientOfKourend.java
Spent 10 minutes punching seagulls to find out I misread their drop table. Added note for where to buy a feather in port sarim.
> Add tooltip for purchasing feather nearby

- src/main/java/com/questhelper/quests/mourningsendpartii/MourningsEndPartII.java
Missing the key requirement for exiting the mourner basement
> Fixing item requirements for ME2 return to the temple step

- src/main/java/com/questhelper/quests/deserttreasure/DesertTreasure.java
closes #1092 - Desert Treasure I - Add Ice Gloves requirement
> Add Ice Gloves requirement

- src/main/java/com/questhelper/helpers/quests/songoftheelves/SongOfTheElves.java
> Add stamina potion recommendations to SOTE

- src/main/java/com/questhelper/helpers/quests/lunardiplomacy/LunarDiplomacy.java
There are three points in the quest where you have to fight, but only one of them mentions the combat gear. It's hinted to gather suqah hide, but the step to bring them doesn't mention them as required items.
> Add required items for LunarDiplomacy

- src/main/java/com/questhelper/helpers/quests/junglepotion/JunglePotion.java
Ardrigal is only used in Legend's quest
> Fix Ardrigal step in JunglePotion.java

- src/main/java/com/questhelper/helpers/quests/cooksassistant/CooksAssistant.java
- src/main/java/com/questhelper/steps/DetailedQuestStep.java
- src/main/java/com/questhelper/steps/QuestStep.java
- src/main/java/com/questhelper/steps/WidgetHighlights.java
Was very underwhelmed with the old version especially since this is the first quest that most new players will do. This should 'modernize' the quest and be a lot more approachable for newer players.
> Cooks Assistant Rewrite

- src/main/java/com/questhelper/helpers/quests/impcatcher/ImpCatcher.java
modernization of the imp catcher quest
> Imp catcher rewrite

- src/main/java/com/questhelper/helpers/quests/thefremennikexiles/TheFremennikExiles.java
Updating Exile's boss step with mention of its weakness to crush
> adding boss weakness type to helper

- src/main/java/com/questhelper/helpers/achievementdiaries/desert/DesertMedium.java
- src/main/java/com/questhelper/helpers/achievementdiaries/falador/FaladorMedium.java
- src/main/java/com/questhelper/helpers/achievementdiaries/fremennik/FremennikEasy.java
- src/main/java/com/questhelper/helpers/achievementdiaries/kandarin/KandarinHard.java
- src/main/java/com/questhelper/helpers/achievementdiaries/karamja/KaramjaMedium.java
- src/main/java/com/questhelper/helpers/achievementdiaries/kourend/KourendElite.java
- src/main/java/com/questhelper/helpers/achievementdiaries/lumbridgeanddraynor/LumbridgeEasy.java
- src/main/java/com/questhelper/helpers/achievementdiaries/lumbridgeanddraynor/LumbridgeMedium.java
- src/main/java/com/questhelper/helpers/achievementdiaries/westernprovinces/WesternMedium.java
- src/main/java/com/questhelper/helpers/skills/woodcutting/Woodcutting.java
- src/main/java/com/questhelper/helpers/skills/woodcuttingmember/WoodcuttingMember.java
List of changes, it's just because tree names were changed. Based of this https://github.com/runelite/runelite/commit/41b23c9c34960423d08839845310e16a0e33cdcd
Desert Medium Teak
Falador Medium Willow
Fremennik Easy Oak
Kandarin Hard Yew Longbow
Karamja Medium Teak
Kourend Elite Redwood
Lumbridge and draynor Easy Oak
Lumbridge and draynor Medium Willow
Western province Medium Teak
Skill helper for Woodcutting
chopOakTrees
chopWillowTrees
Member chopOakTrees
Member chopTeakTrees
> Corrected all changes done to tree names with Forestry update

- src/main/java/com/questhelper/helpers/quests/murdermystery/MurderMystery.java
I just did this quest and David was the murderer. However, the NPC Step said "Talk to Anna".
Also, just FYI talking to the poison salesman right before this step does not progress the quest helper log.
> 2 Murder Mystery Talking Steps: Suspect(typo) & Poison Salesman(bug)

- src/main/java/com/questhelper/helpers/quests/shilovillage/ShiloVillage.java
correct boss name spelling in helper step list
> Simple Shilo Village Helper Typo

- src/main/java/com/questhelper/helpers/quests/enakhraslament/EnakhrasLament.java
Added a mention about needing prayer points in the getting started section. This will ensure the has points to use the protect from melee prayer
closes #1185
> enakhras lament - added note - (#1185)

- src/main/java/com/questhelper/helpers/quests/akingdomdivided/AKingdomDivided.java
> Grammer fix in Kingdom Divided

- src/main/java/com/questhelper/helpers/achievementdiaries/fremennik/FremennikElite.java
- src/main/java/com/questhelper/helpers/achievementdiaries/fremennik/FremennikMedium.java
First-time contributor here. Let me know if you don't agree with anything here or if something should be different.
- Medium diary changes: Displaying Eagles Peak & Between a Rock requirements in general requirements.
- Elite diary changes: Agility, Crafting, Runecrafting are now marked as "boostable".
- closes #1184 
- closes #1177
> Fremennik Medium & Elite Diary Reqs

- src/main/java/com/questhelper/helpers/miniquests/thegeneralsshadow/TheGeneralsShadow.java
- src/main/java/com/questhelper/helpers/quests/deserttreasure/DesertTreasure.java
- src/main/java/com/questhelper/helpers/quests/thegolem/TheGolem.java
- src/main/java/com/questhelper/helpers/quests/thetouristtrap/TheTouristTrap.java
https://oldschool.runescape.wiki/w/Shantay_Pass
> use correct spelling of "Shantay Pass"

- src/main/java/com/questhelper/helpers/achievementdiaries/karamja/KaramjaHard.java
- src/main/java/com/questhelper/helpers/quests/bonevoyage/BoneVoyage.java
- src/main/java/com/questhelper/helpers/quests/deserttreasure/DesertTreasure.java
- src/main/java/com/questhelper/helpers/quests/dragonslayerii/DragonSlayerII.java
- src/main/java/com/questhelper/helpers/quests/eadgarsruse/EadgarsRuse.java
- src/main/java/com/questhelper/helpers/quests/kingsransom/KingsRansom.java
- src/main/java/com/questhelper/helpers/quests/merlinscrystal/MerlinsCrystal.java
- src/main/java/com/questhelper/helpers/quests/onesmallfavour/OneSmallFavour.java
- src/main/java/com/questhelper/helpers/quests/plaguecity/PlagueCity.java
- src/main/java/com/questhelper/helpers/quests/princealirescue/PrinceAliRescue.java
Reminder for Zoink to look at the Lady in the Lake part of Merlin's crystal.
Other than that this is just a bunch of random feedback stuff and some random typos etc.
> Just a few feedback things fixed

- src/main/java/com/questhelper/helpers/quests/animalmagnetism/AnimalMagnetism.java
Referring to [#987](https://github.com/Zoinkwiz/quest-helper/issues/987)
> Moved undead chickens to correct panel and added tooltip.

- src/main/java/com/questhelper/helpers/mischelpers/herbrun/HerbRun.java
Adds the Hosidius herb patch to the Herb Helper.
> Add Hosidius Patch to Herb Helper

- src/main/java/com/questhelper/helpers/quests/shadowofthestorm/ShadowOfTheStorm.java
> Fix typo in the Shadow of the Storm quest

- src/main/java/com/questhelper/helpers/quests/landofthegoblins/LandOfTheGoblins.java
- src/main/java/com/questhelper/helpers/quests/thefremenniktrials/TheFremennikTrials.java
- src/main/java/com/questhelper/helpers/quests/thegardenofdeath/TheGardenOfDeath.java
Update incorrect quest point reward and add a missing reward for the quests:
- The Fremennik Trials
- The Garden of Death
Also made **Land of the Goblins** consistent with the rest of the code.
> Fix quest point rewards

- src/main/java/com/questhelper/helpers/achievementdiaries/fremennik/FremennikEasy.java
I tested this commit with my alt, making sure it correctly pointed to the NPC.
On my alt I have complted The Fremennik Trials, but not started The Fremennik Exiles/Isles.
I didn't add `JARVALD_10407` as it's the NPC on the Waterbirth Island
> Search for alternate Jarvald NPC for Fremennik Easy Diary

- src/main/java/com/questhelper/helpers/quests/eaglespeak/EaglesPeak.java
https://github.com/Zoinkwiz/quest-helper/assets/962989/9fa468ed-f203-4147-811d-a0316d0d3a01
https://github.com/Zoinkwiz/quest-helper/assets/962989/91359dde-2ae6-4fc8-a097-db9809d22f8d
> Eagles' Peak: Wait for 6 bird feed before finishing step

- src/main/java/com/questhelper/helpers/quests/shilovillage/ShiloVillage.java
> Add info tooltip to ShiloVillage light source

- src/main/java/com/questhelper/helpers/achievementdiaries/ardougne/ArdougneHard.java
> Add boost info to Mithril platebody in Ardy Hard

- src/main/java/com/questhelper/helpers/achievementdiaries/lumbridgeanddraynor/LumbridgeElite.java
> Update LumbridgeElite boostable information

- src/main/java/com/questhelper/helpers/achievementdiaries/westernprovinces/WesternEasy.java
Keeping the old Brimstail NPC ID just to be sure
> Western Provinces Easy Diary: Fix Brimstail Npc ID

- src/main/java/com/questhelper/helpers/quests/thetouristtrap/TheTouristTrap.java
Fixes https://discord.com/channels/772056816242130964/1119375205089951774
> The Tourist Trap: Fix typo (Theiving -> Thieving)

- src/main/java/com/questhelper/helpers/quests/royaltrouble/RoyalTrouble.java
Not a very interesting PR - feel free to close if this should be obvious enough for later game quests
> Royal Trouble: Add energy restore item recommendation

- src/main/java/com/questhelper/helpers/quests/kingsransom/KingsRansom.java
I noticed this typo while doing the quest
> Fixed typo in KingsRansom

- build.gradle
- src/test/java/com/questhelper/MockedTest.java
- src/test/java/com/questhelper/MockedTestBase.java
Add support for simple unit tests
An example test can be found in #1289: https://github.com/pajlada/quest-helper/blob/quest/the-path-of-glouphrie/src/test/java/com/questhelper/helpers/quests/thepathofglouphrie/SolutionTest.java
> feat: unit tests, update junit, add mockito & add test job

- src/main/java/com/questhelper/helpers/quests/thegiantdwarf/TheGiantDwarf.java
Fixes a single character typo I noticed.
> Fixed typo in TheGiantDwarf.java

- src/main/java/com/questhelper/helpers/quests/ghostsahoy/GhostsAhoy.java
Thanks @cdfisher for helping test & fix this with the OSRS wiki team
Fixes #1309
> Ghosts Ahoy: Add completion of The Restless Ghost as a hard requirement

- src/main/java/com/questhelper/helpers/quests/recipefordisaster/QuizSteps.java
Not tested in-game, going off the wiki & what the reporting issue stated. Couldn't find a video showing off the NPC since each person gets different options
Fixes #1332
> fix: RFD Lumbridge Guide Professor Gronigen option

- src/main/java/com/questhelper/helpers/quests/betweenarock/BetweenARock.java
> Between a Rock...: Add the Double ammo mould as an alternative to crafting with Golden cannonball

- src/main/java/com/questhelper/helpers/quests/thegolem/TheGolem.java
Fix text for using the program on the golem
Add missing "Use implement" step to the sidebar
> Polish the "The Golem" quest

- src/main/java/com/questhelper/helpers/quests/waterfallquest/WaterfallQuest.java
Remove duplicate "a rope" text from "Put Glarial to rest" steps
> Update WaterfallQuest.java - Remove duplicate "a rope"

- src/main/java/com/questhelper/helpers/achievementdiaries/lumbridgeanddraynor/LumbridgeEasy.java
- Lumbridge & Draynor Easy Diary: Fix Cave Bug task conditional order
- Lumbridge & Draynor Easy Diary: Highlight all Cave Bugs
> Small polish for the Lumbridge & Draynor Easy Diary

- src/main/java/com/questhelper/helpers/quests/onesmallfavour/OneSmallFavour.java
Originally reported by `flip` in Discord https://discord.com/channels/772056816242130964/772056861934354433/1183475541282652300
> One Small Favour: fix Taverley typo in teleport suggestion

- src/main/java/com/questhelper/helpers/achievementdiaries/falador/FaladorEasy.java
The step to get a security book from the jail guy was missing a dialog highlight
> Falador Easy Diary: Add missing dialog highlight

- src/main/java/com/questhelper/helpers/quests/witchshouse/WitchsHouse.java
> Witch's House: Highlight the "Yes." option when starting the quest

- src/main/java/com/questhelper/helpers/quests/grimtales/GrimTales.java
> Grim Tales: Fix the "Yes." dialog highlight to start the quest

- src/main/java/com/questhelper/helpers/achievementdiaries/lumbridgeanddraynor/LumbridgeMedium.java
I read only the panel title and did not realize I was suppose to craft it in the cow pen. This should hopefully make it more clear for future people.😄
> Update LumbridgeMedium.java wording so title is clear where to craft

- src/main/java/com/questhelper/helpers/achievementdiaries/varrock/VarrockHard.java
- Varrock Hard Diary: Polish the burn yew log on church step
- Varrock Hard Diary: Polish the Fancy Stone redecoration step
> Varrock Hard Diary: Some polish

- src/main/java/com/questhelper/helpers/achievementdiaries/fremennik/FremennikMedium.java
Magic Butterfly Net can be used as an alternative.
Fixes #1364
> Frem med - butterfly net alternative

- src/main/java/com/questhelper/helpers/achievementdiaries/kourend/KourendElite.java
- src/main/java/com/questhelper/requirements/conditional/Conditions.java
- Kourend & Kebos Elite Diary: Polish essence steps
- chore: document some Conditions constructors
> Polish Kourend & Kebos Elite Diary

- src/main/java/com/questhelper/helpers/quests/theknightssword/TheKnightsSword.java
Just making sure all dialog options are highlighted
> The Knight's Sword: Super minor polish

- src/main/java/com/questhelper/helpers/achievementdiaries/varrock/VarrockEasy.java
super minor polish that would've helped me
> Varrock Easy Diary: Include location for the trout fishing step

- src/main/java/com/questhelper/helpers/quests/asoulsbane/ASoulsBane.java
- A Soul's Bane: Add starter dialog highlight
- A Soul's Bane: Update Fear room message & remove unused code
Preferably, the quest is tested before this is merged in since I didn't actually test the Fear room changes.
The messaging is the most important part, and that could be included without testing so I could change it if needed.
> A Soul's Bane: Minor polish

- src/main/java/com/questhelper/helpers/quests/spiritsoftheelid/SpiritsOfTheElid.java
- Spirits of the Elid: Rename "Lightsource" to "Light source"
- Spirits of the Elid: Fix minor variable typo
- Spirits of the Elid: Fix a minor guide typo
> Spirits of the Elid: Fix some minor typos

- src/main/java/com/questhelper/helpers/quests/betweenarock/BetweenARock.java
Fixes #1389
I confirmed it in-game this time :)
> Between A Rock: Fix Ammo Mould quantity/Double Ammo Mould alternative

- src/main/java/com/questhelper/helpers/quests/bonevoyage/BoneVoyage.java
* Fix incorrect English grammar. "Talk the" to "Talk to the"
> Grammar fixes to Bone Voyage WorldPoints

- src/main/java/com/questhelper/helpers/quests/thetouristtrap/TheTouristTrap.java
* Fix incorrect English grammar. "Talk the" to "Talk to the"
> Grammar fix to Tourist Trap WorldPoint

- src/main/java/com/questhelper/helpers/quests/holygrail/HolyGrail.java
Also added in steps when to use the Draynor tele tab
Refer to Zoinkwiz/quest-helper#1413
> feat:added "DraynorTele" to recommended items in Holy Grail quest

- src/main/java/com/questhelper/helpers/quests/defenderofvarrock/DefenderOfVarrock.java
Corrected npc highlighting and teleport recommended
> Defender of Varrock changes

- src/main/java/com/questhelper/helpers/quests/thegreatbrainrobbery/TheGreatBrainRobbery.java
It's incredibly unlikely you'd need 200 nails, but as reported in #1337 it can happen so better to recommend a safer quantity still to avoid any unhappy accidents.
closes #1337
> feature:increase nails needed for GBR

- src/main/java/com/questhelper/helpers/quests/creatureoffenkenstrain/CreatureOfFenkenstrain.java
> feature:Remove plural item usage for consistency in CoF

- src/main/java/com/questhelper/helpers/quests/eaglespeak/EaglesPeak.java
> feature:added text highlight for Outpost tele in Eagles' Peak

- src/main/java/com/questhelper/helpers/quests/enlightenedjourney/CraftingGuildBalloonFlight.java
- src/main/java/com/questhelper/questinfo/ExternalQuestResources.java
> feature:Added external resources for balloon guides

- src/main/java/com/questhelper/helpers/achievementdiaries/falador/FaladorMedium.java
> fix:Add Mogres as a combat requirement in Falador Medium

- src/main/java/com/questhelper/helpers/achievementdiaries/kandarin/KandarinHard.java
> feature:Added requirement to be on normal spellbook for Kandarin Hard

- src/main/java/com/questhelper/helpers/quests/thegardenofdeath/TheGardenOfDeath.java
SE to NW for first table search.
fixes #1315
> fix: Update direction in Garden of Death

- src/main/java/com/questhelper/helpers/quests/mountaindaughter/MountainDaughter.java
> feature: Added pole obtaining step to MD

- src/main/java/com/questhelper/helpers/quests/deserttreasure/DesertTreasure.java
- src/main/java/com/questhelper/helpers/quests/eadgarsruse/EadgarsRuse.java
- src/main/java/com/questhelper/helpers/quests/trollstronghold/TrollStronghold.java
> fix:Added more climbing boot variations to quests

- src/main/java/com/questhelper/helpers/quests/ragandboneman/RagAndBoneManII.java
> feat:Added ranged weapon req for vulture in rabm2

- src/main/java/com/questhelper/helpers/quests/deserttreasureii/DesertTreasureII.java
> feat:add all bosses to getCombatRequirements for DT2

- src/main/java/com/questhelper/collections/ItemCollections.java
- src/main/java/com/questhelper/helpers/quests/aporcineofinterest/APorcineOfInterest.java
> feat:added teleport reccs to APoI

- src/main/java/com/questhelper/helpers/quests/recipefordisaster/RFDDwarf.java
> feat:add better teleport reccs to RFD Dwarf

- src/main/java/com/questhelper/helpers/quests/shadowofthestorm/ShadowOfTheStorm.java
> feat:added Al Kharid tele to SotS

- build.gradle
- src/main/java/com/questhelper/helpers/miniquests/familypest/FamilyPest.java
- src/main/java/com/questhelper/helpers/quests/defenderofvarrock/DefenderOfVarrock.java
- src/main/java/com/questhelper/questinfo/QuestHelperQuest.java
- src/main/java/com/questhelper/questinfo/QuestVarbits.java
- src/main/java/com/questhelper/requirements/var/VarplayerRequirement.java
Fairly bog-standard helper with no new features added.
> Add Defender of Varrock

- src/main/java/com/questhelper/helpers/quests/thelosttribe/TheLostTribe.java
> fix:Silverware step is no longer skippable in TLT

- src/main/java/com/questhelper/helpers/quests/secretsofthenorth/SecretsOfTheNorth.java
> fix:Remove duplicate instructions in SotN

- src/main/java/com/questhelper/helpers/quests/deathtothedorgeshuun/DeathToTheDorgeshuun.java
> fix:Improved Zanik detection in DttD

- src/main/java/com/questhelper/helpers/quests/templeofikov/TempleOfIkov.java
> feat:Added hint on re-obtaining the Pendant of Lucien

- src/main/java/com/questhelper/helpers/quests/wanted/Wanted.java
> fix:Adds more details to sidebar for finding Solus in Canifis

- src/main/java/com/questhelper/helpers/quests/thehandinthesand/TheHandInTheSand.java
> feat:Added tele to Sarim in HitS

- src/main/java/com/questhelper/helpers/quests/deserttreasure/DesertTreasure.java
> feat:Added climbing boots to step where needed in DT1

- src/main/java/com/questhelper/helpers/quests/monkeymadnessii/MonkeyMadnessII.java
> feat:Added climbing boots to MM2

- src/main/java/com/questhelper/helpers/quests/zogreflesheaters/ZogreFleshEaters.java
> feat:Improved directions to Sithik in ZFE

- src/main/java/com/questhelper/helpers/quests/songoftheelves/SongOfTheElves.java
> feat:Added tele crystal to bax step in SOTE

- src/main/java/com/questhelper/helpers/quests/thegolem/TheGolem.java
> feat:Added necklace of passage to The Golem

- src/main/java/com/questhelper/helpers/quests/naturespirit/NatureSpirit.java
> feat:Added prayer point req to Nature Spirit

- src/main/java/com/questhelper/helpers/quests/legendsquest/LegendsQuest.java
> feat:Changed step used for descending rope in Legends' Quest

- src/main/java/com/questhelper/helpers/quests/mourningsendparti/MourningsEndPartI.java
> feat:Improved item suggestions in MEP2

- src/main/java/com/questhelper/helpers/achievementdiaries/lumbridgeanddraynor/LumbridgeHard.java
- src/main/java/com/questhelper/helpers/quests/belowicemountain/BelowIceMountain.java
- src/main/java/com/questhelper/helpers/quests/misthalinmystery/MisthalinMystery.java
- src/main/java/com/questhelper/helpers/quests/monkeymadnessii/MonkeyMadnessII.java
- src/main/java/com/questhelper/helpers/quests/runemysteries/RuneMysteries.java
- src/main/java/com/questhelper/helpers/quests/sinsofthefather/SinsOfTheFather.java
- src/main/java/com/questhelper/helpers/skills/agility/Agility.java
- src/main/java/com/questhelper/helpers/skills/woodcutting/Woodcutting.java
- src/main/java/com/questhelper/helpers/skills/woodcutting/WoodcuttingMember.java
- src/main/java/com/questhelper/managers/QuestMenuHandler.java
- src/main/java/com/questhelper/panel/questorders/QuestOrders.java
- src/main/java/com/questhelper/questinfo/QuestHelperQuest.java
This supersedes #1160, matching it to the current state of QH.
> Small fixes

- src/main/java/com/questhelper/helpers/quests/mountaindaughter/MountainDaughter.java
> feat:Added icons to indicate trees to cut in MD

- src/main/java/com/questhelper/helpers/quests/contact/Contact.java
> feat:Added tip for combat style in Contact!

- src/main/java/com/questhelper/helpers/quests/entertheabyss/EnterTheAbyss.java
> feat:Added inventory req for EtA

- src/main/java/com/questhelper/helpers/quests/merlinscrystal/MerlinsCrystal.java
- src/main/java/com/questhelper/helpers/quests/thegiantdwarf/TheGiantDwarf.java
fixes #1296 hopefully. It was previously counting these steps as completed if the player's name appeared in any chat boxes.
> fix:Fixed mistructured DialogRequirements in MC and TGD

- src/main/java/com/questhelper/helpers/achievementdiaries/karamja/KaramjaHard.java
> fix:Added enemies to defeat to Karamja Hard

- src/main/java/com/questhelper/helpers/quests/eadgarsruse/EadgarsRuse.java
> fix:Update parrot hint after showing to Eadgar in ER

- src/main/java/com/questhelper/helpers/achievementdiaries/varrock/VarrockHard.java
> bug:Add ironman check for hunter req Varrock Hard

- src/main/java/com/questhelper/helpers/quests/insearchofthemyreque/InSearchOfTheMyreque.java
> fix:Corrected ISotM bridge region

- src/main/java/com/questhelper/QuestHelperPlugin.java
- src/main/java/com/questhelper/helpers/quests/sheepshearer/SheepShearer.java
- src/main/java/com/questhelper/steps/NpcStep.java
More of a walk through and slightly more elegant solution. With steps on how to get the wool, turn wool into balls of wool, and then turn in. It's not perfect but I added things to catch edge cases such as opening the helper mid-quest progress.
> Sheep Shearer Rewrite

- src/main/java/com/questhelper/helpers/quests/mountaindaughter/MountainDaughter.java
> fix:Corrected muddy rock check in MD

- src/main/java/com/questhelper/helpers/quests/fishingcontest/FishingContest.java
> Fixes fishing context

- src/main/java/com/questhelper/QuestHelperConfig.java
- src/main/java/com/questhelper/steps/DetailedQuestStep.java
> feat:Added toggle for flashing minimap arrow

- src/main/java/com/questhelper/QuestHelperConfig.java
- src/main/java/com/questhelper/panel/QuestOverviewPanel.java
Allows for the sidebar to show all requirements for a quest, including requirements from sub-quests.
> Add full quest requirement option

- src/main/java/com/questhelper/helpers/achievementdiaries/karamja/KaramjaMedium.java
- src/main/java/com/questhelper/helpers/achievementdiaries/westernprovinces/WesternHard.java
I have confirmed in-game that the ID of the trees are correct
> fix: Mahogany Tree ID for varlamore update

- src/main/java/com/questhelper/helpers/quests/childrenofthesun/ChildrenOfTheSun.java
Just removed a part where it said When varlamore releases.
> Children of the sun very small edit

- src/main/java/com/questhelper/helpers/quests/twilightspromise/TwilightsPromise.java
Some typoes
Extra highlight for stairs
Changes requirement a little
> More pr's for Zoinkwiz to look through

- src/main/java/com/questhelper/helpers/quests/fairytaleii/FairytaleII.java
* Changed xp reward lamp from 2, to 1
* Removed irrelevant comment
PR resolves [1521](https://github.com/Zoinkwiz/quest-helper/issues/1521)
> fix: Fairy Tale Part 2 rewards [1521]

- src/main/java/com/questhelper/runeliteobjects/GlobalFakeObjects.java
> fix: Hopleez text replacement includes dialog sprite text

- src/main/java/com/questhelper/managers/QuestManager.java
- src/main/java/com/questhelper/panel/QuestOverviewPanel.java
- src/main/java/com/questhelper/panel/QuestRequirementPanel.java
- src/main/java/com/questhelper/panel/QuestStepPanel.java
This means it can be run on SwingUtilities, which removes the client lag.
> remove init checks for quests

- src/main/java/com/questhelper/helpers/quests/secretsofthenorth/SecretsOfTheNorth.java
> feat: Added hair clip as lockpick alt in SotN

- src/main/java/com/questhelper/helpers/quests/biohazard/Biohazard.java
> fix: Added touch paper to section reqs in Biohazard

- src/main/java/com/questhelper/helpers/quests/onesmallfavour/OneSmallFavour.java
`JUNGLE_FORESTER_3955` walks closer to the Shilo gate, technically quicker to talk to them
> Use the closer Jungle Forester NPC

- src/main/java/com/questhelper/helpers/mischelpers/herbrun/FarmingPatch.java
- src/main/java/com/questhelper/helpers/mischelpers/herbrun/FarmingWorld.java
- src/main/java/com/questhelper/helpers/mischelpers/herbrun/HerbRun.java
- src/main/java/com/questhelper/helpers/mischelpers/herbrun/PatchImplementation.java
Added the Varlamore herb patch to the generic helper
Added each variant of the whistle as suggested teleport item
closes #1532
> Herb run varlamore

- src/main/java/com/questhelper/helpers/quests/holygrail/HolyGrail.java
- src/main/java/com/questhelper/helpers/quests/makingfriendswithmyarm/MakingFriendsWithMyArm.java
Added draynor tab and glory alts in quests where there were issues
> cleared up some draynor tele options

- src/main/java/com/questhelper/panel/QuestOverviewPanel.java
> fix:Removed skip of further reqs on duplicate quest found

- src/main/java/com/questhelper/bank/banktab/QuestBankTabInterface.java
> fix: retain opacity on bank tab reopen

- src/main/java/com/questhelper/managers/QuestManager.java
Found this when trying to debug https://github.com/Zoinkwiz/quest-helper/issues/1564
> fix: npe when switching profiles & the quest list wanted to be updated

- src/main/java/com/questhelper/QuestHelperPlugin.java
- src/main/java/com/questhelper/helpers/mischelpers/allneededitems/AllNeededItems.java
- src/main/java/com/questhelper/managers/QuestManager.java
- src/main/java/com/questhelper/overlays/QuestHelperWorldOverlay.java
This avoids null states where checks require the user to be logged in.
fixes #1564
> fix: Add additional logged in checks for config changes

- src/main/java/com/questhelper/helpers/quests/lunardiplomacy/MemoryChallenge.java
- src/test/java/com/questhelper/helpers/quests/lunardiplomacy/MemoryChallengeTest.java
This adjusts the path generation from being hardcoded options to dynamic based on the actual path. This should ensure it's more reliable and less prone to error.
> feat: Made the Memory Puzzle in Lunar Diplomacy dynamic

- src/main/java/com/questhelper/helpers/achievementdiaries/falador/FaladorHard.java
Updates prospector set requirements to just require helmet
fixes #1567
> Update falador hard prospector requirement

- src/main/java/com/questhelper/helpers/quests/thegiantdwarf/TheGiantDwarf.java
> fix: Remove redwood logs as viable log for TGD

- src/main/java/com/questhelper/helpers/miniquests/enchantedkey/EnchantedKeyDigStep.java
- src/main/java/com/questhelper/helpers/miniquests/themagearenaii/MageArenaBossStep.java
- src/main/java/com/questhelper/helpers/quests/coldwar/PenguinEmote.java
- src/main/java/com/questhelper/helpers/quests/deserttreasure/GiveItems.java
- src/main/java/com/questhelper/helpers/quests/deserttreasureii/GrowthPuzzleStep.java
- src/main/java/com/questhelper/helpers/quests/deserttreasureii/MemoryPuzzle.java
- src/main/java/com/questhelper/helpers/quests/deserttreasureii/WhispererSteps.java
- src/main/java/com/questhelper/helpers/quests/enlightenedjourney/BalloonFlightStep.java
- src/main/java/com/questhelper/helpers/quests/enlightenedjourney/TaverleyBalloonFlight.java
- src/main/java/com/questhelper/helpers/quests/lunardiplomacy/BringLunarItems.java
- src/main/java/com/questhelper/helpers/quests/lunardiplomacy/MemoryChallenge.java
- src/main/java/com/questhelper/helpers/quests/lunardiplomacy/MimicChallenge.java
- src/main/java/com/questhelper/helpers/quests/lunardiplomacy/NumberChallenge.java
- src/main/java/com/questhelper/helpers/quests/observatoryquest/StarSignAnswer.java
- src/main/java/com/questhelper/helpers/quests/recruitmentdrive/LadyTableStep.java
- src/main/java/com/questhelper/helpers/quests/recruitmentdrive/MsHynnAnswerDialogQuizStep.java
- src/main/java/com/questhelper/helpers/quests/recruitmentdrive/SirRenItchoodStep.java
- src/main/java/com/questhelper/helpers/quests/thepathofglouphrie/MonolithPuzzle.java
- src/main/java/com/questhelper/helpers/quests/thepathofglouphrie/YewnocksPuzzle.java
- src/main/java/com/questhelper/steps/MultiNpcStep.java
- src/main/java/com/questhelper/steps/NpcStep.java
- src/main/java/com/questhelper/steps/ObjectStep.java
A function with Subscribe which overrides another function with Subscribe will mean there are two invocations of the function. This removes occurrences of this.
> Remove duplicate subscribes on overridden functionality

- src/main/java/com/questhelper/helpers/quests/animalmagnetism/PuzzleSolver.java
- src/main/java/com/questhelper/helpers/quests/coldwar/PenguinEmote.java
- src/main/java/com/questhelper/helpers/quests/sleepinggiants/SleepingGiants.java
- src/main/java/com/questhelper/helpers/quests/theeyesofglouphrie/PuzzleStep.java
- src/main/java/com/questhelper/helpers/quests/toweroflife/PuzzleSolver.java
- src/main/java/com/questhelper/runeliteobjects/GlobalFakeObjects.java
- src/main/java/com/questhelper/runeliteobjects/extendedruneliteobjects/RuneliteObjectManager.java
- src/main/java/com/questhelper/runeliteobjects/extendedruneliteobjects/WidgetReplacement.java
- src/main/java/com/questhelper/steps/DetailedQuestStep.java
- src/main/java/com/questhelper/steps/PuzzleStep.java
- src/main/java/com/questhelper/steps/QuestStep.java
- src/main/java/com/questhelper/steps/WidgetStep.java
- src/main/java/com/questhelper/steps/widget/AbstractWidgetHighlight.java
- src/main/java/com/questhelper/steps/widget/AncientSpells.java
- src/main/java/com/questhelper/steps/widget/ArceuusSpells.java
- src/main/java/com/questhelper/steps/widget/LunarSpells.java
- src/main/java/com/questhelper/steps/widget/NormalSpells.java
- src/main/java/com/questhelper/steps/widget/Spell.java
- src/main/java/com/questhelper/steps/widget/SpellWidgetHighlight.java
- src/main/java/com/questhelper/steps/widget/WidgetDetails.java
- src/main/java/com/questhelper/steps/widget/WidgetHighlight.java
This is intended for usage with the SpellWidgetHighlight, as an easy way to specifiy the spell you want to use.
> feat: Added Spell enum for spells

- src/main/java/com/questhelper/playerquests/bikeshedder/BikeShedder.java
- src/main/java/com/questhelper/steps/DetailedQuestStep.java
- src/main/java/com/questhelper/steps/tools/QuestPerspective.java
This allows for zones to be highlighted rather than just individual tiles.
> feat: Add zone highlight functionality

- src/main/java/com/questhelper/QuestHelperConfig.java
- src/main/java/com/questhelper/helpers/mischelpers/allneededitems/AllNeededItems.java
- src/main/java/com/questhelper/managers/QuestOverlayManager.java
- src/main/java/com/questhelper/overlays/BackgroundQuestHelperTooltipOverlay.java
- src/main/java/com/questhelper/overlays/QuestHelperTooltipOverlay.java
- src/main/java/com/questhelper/steps/ConditionalStep.java
- src/main/java/com/questhelper/steps/DetailedOwnerStep.java
- src/main/java/com/questhelper/steps/DetailedQuestStep.java
- src/main/java/com/questhelper/steps/QuestStep.java
This should help identify background helpers and why stuff is being highlighted.
> feat: Added tooltip for background helpers

- src/main/java/com/questhelper/helpers/miniquests/alfredgrimhandsbarcrawl/AlfredGrimhandsBarcrawl.java
- src/main/java/com/questhelper/helpers/quests/piratestreasure/RumSmugglingStep.java
- src/main/java/com/questhelper/helpers/quests/taibwowannaitrio/TaiBwoWannaiTrio.java
- src/main/java/com/questhelper/helpers/quests/tearsofguthix/TearsOfGuthix.java
- src/main/java/com/questhelper/helpers/quests/templeofikov/TempleOfIkov.java
- Zambo changed their name to Zembo
- Lucien & Light Creature NPC ID changes - since I can't verify which NPC ID is actually correct, I've made it accept any NPC ID matching them
> fix: build for latest runelite version

- src/main/java/com/questhelper/helpers/quests/fairytalei/FairytaleI.java
I moved the name and location of the first farmer to a newline as for some folks this may be more legible as it is more consistent with the other farmers.
> Minor formatting change in FairyTale I

- src/main/java/com/questhelper/tools/QuestHelperWorldMapPoint.java
> fix: Remove unnecessary println

- src/main/java/com/questhelper/helpers/quests/thefremennikisles/TheFremennikIsles.java
- src/test/java/com/questhelper/helpers/quests/thefremennikisles/TheFremennikIslesTest.java
to be merged into the `fix-skill-checks-items` branch
> add tests for the Fremennik Isles skill check

- src/main/java/com/questhelper/playerquests/bikeshedder/BikeShedder.java
- src/main/java/com/questhelper/steps/DetailedQuestStep.java
also updated bike shedder quest to highlight 1 and 100 coins next to the bush to ensure it still highlights stack you have
> fix: coins not highlighting in inventory correctly

- src/main/java/com/questhelper/helpers/quests/piratestreasure/PiratesTreasure.java
Dialog is "Ok, I will bring you some Karamja Rum."
> Fix Pirate Treasure - Talk to Redbeard Step

- build.gradle
- src/main/java/com/questhelper/helpers/quests/whileguthixsleeps/WeightStep.java
- src/main/java/com/questhelper/helpers/quests/whileguthixsleeps/WhileGuthixSleeps.java
- **weight step: polish**
- **Add closed bed chest as an alternative step for getting the steps**
> mini polish for While Guthix Sleeps helper

- src/main/java/com/questhelper/helpers/achievementdiaries/westernprovinces/WesternHard.java
You can also kill an elf archer (lvl 90)
> Western Hard Dairy: Added info that u can also kill a level 90 elf

- src/main/java/com/questhelper/helpers/quests/whileguthixsleeps/DolmenType.java
- src/main/java/com/questhelper/helpers/quests/whileguthixsleeps/HerblorePuzzle.java
- src/main/java/com/questhelper/requirements/util/LogicHelper.java
Adds the ability to specify expected completion value, which I've done for two certain ones. Others assume the generic 35 or 3 are completion states still.
> Fix balance potion WGS

- src/main/java/com/questhelper/helpers/quests/darknessofhallowvale/DarknessOfHallowvale.java
Highlighted broken wall in Burgh de Rott. Resolves #1328
> Darkness of Hallowvale - Highlighted broken wall

- src/main/java/com/questhelper/helpers/quests/taibwowannaitrio/TaiBwoWannaiTrio.java
> fix: typo in Tai Bwo Wannai Trio

- src/main/java/com/questhelper/helpers/quests/witchspotion/WitchsPotion.java
Update Witch's Potion to have: 
* A combat requirement to kill a rat
* A new panel for the step of killing the rat
* Add item requirements to the step to turn in the items to the witch.
> Update Witch's Potion Quest

- src/main/java/com/questhelper/helpers/quests/whileguthixsleeps/HerblorePuzzle.java
- src/main/java/com/questhelper/helpers/quests/whileguthixsleeps/StatueLocation.java
- src/main/java/com/questhelper/helpers/quests/whileguthixsleeps/WhileGuthixSleeps.java
Added cammy tele to overall recommended for WGS, and added worldlines to the herblore puzzle.
> Wgs improvements

- src/main/java/com/questhelper/panel/QuestRequirementsPanel.java
this caused input lag (????)
not sure why is caused input lag, also not sure why only very few people could reproduce it, but this has been confirmed to fix it for one user
Thanks a lot to SwedishHokage from Discord who helped report & test this issue
> fix: don't constantly update all requirement texts

- src/main/java/com/questhelper/helpers/quests/templeoftheeye/RuneEnergyStep.java
- src/main/java/com/questhelper/helpers/quests/templeoftheeye/RunicEnergy.java
- src/main/java/com/questhelper/helpers/quests/templeoftheeye/TempleOfTheEye.java
- Adds memory to the runic energy puzzle
- Adds teleport hints
- Adds mind altar to region for the tutorial
> Improvements to Temple of the Eye

- src/main/java/com/questhelper/managers/QuestMenuHandler.java
See https://github.com/Zoinkwiz/quest-helper/issues/1740
> Fix: No "stop" right click menu option for Achievement diaries

- src/main/java/com/questhelper/panel/QuestRequirementsPanel.java
- src/main/java/com/questhelper/playerquests/bikeshedder/BikeShedder.java
Fixes #1746
[2024-09-14-hide-tooltip-button-with.webm](https://github.com/user-attachments/assets/f3d8a84c-dee5-48d3-a0f3-1cbee54bc3ee)
> fix: tooltip buttons not being hidden alongside their requirements

- src/main/java/com/questhelper/QuestHelperPlugin.java
- src/main/java/com/questhelper/config/ConfigKeys.java
- src/main/java/com/questhelper/helpers/achievementdiaries/morytania/MorytaniaElite.java
- src/main/java/com/questhelper/helpers/miniquests/barbariantraining/BarbarianTraining.java
- src/main/java/com/questhelper/requirements/RequirementValidator.java
- src/main/java/com/questhelper/statemanagement/BarbarianTrainingStateTracker.java
- src/main/java/com/questhelper/statemanagement/PlayerStateManager.java
- src/main/java/com/questhelper/steps/ConditionalStep.java
This adds a new class, RequirementValidator, which acts as a trimmed down ConditionalStep with just requirements. The intention is for this to allow for requirements to be continually updated, in this case for barb training.
Currently there's a bit too much setup for it required I feel outside of the class itself, so I think I need to give this another look in a bit.
> Add barb training req check

- build.gradle
no dependency needed this time
> feat: add shadow jar build task

- src/main/java/com/questhelper/collections/ItemCollections.java
> Add Imcando hammer (off-hand)

- src/main/java/com/questhelper/helpers/quests/shieldofarrav/ShieldOfArravPhoenixGang.java
Update ShieldOfArravPhoenixGang.java
> Fix typo Straven (Shield of Arrav Phoenix Gang)

- src/main/java/com/questhelper/QuestHelperConfig.java
- src/main/java/com/questhelper/QuestHelperPlugin.java
- src/main/java/com/questhelper/managers/QuestManager.java
- src/main/java/com/questhelper/steps/DetailedQuestStep.java
- src/main/java/com/questhelper/steps/QuestStep.java
This should allow for players to have most quest steps have a shortest path generated, if they also have that plugin.
> feat: Added shortest path config option

- src/main/java/com/questhelper/helpers/quests/deathontheisle/DeathOnTheIsle.java
- src/main/java/com/questhelper/panel/questorders/QuestOrders.java
- src/main/java/com/questhelper/questinfo/ExternalQuestResources.java
- src/main/java/com/questhelper/questinfo/QuestHelperQuest.java
- src/main/java/com/questhelper/questinfo/QuestVarbits.java
No
Yes, although the wording is open for change
> feat: Initial Death on the Isle quest helper

- src/main/java/com/questhelper/helpers/quests/meatandgreet/MeatAndGreet.java
- src/main/java/com/questhelper/panel/questorders/QuestOrders.java
- src/main/java/com/questhelper/questinfo/ExternalQuestResources.java
- src/main/java/com/questhelper/questinfo/QuestHelperQuest.java
- src/main/java/com/questhelper/questinfo/QuestVarbits.java
No, this will be fixed together with the other quests in a separate PR
There are a few open questions I'd like tested:
- Are the sidebar options always lit up? (not sure if I've added substeps to everything correctly)
- Does it handle destroying of kebabs well? there are 2 scenarios where you can destroy kebabs and you have to get new ones
- Does it handle death to the minotaur well? (note you will have to pay a graveyard fee)
- Are there any accessible teleports I could add throughout the quest? So far I've added none
> feat: Add Meat and Greet quest helper

- src/main/java/com/questhelper/playerquests/bikeshedder/BikeShedder.java
this was used to test https://github.com/Zoinkwiz/quest-helper/pull/1781
> feat(bikeshedder): Add stair highlight in Sunrise Palace

- src/main/java/com/questhelper/helpers/quests/wanted/Wanted.java
Come on now, let's get this straight.
> Fixed grammar in Wanted

- src/main/java/com/questhelper/helpers/miniquests/thegeneralsshadow/TheGeneralsShadow.java
- src/main/java/com/questhelper/helpers/quests/anightatthetheatre/ANightAtTheTheatre.java
- src/main/java/com/questhelper/helpers/quests/defenderofvarrock/DefenderOfVarrock.java
- src/main/java/com/questhelper/helpers/quests/secretsofthenorth/SecretsOfTheNorth.java
- src/main/java/com/questhelper/helpers/quests/sleepinggiants/SleepingGiants.java
- src/main/java/com/questhelper/helpers/quests/theribbitingtaleofalilypadlabourdispute/TheRibbitingTaleOfALilyPadLabourDispute.java
A Night At The Theatre
Defender of Varrock
Sleeping Giants
The Ribbiting Tale of a Lily Pad Labour Dispute
> Just a few small changes to quests of stuff that I noticed on 4 quests and a miniquest

- src/main/java/com/questhelper/helpers/quests/aporcineofinterest/APorcineOfInterest.java
Small little thing I noticed when doing the quest
> Turael can no longer assign sourhogs

- src/main/java/com/questhelper/helpers/quests/shilovillage/ShiloVillage.java
> fix: Check bank for belt in Shilo Village

- src/main/java/com/questhelper/collections/ItemCollections.java
reported in the wiki discord, i couldn't figure out the pattern so I just stuck it at the top
> fix: add zaryte crossbow to the list of crossbows

- src/main/java/com/questhelper/panel/QuestOverviewPanel.java
this prevents a bunch of repaints/revalidations that cause some flickering
> fix: more carefully update text labels in case their text update

- src/main/java/com/questhelper/helpers/quests/thefeud/TheFeud.java
> Fix The Feud: Ali Morrisane start quest dialogue changes

- src/main/java/com/questhelper/panel/QuestHelperPanel.java
Fixes #1877
Some minor unrelated changes
> fix: random panel resize

- src/main/java/com/questhelper/helpers/quests/eaglespeak/EaglesPeak.java
- Include full silver room in silver room zone - the conditional step could lose track if the user was standing right where the ferret (or whatever animal that was) came out and you had to threaten it
- Add some substeps to ensure sidebar doesn't lose track
- Add the "exit" step of each feather room to the sidebar to ensure sidebar doesn't lose track
- mini wording fix
> Eagles Peak: minor polish

- src/main/java/com/questhelper/helpers/quests/thefremennikexiles/TheFremennikExiles.java
add mining quest requirement for The Fremennik Exiles quest
> hansen:TheFremennikExiles

- src/main/java/com/questhelper/helpers/quests/misthalinmystery/MisthalinMystery.java
Mostly reformats, look specifically at the `polish` commit for the actual meaty changes
> Misthalin Mystery: minor polish

- src/main/java/com/questhelper/helpers/quests/ragandboneman/RagAndBoneManI.java
- src/main/java/com/questhelper/helpers/quests/ragandboneman/RagBoneGroups.java
- src/main/java/com/questhelper/helpers/quests/ragandboneman/RagBoneState.java
- Fixed the "frog leg" step not being correctly found through the widget search because name was wrong
- Add a missing dialog step hint for the start of the quest
> Rag and Bone Man I: Minor polish

- src/main/java/com/questhelper/helpers/achievementdiaries/lumbridgeanddraynor/LumbridgeEasy.java
- Add alternate NPC ID for Sedridor. This might be league specific?
- Add alternate dialog text for talking to sedridor. This might also be league specific?
> Lumbridge & Draynor Easy Diary: Minor polish

- src/main/java/com/questhelper/helpers/achievementdiaries/morytania/MorytaniaEasy.java
- Added a hint for where you can get the Wolfbane dagger again if you lost it
- Highlight the bones when they need to be used on the ectofuntus grinder thing
- Fix the order of the ectofuntus steps (they were reversed before)
> Morytania Easy Diary: Minor polish

- src/main/java/com/questhelper/QuestHelperPlugin.java
- src/main/java/com/questhelper/helpers/quests/coldwar/ColdWar.java
- src/main/java/com/questhelper/helpers/quests/misthalinmystery/MisthalinMystery.java
- src/main/java/com/questhelper/helpers/quests/thefeud/TheFeud.java
- src/main/java/com/questhelper/helpers/quests/therestlessghost/TheRestlessGhost.java
- src/main/java/com/questhelper/managers/QuestManager.java
- src/main/java/com/questhelper/panel/PanelDetails.java
- src/main/java/com/questhelper/panel/QuestOverviewPanel.java
- src/main/java/com/questhelper/panel/QuestStepPanel.java
- src/main/java/com/questhelper/steps/ConditionalStep.java
- src/main/java/com/questhelper/steps/QuestStep.java
- src/test/java/com/questhelper/questhelpers/QuestHelperTest.java
This test is kinda chonky, it takes 2min12sec to run on my computer. Some big quests have a lot of steps!
I'm sure it can be optimized, especially since I keep creating the same-ish swing objects over and over again.
> test: ensure quest steps have sidebar step

- src/main/java/com/questhelper/helpers/quests/beneathcursedsands/BeneathCursedSands.java
fixes #1699 but not like linking the discussion matters anyway since you can't auto close discussions with PRs
unlucky that this has always been broken tho
> fix: beneath cursed sands recommendations

- src/main/java/com/questhelper/helpers/quests/insearchofthemyreque/InSearchOfTheMyreque.java
Making the helper more informative for this quest by including rec items, expanding the notes section, adding tooltips. From the feedback in the linked issue.
closes #1948
> In search of the myreque quest #1948

- src/main/java/com/questhelper/helpers/quests/regicide/Regicide.java
Fix a minor typo (`your` -> `you`).
> fix typo in Regicide

- src/main/java/com/questhelper/helpers/quests/whileguthixsleeps/WhileGuthixSleeps.java
Small tuning of phrasing/punction in a couple locations.
This was brought to our attention via Discord
> small wording fixes - While Guthix Sleeps

- src/main/java/com/questhelper/helpers/quests/contact/Contact.java
It is now clear that you should bring antipoisons for defense in the tunnel and scarab fight.
> added antipoison to Contact items

- src/main/java/com/questhelper/QuestHelperPlugin.java
- src/main/java/com/questhelper/bank/GroupBank.java
- src/main/java/com/questhelper/bank/QuestBank.java
- src/main/java/com/questhelper/managers/QuestBankManager.java
- src/main/java/com/questhelper/managers/QuestContainerManager.java
- src/main/java/com/questhelper/panel/QuestRequirementsPanel.java
- src/main/java/com/questhelper/requirements/item/ItemRequirement.java
- src/main/java/com/questhelper/requirements/item/TrackedContainers.java
This won't do anything fancy like knowing when others edit it, but you can know your last known state.
> feat: Added Group Ironman Storage to TrackedContainers

- src/main/java/com/questhelper/helpers/quests/deserttreasureii/WhispererSteps.java
Post-quest the whisperer heals to 140HP but during the quest it is only 100.
> Update whisperer healing

- src/main/java/com/questhelper/bank/banktab/QuestHelperBankTagService.java
- src/main/java/com/questhelper/helpers/mischelpers/farmruns/CropState.java
- src/main/java/com/questhelper/helpers/mischelpers/farmruns/FarmingConfigChangeHandler.java
- src/main/java/com/questhelper/helpers/mischelpers/farmruns/FarmingHandler.java
- src/main/java/com/questhelper/helpers/mischelpers/farmruns/FarmingPatch.java
- src/main/java/com/questhelper/helpers/mischelpers/farmruns/FarmingRegion.java
- src/main/java/com/questhelper/helpers/mischelpers/farmruns/FarmingUtils.java
- src/main/java/com/questhelper/helpers/mischelpers/farmruns/FarmingWorld.java
- src/main/java/com/questhelper/helpers/mischelpers/farmruns/HerbRun.java
- src/main/java/com/questhelper/helpers/mischelpers/farmruns/PatchImplementation.java
- src/main/java/com/questhelper/helpers/mischelpers/farmruns/PatchPrediction.java
- src/main/java/com/questhelper/helpers/mischelpers/farmruns/PatchState.java
- src/main/java/com/questhelper/helpers/mischelpers/farmruns/PatchStates.java
- src/main/java/com/questhelper/helpers/mischelpers/farmruns/PaymentTracker.java
- src/main/java/com/questhelper/helpers/mischelpers/farmruns/TreeRun.java
- src/main/java/com/questhelper/questinfo/QuestHelperQuest.java
- src/main/java/com/questhelper/steps/ObjectStep.java
- src/main/java/com/questhelper/steps/QuestStep.java
- src/main/java/com/questhelper/steps/widget/WidgetHighlight.java
- src/test/java/com/questhelper/MockedTest.java
Recreated as of all the recent changes resulting in a lot of conflicts and issues. I've fixed some shared tree area steps being skipped. Did a full run myself and seems to be working now.
Recreation of #1586
> Tree run helper

- src/main/java/com/questhelper/helpers/quests/deserttreasureii/VardorvisSteps.java
> Fix Kasonde's name in DT2

- src/main/java/com/questhelper/bank/banktab/QuestBankTab.java
More options were added to the bank when taking out items, so this needs to be accounted for now in the quest bank.
> fix: Updated bank withdraw options to work with new bank changes

- src/main/java/com/questhelper/managers/QuestManager.java
- src/main/java/com/questhelper/panel/QuestRequirementsPanel.java
- src/test/java/com/questhelper/MockedTest.java
Allows user to also get item info in the NER plugin.
Preferably this can check if the player has the NER plugin downloaded before showing the option, unsure how to do that though.
> feat: Added NER support

- src/main/java/com/questhelper/helpers/quests/thedigsite/TheDigSite.java
> fix: Digsite cup of tea gameval

- src/main/java/com/questhelper/helpers/quests/theforsakentower/JugPuzzle.java
https://github.com/Zoinkwiz/quest-helper/issues/2039
> Changes the wording from south east to south west for the furnace puzzle in The Forsaken Tower quest

- src/main/java/com/questhelper/helpers/achievementdiaries/falador/FaladorEasy.java
- src/main/java/com/questhelper/helpers/quests/theknightssword/TheKnightsSword.java
Adds note tip to 'The Knight's Sword' mine additional blurite ore and to smelt an additional bar which is required for Falador Easy Diary
> Adds note tip to 'The Knight's Sword' to mine additional blurite

- src/main/java/com/questhelper/helpers/quests/enakhraslament/EnakhrasLament.java
Normal logs are now to be used on the south west brazier and Willow Logs on the south east brazier
https://github.com/Zoinkwiz/quest-helper/issues/2111
> Swaps normal logs and willows logs brazier for the Enakhra's Lament quest

- src/main/java/com/questhelper/panel/questorders/IronmanOptimalQuestGuide.java
- src/main/java/com/questhelper/panel/questorders/OptimalQuestGuide.java
- src/main/java/com/questhelper/panel/questorders/ReleaseDate.java
only an update to the ironman order, updated 2025-07-14
just reran reformatting on other orders too while i was checking for updates
> chore: update quests order

- src/main/java/com/questhelper/helpers/miniquests/skippyandthemogres/SkippyAndTheMogres.java
> fix: typo in Skippy and the Mogres mini quest

- src/main/java/com/questhelper/helpers/quests/recruitmentdrive/RecruitmentDrive.java
> fix: typo in Recruitment Drive

- src/main/java/com/questhelper/helpers/quests/ImpendingChaos/ImpendingChaos.java
- src/main/java/com/questhelper/helpers/quests/anexistentialcrisis/AnExistentialCrisis.java
- src/main/java/com/questhelper/helpers/quests/scrambled/Scrambled.java
- src/main/java/com/questhelper/helpers/quests/shadowsofcustodia/ShadowsOfCustodia.java
- src/main/java/com/questhelper/helpers/quests/thefinaldawn/TheFinalDawn.java
- src/main/java/com/questhelper/helpers/quests/valetotems/ValeTotems.java
- src/main/java/com/questhelper/panel/questorders/IronmanOptimalQuestGuide.java
- src/main/java/com/questhelper/panel/questorders/OptimalQuestGuide.java
- src/main/java/com/questhelper/panel/questorders/ReleaseDate.java
- src/main/java/com/questhelper/questinfo/QuestHelperQuest.java
- src/main/java/com/questhelper/questinfo/QuestVarbits.java
define/prepare all Varlamore part 3 quests
hopefully this would make merging in future quest helpers a little bit less merge-conflicty
> chore: prepare Varlamore Part 3 quests

- src/main/java/com/questhelper/panel/QuestOverviewPanel.java
- src/main/java/com/questhelper/panel/QuestStepPanel.java
JTextPane's allow for text wrapping, meaning quest sectinos have more text to play with.
I have reduced the bottom offset to retain as much of the previous look as possible, as JTextPane does its positioning slightly different to a JLabel.
> feat: make quest section headers a JTextPane instead of JLabel

- src/main/java/com/questhelper/helpers/mischelpers/strongholdofsecurity/StrongholdOfSecurity.java
- src/test/java/com/questhelper/questhelpers/QuestHelperTest.java
Commits are now properly order in refactor -> actual changes, so it should be trivial to review in two steps with GitHub's diff range view
What has changed:
I fixed some steps being lost in the sidebar
I added some missing answers
I made all varbit things use gamevals
I reorganized the methods to make more sense (more of a me thing)
I removed setupConditions and merged them into setupRequirements. I see conditions & requirements as the same
> polish: Stronghold of Security

- src/main/java/com/questhelper/helpers/quests/impcatcher/ImpCatcher.java
- src/test/java/com/questhelper/questhelpers/QuestHelperTest.java
basically nothing changed, just a sidebar step changed and some refactors
> polish: Imp Catcher

- src/main/java/com/questhelper/helpers/quests/misthalinmystery/MisthalinMystery.java
- src/test/java/com/questhelper/questhelpers/QuestHelperTest.java
This PR adds puzzle wrapper steps around the third and fourth puzzle, but not the first or second one. I didn't think to add them until I had already passed the
> polish: Misthalin Mystery

- src/main/java/com/questhelper/helpers/quests/clientofkourend/ClientOfKourend.java
- src/test/java/com/questhelper/questhelpers/QuestHelperTest.java
Mostly gameval/teleport suggestions, and handling the case where a user can destroy their enchanted scroll after making the quill which would cause the quest to lock up
> polish: Client of Kourend

- src/main/java/com/questhelper/helpers/quests/romeoandjuliet/RomeoAndJuliet.java
- src/test/java/com/questhelper/questhelpers/QuestHelperTest.java
Just some object highlights & quest start dialog steps, rest is good
> polish: Romeo & Juliet

- src/main/java/com/questhelper/helpers/quests/gertrudescat/GertrudesCat.java
- src/test/java/com/questhelper/questhelpers/QuestHelperTest.java
A bunch of modernization/refactoring to remove "needless" functions. I'm sure this quest could use another polish pass, but it works as expected now and has directions I found helpful
> polish: Gertrude's Cat

- src/main/java/com/questhelper/helpers/quests/fightarena/FightArena.java
- src/test/java/com/questhelper/questhelpers/QuestHelperTest.java
Mostly modernizing, otherwise I have:
- Added some missing dialog steps
- Highlighted safe spots inside the arena
> polish: Fight Arena

- src/main/java/com/questhelper/helpers/quests/hazeelcult/HazeelCult.java
- src/main/java/com/questhelper/helpers/quests/hazeelcult/HazeelValves.java
- src/test/java/com/questhelper/questhelpers/QuestHelperTest.java
Mostly modernizing/reorganizing. This quest is a bit tricky since making changes to one side while siding with the other feels risky. I sided with the Hazeel side, so that's where I could polish things the most.
> polish: Hazeel Cult

- src/main/java/com/questhelper/helpers/quests/plaguecity/PlagueCity.java
- src/test/java/com/questhelper/questhelpers/QuestHelperTest.java
Clean quest!
Modernized, fixed an NPC ID that was wrong since the gameval update (wilderness cape seller 8?), updated the bucket of water tooltip, gameval'd a varbit, and updated some quest step texts
> polish: Plague City

- src/main/java/com/questhelper/helpers/quests/biohazard/Biohazard.java
- src/test/java/com/questhelper/questhelpers/QuestHelperTest.java
Mostly refactors, one dialog highlight missing, and some step dedupes
> polish: Biohazard

- src/main/java/com/questhelper/panel/PanelDetails.java
little helper function to create Diary sidebar steps a bit more easily
Covers every usecase for Ardougne Easy at least - if it ends up not being useful later it should be easy to revert
> feat(PanelDetails): static locked panel creator

- src/main/java/com/questhelper/helpers/quests/piratestreasure/PiratesTreasure.java
- src/main/java/com/questhelper/helpers/quests/piratestreasure/RumSmugglingStep.java
Had to make these changes very carefully since it's one of those quests that have like 4 total states
> polish: Pirate's Treasure

- src/main/java/com/questhelper/helpers/quests/dwarfcannon/DwarfCannon.java
- src/test/java/com/questhelper/questhelpers/QuestHelperTest.java
> polish: Dwarf Cannon

- src/main/java/com/questhelper/helpers/quests/toweroflife/TowerOfLife.java
clarify that you need to wear the builder's outfit (for when you don't have your inventory open)
> polish: tower of life

- src/main/java/com/questhelper/helpers/achievementdiaries/wilderness/WildernessMedium.java
Closes #2300
Discord report: https://discord.com/channels/772056816242130964/1402052774924914739
> fix(Wilderness Medium): Woodcutting requirement is not boostable

- src/main/java/com/questhelper/panel/queststepsection/AbstractQuestSection.java
- src/main/java/com/questhelper/panel/queststepsection/QuestSectionSection.java
- src/main/java/com/questhelper/panel/queststepsection/QuestStepPanel.java
Just some minor nits I found when reviewing
> feedback: multitier panels

- src/main/java/com/questhelper/helpers/quests/holygrail/HolyGrail.java
- src/test/java/com/questhelper/questhelpers/QuestHelperTest.java
Just minor polish - there's still some cleanup that could be done (e.g. recommended items that show up in the main list but nowhere else)
> polish: Holy Grail

- src/main/java/com/questhelper/helpers/quests/songoftheelves/SongOfTheElves.java
From Discord: https://discord.com/channels/772056816242130964/1418374887168278538
> fix(Song of the Elves): rub crystal seed, not teleport crystal

- src/main/java/com/questhelper/helpers/quests/deathontheisle/DeathOnTheIsle.java
- src/main/java/com/questhelper/requirements/npc/NoFollowerRequirement.java
- src/test/java/com/questhelper/questhelpers/QuestHelperTest.java
> polish: Death on the Isle
